### ISSUE TITLE
TensorFlow support in DJL and NDArrays

### ISSUE THREAD

**Issue by karllessard** [awslabs/djl#1]
Hi,

This is not really a feature request but I thought it would be easy to reach out to the DJL community here, so please close this issue whenever you wish.

I represent the official group responsible of maintaining and enhancing the support of TensorFlow on the JVM. We have just heard of your initiative and we are very excited about it. We would like to know if there is anything we can do to help with the integration of TensorFlow in DJL.

Also, we would like to open a discussion about the NDArray standardization. There is already a few implementations of this interface available on the market (e.g. MXNet has one, DL4J has one, we have just created one and now AWS has one). To improve portability between various frameworks and libraries, we believe that such an interface should eventually end up in the JDK itself and it would be a good candidate for a JSR/JEP. It would be interesting to see all parties actually involved in the development of a "NumPy equivalent" for Java to agree on a common interface that could then be proposed to the Java community, on top of which higher-level APIs can be built.

If you are interested, it is possible to reach us directly on one the following channels:

Google Group: jvm@tensorflow.org
Gitter: tensorflow/sig-jvm
GitHub: https://github.com/tensorflow/java

Thanks, hoping to hear from you soon,

Karl

**Comment by frankfliu** [comment]
@karllessard 
Thank you very much for reaching to us. I think we share the same vision that NDArray need to be standardized. We are eager to get comments and opinions. We are not satisfied with our current NDArray interface, we need more voice from java community to guide us how to make it better.

Hope to talk to you soon.

**Comment by agibsonccc** [comment]
@frankfliu Hi Frank. The dl4j team is working within sig-jvm already.

 We already did a lot of this work within our tensor framework including proper numpy interop. We have a parallel "engine" with our own garbage collection, implementations of various operations in c/c++ and are happy to share our work with the community.
We expect there to be different opinions on how things should be done. We'll at least try to work with the team to contribute an engine for this as well.

Our team (not sig-jvm, just dl4j) has chatted with the team over at the jdk before and it does not seem like there is an interest in building a proper ndarray interface.

We would be happy to host this kind of work over at the eclipse foundation however through the jakarta spec already implemented: https://jakarta.ee/about/jesp/

If this is interesting, maybe we can start a discussion on standardization.
It's probably best to have a separate issue for this maybe?

**Comment by karllessard** [comment]
I think we all agree that DJL's GitHub is probably not the best channel for starting our discussion on NDArrays standardization, so I've created this public and informal Google Group where all parties can share their ideas on what this specification should look like and how it can be standardized:

https://groups.google.com/forum/#!forum/java-ndarray-standardization

Please also share with anyone you think might be interested, thanks!

**Comment by agibsonccc** [comment]
@karllessard thanks. I'm ok with this for now.

**Comment by frankfliu** [comment]
@karllessard 
Sorry for the delay due to holidays.
We are more than happy to accept support from you guys. Would you mind to schedule a call to sync up? I really looking forward to talk to you guys and share our vision and goal. And we can discuss how can we collaborate on NDArrays standardization as well.

**Comment by karllessard** [comment]
Hi @frankfliu, sounds good, the SIG has a monthly community call which could be a nice opportunity to sync up. This month though might be special though as it occurs during the holidays (December 27th) and I don't know how many people will be able to attend to it, including in your team.

So if that doesn't work on your side, we can setup a special meeting early January and send an invite to the SIG or just wait for the next meeting (January 24th), please let me know your preference

**Comment by frankfliu** [comment]
@karllessard 
I'm afraid most of our members are out on December 27th. It would be nice if we can schedule something early January. We can jump on next meeting on Jan 24th if that doesn't work.

**Comment by karllessard** [comment]
Ok @frankfliu , let's do this then on our Jan 24th meeting, that will give you also an opportunity to know better how those sessions work if your team wants to assist on a regular basis.

**Comment by frankfliu** [comment]
DJL 0.5.0 release implemented tensorflow engine which support TF 2.1.0 version.

**Comment by saudet** [comment]
@frankfliu Great! How are you performing the builds?

**Comment by frankfliu** [comment]
@saudet we decide not to support windows in 0.5.0.

**Comment by saudet** [comment]
Ah, so you're still relying on TensorFlow SIG JVM to perform the builds.
@karllessard @joanafilipa @ananthr We really need to get this fixed.
