### ISSUE TITLE
TrainResnetWithCifar10例子中存在一个错误

### ISSUE THREAD

**Issue by yanchaoguo** [awslabs/djl#100]
我按照例子在自己的10分类数据集上进行测试 发现存储的模型无法得到正确的输出 抛出数组越界的错误，经排查： newBlock.add(x -> new NDList(x.singletonOrThrow().squeeze()));这段代码会导致预测时网络出错
应改为newBlock.add(Blocks.batchFlattenBlock());

参考：
https://github.com/awslabs/djl/blob/468ba99815d57e17ae349d072da36be1cc31cdbd/model-zoo/src/main/java/ai/djl/basicmodelzoo/cv/classification/ResNetV1.java

**Comment by frankfliu** [comment]
@yanchaoguo I'm working on a fix and adding inference in example.
The last block should be: newBlock.add(Blocks.batchFlattenBlock(10));

**Comment by yanchaoguo** [comment]
> @yanchaoguo I'm working on a fix and adding inference in example.
> The last block should be: newBlock.add(Blocks.batchFlattenBlock(10));

When will it be submitted? Besides, can you provide an example about image feature extraction to examples

**Comment by frankfliu** [comment]
Fixed with commit: https://github.com/awslabs/djl/commit/1775305152a3611876b0bd3487d9d202761d22ea

@yanchaoguo for the image feature extraction, the solution you proposed is specific to MXNet. We didn't find a generic and elegant way to implement such an API. Use can implement such a solution as you described themselves. We will keep to explore a solution in future.

**Comment by yanchaoguo** [comment]
@frankfliu 迁移学习例子中如果将 newBlock.add(x -> new NDList(x.singletonOrThrow().squeeze()));这段代码替换为newBlock.add(Blocks.batchFlattenBlock()); 在我的10分类数据集上进行相同epoch模型训练，会得到更好的准确率

**Comment by roywei** [comment]
Hi @yanchaoguo 经讨论我们会改成用batchFlatten()，不过我们觉得并不会影响训练准确度。因为不管是squeeze还是batch flatten都只是改变形状，并不会多学习到一些feature。
请问在你的数据集上准确率能提升多少？跑相同的epoch，准确率的差别会不会是由于初始化的不同导致的？假设给与足够多的epoch数，不管用哪个，理论上应该都能到达相同的准确率。

**Comment by yanchaoguo** [comment]
> Hi @yanchaoguo 经讨论我们会改成用batchFlatten()，不过我们觉得并不会影响训练准确度。因为不管是squeeze还是batch flatten都只是改变形状，并不会多学习到一些feature。
> 请问在你的数据集上准确率能提升多少？跑相同的epoch，准确率的差别会不会是由于初始化的不同导致的？假设给与足够多的epoch数，不管用哪个，理论上应该都能到达相同的准确率。

这是我做的实验  十个类汽车数据集 每个类大学有500张图片  都是训练了50次，结果是batchFlatten()这种方式得到的模型 效果要远远好于另一种，你们也可以测试一下
链接: https://pan.baidu.com/s/1C6YFzERknzsYFaVzm5mjug 提取码: qx8g  源码工程

**Comment by stu1130** [comment]
@yanchaoguo in our transfer learning example, we use MXNet model which doesn't flatten right before the Linear block (fullyconnected) as MXNet [fullyconnected](https://beta.mxnet.io/api/ndarray/_autogen/mxnet.ndarray.FullyConnected.html) can do the flatten operation for you. As a result, you need to explicitly add batchFlatten() here. It is pretty common in TensorFlow and PyTorch model as well.

**Comment by stu1130** [comment]
I will go ahead to close the issue, please feel free to reopen the issue.
