### ISSUE TITLE
Mnist - memory issue

### ISSUE THREAD

**Issue by berry120** [awslabs/djl#106]
## Description
While trying to run the `Mnist` sample, I get to around 80% through and then hit a `ai.djl.engine.EngineException: MXNet engine call failed: MXNetError: can't alloc`. The same behaviour occurs if I run the minimal tutorial sample below.

I'm on Windows, using `mxnet-native-auto:1.7.0-a` and `0.5.0` of the various `djl` libraries.

This *may not* be a bug at all - I only have 8GB RAM which is hardly much, and it uses about 2-3GB before dying. It could simply be that this is expected behaviour and I need to upgrade, this machine is getting on for 10 years old now...

The reason I think it *may* be a bug is because if I comment out:

    batch.close();

...then I see no discernible difference to memory usage. I'd expect the `batch.close()` to free up some memory and make the problem *worse*, but I may be misunderstanding the purpose of this call.

## How to Reproduce?

    Mnist mnist = Mnist.builder()
            .setSampling(32, true)
            .build();
    mnist.prepare(new ProgressBar());

    Model model = Model.newInstance();

    model.setBlock(new Mlp(28 * 28, 10, new int[]{128, 64}));

    DefaultTrainingConfig config = new DefaultTrainingConfig(Loss.softmaxCrossEntropyLoss())
            .addEvaluator(new Accuracy())
            .addTrainingListeners(TrainingListener.Defaults.logging());

    Trainer trainer = model.newTrainer(config);
    trainer.initialize(new Shape(1, 28 * 28));

    for (Batch batch : trainer.iterateDataset(mnist)) {
        trainer.trainBatch(batch);
        trainer.step();
        batch.close();
    }

## Environment Info

[INFO ] - ----------System Properties----------
[INFO ] - sun.desktop: windows
[INFO ] - awt.toolkit: sun.awt.windows.WToolkit
[INFO ] - java.specification.version: 11
[INFO ] - sun.cpu.isalist: amd64
[INFO ] - sun.jnu.encoding: Cp1252
[INFO ] - java.class.path: C:\Users\Michael\Desktop\djlsource\integration\build\classes\java\main;C:\Users\Michael\Desktop\djlsource\integration\build\resources\main;C:\Users\Michael\.g
radle\caches\modules-2\files-2.1\commons-cli\commons-cli\1.4\c51c00206bb913cd8612b24abd9fa98ae89719b1\commons-cli-1.4.jar;C:\Users\Michael\.gradle\caches\modules-2\files-2.1\org.apache.
logging.log4j\log4j-slf4j-impl\2.12.1\14973e22497adaf0196d481fb99c5dc2a0b58d41\log4j-slf4j-impl-2.12.1.jar;C:\Users\Michael\Desktop\djlsource\basicdataset\build\libs\basicdataset-0.6.0-
SNAPSHOT.jar;C:\Users\Michael\Desktop\djlsource\model-zoo\build\libs\model-zoo-0.6.0-SNAPSHOT.jar;C:\Users\Michael\Desktop\djlsource\testing\build\libs\testing-0.6.0-SNAPSHOT.jar;C:\Use
rs\Michael\.gradle\caches\modules-2\files-2.1\org.testng\testng\6.8.1\8aebea980eee079365df20f0cf7fcac900d50250\testng-6.8.1.jar;C:\Users\Michael\Desktop\djlsource\mxnet\mxnet-model-zoo\
build\libs\mxnet-model-zoo-0.6.0-SNAPSHOT.jar;C:\Users\Michael\Desktop\djlsource\mxnet\mxnet-engine\build\libs\mxnet-engine-0.6.0-SNAPSHOT.jar;C:\Users\Michael\.gradle\caches\modules-2\
files-2.1\ai.djl.mxnet\mxnet-native-auto\1.7.0-a-SNAPSHOT\6a05ab7a720a1f7e970715a55a9819defbd59679\mxnet-native-auto-1.7.0-a-SNAPSHOT.jar;C:\Users\Michael\Desktop\djlsource\api\build\li
bs\api-0.6.0-SNAPSHOT.jar;C:\Users\Michael\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.26\77100a62c2e6f04b53977b9f541044d7d722693d\slf4j-api-1.7.26.jar;C:\Users\Michael\.
gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-core\2.12.1\4382e93136c06bfb34ddfa0bb8a9fb4ea2f3df59\log4j-core-2.12.1.jar;C:\Users\Michael\.gradle\caches\modules-2\fil
es-2.1\org.apache.logging.log4j\log4j-api\2.12.1\a55e6d987f50a515c9260b0451b4fa217dc539cb\log4j-api-2.12.1.jar;C:\Users\Michael\.gradle\caches\modules-2\files-2.1\org.beanshell\bsh\2.0b
4\a05f0a0feefa8d8467ac80e16e7de071489f0d9c\bsh-2.0b4.jar;C:\Users\Michael\.gradle\caches\modules-2\files-2.1\com.beust\jcommander\1.27\58c9cbf0f1fa296f93c712f2cf46de50471920f9\jcommande
r-1.27.jar;C:\Users\Michael\.gradle\caches\modules-2\files-2.1\org.yaml\snakeyaml\1.6\a1e23e31c424d566ee27382e373d73a28fdabd88\snakeyaml-1.6.jar;C:\Users\Michael\.gradle\caches\modules-
2\files-2.1\com.google.code.gson\gson\2.8.5\f645ed69d595b24d4cf8b3fbb64cc505bede8829\gson-2.8.5.jar;C:\Users\Michael\.gradle\caches\modules-2\files-2.1\net.java.dev.jna\jna\5.3.0\4654d1
da02e4173ba7b64f7166378847db55448a\jna-5.3.0.jar;C:\Users\Michael\.gradle\caches\modules-2\files-2.1\org.apache.commons\commons-compress\1.20\b8df472b31e1f17c232d2ad78ceb1c84e00c641b\co
mmons-compress-1.20.jar
[INFO ] - java.vm.vendor: AdoptOpenJDK
[INFO ] - sun.arch.data.model: 64
[INFO ] - user.variant:
[INFO ] - java.vendor.url: https://adoptopenjdk.net/
[INFO ] - user.timezone: Europe/London
[INFO ] - os.name: Windows 10
[INFO ] - java.vm.specification.version: 11
[INFO ] - org.apache.logging.log4j.assignedSequences: 6991
[INFO ] - sun.java.launcher: SUN_STANDARD
[INFO ] - user.country: GB
[INFO ] - sun.boot.library.path: C:\Program Files\Java\jdk-11.0.1+13\bin;C:\Program Files\Java\jdk-11.0.1+13\bin
[INFO ] - sun.java.command: ai.djl.integration.util.DebugEnvironment
[INFO ] - jdk.debug: release
[INFO ] - sun.cpu.endian: little
[INFO ] - user.home: C:\Users\Michael
[INFO ] - org.gradle.appname: gradlew
[INFO ] - user.language: en
[INFO ] - java.specification.vendor: Oracle Corporation
[INFO ] - java.version.date: 2018-10-16
[INFO ] - java.home: C:\Program Files\Java\jdk-11.0.1+13
[INFO ] - ai.djl.logging.level: debug
[INFO ] - org.gradle.internal.http.connectionTimeout: 60000
[INFO ] - file.separator: \
[INFO ] - java.vm.compressedOopsMode: 32-bit
[INFO ] - line.separator:

[INFO ] - java.specification.name: Java Platform API Specification
[INFO ] - java.vm.specification.vendor: Oracle Corporation
[INFO ] - java.awt.graphicsenv: sun.awt.Win32GraphicsEnvironment
[INFO ] - user.script:
[INFO ] - sun.management.compiler: HotSpot 64-Bit Tiered Compilers
[INFO ] - java.runtime.version: 11.0.1+13
[INFO ] - user.name: Michael
[INFO ] - path.separator: ;
[INFO ] - os.version: 10.0
[INFO ] - java.runtime.name: OpenJDK Runtime Environment
[INFO ] - file.encoding: Cp1252
[INFO ] - java.vm.name: OpenJDK 64-Bit Server VM
[INFO ] - java.vendor.version: AdoptOpenJDK
[INFO ] - java.vendor.url.bug: http://bugreport.java.com/bugreport/
[INFO ] - java.io.tmpdir: C:\Users\Michael\AppData\Local\Temp\
[INFO ] - org.gradle.internal.http.socketTimeout: 120000
[INFO ] - java.version: 11.0.1
[INFO ] - user.dir: C:\Users\Michael\Desktop\djlsource\integration
[INFO ] - os.arch: amd64
[INFO ] - java.vm.specification.name: Java Virtual Machine Specification
[INFO ] - java.awt.printerjob: sun.awt.windows.WPrinterJob
[INFO ] - sun.os.patch.level:
[INFO ] - java.library.path: C:\Program Files\Java\jdk-11.0.1+13\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\P
rogram Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\AMD\ATI.ACE
\Core-Static;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files
 (x86)\MiKTeX 2.9\miktex\bin\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC;C:\WINDOWS\sy
stem32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\MySQL\MySQL Utilities
 1.6\;C:\Program Files\TortoiseGit\bin;C:\Program Files\curl-7.54.1-win64-mingw\bin;C:\Program Files\gradle-4.2.1\bin;C:\Program Files\ffmpeg-20171109-723b6ba-win64-static\bin;C:\WINDOW
S\System32\OpenSSH\;C:\Program Files\Apache Software Foundation\apache-maven-3.5.3\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\get_iplayer;C:\Program Files (x86)\S
calyr\bin\;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_111\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Users\Michael\AppData\Local\Programs\Python\Pytho
n37\Scripts;C:\Program Files\ngrok;C:\Program Files\Apache Software Foundation\apache-maven-3.6.2\bin;;C:\Program Files\Amazon\AWSCLI\bin\;C:\Program Files\Docker\Docker\resources\bin;C
:\ProgramData\DockerDesktop\version-bin;C:\Ruby25-x64\bin;C:\Users\Michael\AppData\Local\Microsoft\WindowsApps;C:\Program Files\sfdx\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\
Michael\AppData\Roaming\npm;C:\Users\Michael\AppData\Local\Yarn\bin;C:\Users\Michael\AppData\Local\Keybase\;.
[INFO ] - java.vendor: AdoptOpenJDK
[INFO ] - java.vm.info: mixed mode
[INFO ] - java.vm.version: 11.0.1+13
[INFO ] - sun.io.unicode.encoding: UnicodeLittle
[INFO ] - library.jansi.path: C:\Users\Michael\.gradle\native\jansi\1.18\windows64
[INFO ] - java.class.version: 55.0
[INFO ] - org.gradle.internal.publish.checksums.insecure: true
[INFO ] -
[INFO ] - ----------Environment Variables----------
[INFO ] - USERDOMAIN_ROAMINGPROFILE: mdev
[INFO ] - PROCESSOR_LEVEL: 6
[INFO ] - FP_NO_HOST_CHECK: NO
[INFO ] - VS140COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
[INFO ] - SESSIONNAME: Console
[INFO ] - ALLUSERSPROFILE: C:\ProgramData
[INFO ] - PROCESSOR_ARCHITECTURE: AMD64
[INFO ] - ANDROID_HOME: C:\Users\Michael\AppData\Local\Android\sdk
[INFO ] - PSModulePath: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
[INFO ] - __INTELLIJ_COMMAND_HISTFILE__: C:\Users\Michael\AppData\Roaming\JetBrains\IntelliJIdea2020.1\terminal\history\history-140
[INFO ] - SystemDrive: C:
[INFO ] - =ExitCode: 00000000
[INFO ] - MAVEN_HOME: C:\Program Files\Apache Software Foundation\apache-maven-3.5.3
[INFO ] - DIRNAME: C:\Users\Michael\Desktop\djlsource\
[INFO ] - USERNAME: Michael
[INFO ] - CMD_LINE_ARGS: debugEnv
[INFO ] - ProgramFiles(x86): C:\Program Files (x86)
[INFO ] - FPS_BROWSER_USER_PROFILE_STRING: Default
[INFO ] - APP_HOME: C:\Users\Michael\Desktop\djlsource\
[INFO ] - PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW
[INFO ] - DriverData: C:\Windows\System32\Drivers\DriverData
[INFO ] - SCALYR: C:\Program Files (x86)\Scalyr\
[INFO ] - SVN_SSH: C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe
[INFO ] - ProgramData: C:\ProgramData
[INFO ] - ProgramW6432: C:\Program Files
[INFO ] - HOMEPATH: \Users\Michael
[INFO ] - PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
[INFO ] - M2_HOME: C:\Program Files\Apache Software Foundation\apache-maven-3.5.3
[INFO ] - ProgramFiles: C:\Program Files
[INFO ] - PUBLIC: C:\Users\Public
[INFO ] - windir: C:\WINDOWS
[INFO ] - =::: ::\
[INFO ] - _SKIP: 2
[INFO ] - LOCALAPPDATA: C:\Users\Michael\AppData\Local
[INFO ] - USERDOMAIN: mdev
[INFO ] - FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
[INFO ] - LOGONSERVER: \\MDEV
[INFO ] - WIX: C:\Program Files (x86)\WiX Toolset v3.11\
[INFO ] - JAVA_HOME: C:\Program Files\Java\jdk-11.0.1+13
[INFO ] - PROMPT: $P$G
[INFO ] - VS120COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
[INFO ] - EASYHDR3: C:\Program Files\easyHDR 3
[INFO ] - asl.log: Destination=file
[INFO ] - OneDrive: C:\Users\Michael\OneDrive
[INFO ] - =C:: C:\Users\Michael\Desktop\djlsource
[INFO ] - APPDATA: C:\Users\Michael\AppData\Roaming
[INFO ] - DOWNLOAD_URL: "https://raw.githubusercontent.com/gradle/gradle/master/gradle/wrapper/gradle-wrapper.jar"
[INFO ] - JAVA_EXE: C:\Program Files\Java\jdk-11.0.1+13/bin/java.exe
[INFO ] - DokanLibrary1: C:\Program Files\Dokan\Dokan Library-1.0.0\
[INFO ] - CommonProgramFiles: C:\Program Files\Common Files
[INFO ] - Path: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C
:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance To
olkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft D
NX\Dnvm\;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86
)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Program Files\TortoiseGit\bin;C:\Program Files\curl-7.54.1-win64-mingw\bin;C:\Program Files\gradle-
4.2.1\bin;C:\Program Files\ffmpeg-20171109-723b6ba-win64-static\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Apache Software Foundation\apache-maven-3.5.3\bin;C:\Program Files\Micr
osoft VS Code\bin;C:\Program Files (x86)\get_iplayer;C:\Program Files (x86)\Scalyr\bin\;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_111\bin;C:\Program Files\nodejs\;C:\Progr
am Files (x86)\Yarn\bin\;C:\Users\Michael\AppData\Local\Programs\Python\Python37\Scripts;C:\Program Files\ngrok;C:\Program Files\Apache Software Foundation\apache-maven-3.6.2\bin;;C:\Pr
ogram Files\Amazon\AWSCLI\bin\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Ruby25-x64\bin;C:\Users\Michael\AppData\Local\Microsoft\WindowsAp
ps;C:\Program Files\sfdx\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\Michael\AppData\Roaming\npm;C:\Users\Michael\AppData\Local\Yarn\bin;C:\Users\Michael\AppData\Local\Keybase\
[INFO ] - GIT_SSH: C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe
[INFO ] - OS: Windows_NT
[INFO ] - COMPUTERNAME: MDEV
[INFO ] - JD2_HOME: C:\Users\Michael\AppData\Local\JDownloader v2.0
[INFO ] - PROCESSOR_REVISION: 2a07
[INFO ] - CLASSPATH: C:\Users\Michael\Desktop\djlsource\\gradle\wrapper\gradle-wrapper.jar
[INFO ] - CommonProgramW6432: C:\Program Files\Common Files
[INFO ] - ComSpec: C:\WINDOWS\system32\cmd.exe
[INFO ] - APP_BASE_NAME: gradlew
[INFO ] - TERMINAL_EMULATOR: JetBrains-JediTerm
[INFO ] - SystemRoot: C:\WINDOWS
[INFO ] - TEMP: C:\Users\Michael\AppData\Local\Temp
[INFO ] - HOMEDRIVE: C:
[INFO ] - USERPROFILE: C:\Users\Michael
[INFO ] - TMP: C:\Users\Michael\AppData\Local\Temp
[INFO ] - VS110COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
[INFO ] - MYSQLCONNECTOR_ASSEMBLIESPATH: C:\Program Files (x86)\MySQL\Connector.NET 6.9\Assemblies\v4.5
[INFO ] - CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
[INFO ] - NUMBER_OF_PROCESSORS: 4
[INFO ] - IDEA_INITIAL_DIRECTORY: C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.3\bin
[INFO ] -
[INFO ] - ----------Default Engine----------
[DEBUG] - Found cudart: C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\cudart64_60.dll
[WARN ] - Failed to detect GPU count: CUDA driver version is insufficient for CUDA runtime version (35)
[WARN ] - Failed to detect GPU count: CUDA driver version is insufficient for CUDA runtime version (35)
[DEBUG] - Loading mxnet library from: C:\Users\Michael\.mxnet\cache\1.7.0-a-SNAPSHOT-20200615mkl-win-x86_64\mxnet.dll
[DEBUG] - Found default engine: MXNet
[INFO ] - Engine name: MXNet
[INFO ] - Engine version: 1.7.0
[WARN ] - Failed to detect GPU count: CUDA driver version is insufficient for CUDA runtime version (35)
[WARN ] - Failed to detect GPU count: CUDA driver version is insufficient for CUDA runtime version (35)
[INFO ] - MXNet Library: C:\Users\Michael\.mxnet\cache\1.7.0-a-SNAPSHOT-20200615mkl-win-x86_64\mxnet.dll
[INFO ] - MXNet Features: SIGNAL_HANDLER, LAPACK, BLAS_OPEN, OPENMP, OPENCV, MKLDNN
[INFO ] -
[INFO ] - ----------Hardware----------
[INFO ] - Available processors (cores): 4
[INFO ] - Byte Order: LITTLE_ENDIAN
[INFO ] - Free memory (bytes): 100901656
[INFO ] - Maximum memory (bytes): 2143289344
[INFO ] - Total memory available to JVM (bytes): 134217728
[INFO ] - Heap committed: 134217728
[INFO ] - Heap nonCommitted: 30474240
[INFO ] - GPU Count: 0
[INFO ] - Default Device: cpu()

**Comment by frankfliu** [comment]
@berry120 This is not a bug.

Comment out batch.close() won't have direct impact on the memory. That's because we close previous batch in the DataIterator when fetching next one. See: https://github.com/awslabs/djl/blob/master/api/src/main/java/ai/djl/training/dataset/DataIterable.java#L127-L129

**Comment by berry120** [comment]
@frankfliu Thanks for the prompt reply. Looks like I'll just need to invest in some more RAM in that case :-)
