### ISSUE TITLE
SentencePiece functionality for DJL

### ISSUE THREAD

**Issue by jmracek** [awslabs/djl#114]
## Description
I am requesting the addition of SentencePiece functionality to DJL.  SentencePiece is an algorithm/[library](https://github.com/google/sentencepiece) for unsupervised text tokenization.  It is commonly applied in many natural language applications; for example, the original BERT paper tokenized text using SentencePiece.  Furthermore, SentencePiece is extremely useful for CJK languages which contain no whitespace separators.  

I try to avoid suggesting specific ways of solving problems in Feature requests, but in this case, I think it would be most straightforward to add a JNI wrapper around the existing native library.  Similar libraries already exist on Github, but don't appear to be well maintained (e.g. [here](https://github.com/dongjinleekr/beanpiece), and [here](https://github.com/levyfan/sentencepiece-jni)).  For production code, I would like to see this functionality added to a better maintained library to stay current with API changes.

### Will this change the current api? How?
I don't believe so.  This would be adding new functionality to the package.  It is possible that some of the code in BertToken and related classes will need to be rewritten to an interface rather than an implementation.

### Who will benefit from this feature?
Anyone working on NLP problems who uses Java.  By now, SentencePiece is a very popular choice of tokenizer, yet I could not find a well maintained Java library which supports it.

## References
[Original paper
](https://arxiv.org/abs/1808.06226)

**Comment by lanking520** [comment]
@jmracek Currently we had JNI built in the extensions. Will add the integration on the DJL API later this week.

**Comment by lanking520** [comment]
@jmracek SentencePiece integration is ready: https://github.com/awslabs/djl/tree/master/extensions/sentencepiece Please try this out

**Comment by frankfliu** [comment]
This feature is part of 0.7.0 release.
