### ISSUE TITLE
how to process model using keras api

### ISSUE THREAD

**Issue by yanchaoguo** [awslabs/djl#115]
## Question
Keras作为一种标准，不知道我们这边是否打算支持

**Comment by frankfliu** [comment]
@yanchaoguo We can load Keras model: https://github.com/awslabs/djl/blob/master/docs/tensorflow/how_to_import_keras_models_in_DJL.md

Keras is a Python API, it's not following Java developer's convention. DJL's API is prioritize Java developer's user experience. If you train the model in DJL, the model can be loaded on different engines. And our goal is to make DJL even simpler than Keras for Java developer.

**Comment by lanking520** [comment]
@yanchaoguo Since Keras now is a part of TF 2.0 API, we are supporting the full inference to it through TF Engine. The API design varies in between different DL Framework. Our plan is to go with a path that similar to Numpy and designed to be simple.

**Comment by frankfliu** [comment]
Feel free to reopen this issue if you have further questions.
