### ISSUE TITLE
Where is package ai.djl.mxnet.zoo.MxModelZoo;?

### ISSUE THREAD

**Issue by LJWxyz** [awslabs/djl#118]
I had no idea where to find the package.
I had v0.6.0 snapshot.jar &docs on my hand.
However to follow the detailed guide at
https://towardsdatascience.com/introducing-deep-java-library-djl-9de98de8c6ca
It seems that the script had that additional package not in the core.
Where to obtain?Thanks

**Comment by LJWxyz** [comment]
i think i found the package inside,just need to manual compile and package i assume?
...\djl-0.6.0\mxnet\mxnet-model-zoo\src\main\java\ai\djl\mxnet\zoo
So yeah,hope in the future can get official support to have a neat jar package that can add to classpath as needed.^_^

**Comment by LJWxyz** [comment]
Additional suggestion>list all the possible extra packages that are not included in the core into the readme.
Eg:if mxmodel package is not included in the snapshot.jar.That 's not a core"/basic package 
List of additional package:
ai.djl.Mxmodel>(if have easy way of obtaining it.else just leave it blank...and hope..reader can find the jar or package it theirself from release or git..which is...)
ai.djl.fasttext.zoo>(?manual compile package jar?.....)
etc...

**Comment by LJWxyz** [comment]
PS,having extensive functionality is fine,but not having an easy way of obtaining an detailed,reliable&fast workable package is also a minus.
Kinda like why some IDE that takes forever to load & the IDE itself needs to be manually cmake is not preferred,unless for security reason.and most text editor bind to the filetype,and can execute at specific OS smoothly after installation.^^

**Comment by LJWxyz** [comment]
Finished compiling and packaging as jar.
The process is smooth as hell.Very impressed.
probably just needed jdk and the core djl lib 
(if not wrong(Very neat and clean i personaly don't mind extra high perf collection lib,but newbie may be confused and give up)
I used zulu openjdk,and djl v060snapshot.jar
compile done
remove all java file with batch script
take it to a neat place package it.
Done.
I don't mind sharing the packaged jar&put it on official readme link to some file hosting service.
I hope the ^suggestion is implemented before this thread is closed though.
Seasoned contributor may close this thread,or simply when a neat smooth process is implemented to get those sweet jars.

**Comment by frankfliu** [comment]
We publish multiple maven packages other than core djl libs: https://djl.ai/website/javadoc.html

For MxModelZoo, you need add this dependency: https://github.com/awslabs/djl/tree/master/mxnet/mxnet-model-zoo#installation

**Comment by lanking520** [comment]
I like this UI more: https://search.maven.org/search?q=g:ai.djl.mxnet . You can find corresponding config from the webpage.

**Comment by LJWxyz** [comment]
awesome!would it be possible to put this few links at somewhere more obvious for newcomers?
like readme or wiki(or anywhere convinient to let new user know where to find those modules)?
Plus i believe all of us will benefit from having easy access to the link.^^
PS,sorry I am rather new to how github works.So,the experienced one gotta implement that to prevent conflicts
After that's done I think this issue had served it's purpose and should close.^^

**Comment by LJWxyz** [comment]
Just as a side question as I am trying the code in the tutorial>when compiling

 **incompatible types: ZooModel<Image,ai.djl.modality.cv.output.DetectedObjects> cannot be converted to ZooModel<BufferedImage,ai.djl.modality.cv.DetectedObjects>
                MxModelZoo.SSD.loadModel(new ProgressBar());**

Any idea to fix.Currently i uses both 0.21api &0.60 api&of course the mxmodels. 
It may have been some internal class conflict.
As I am new to the api,I think experienced one may have ideas of related class to help me navigate.
Which ZooModel<> is causing issue. 
I probably will try remove the newer api and recompile,as the tutorial uses older api.

**Comment by LJWxyz** [comment]
welp decided to screw the tutorial and follow the most current api that have close coupleling with the library.Plus it doesn't seem to have a decent support for bufferedimage too.. so...The api for ai.djl.modality.cv.Image better not change.If changed,all newer code will once again get depreciated*.

**Comment by LJWxyz** [comment]
Side problem solved,total version needed =33.Not quite bad huh?compared to manually us training AI....Well anyway The library architecture is quite good.From my experience the internal core api is decently build.It's currently not too bloated or too huge to find relevant stuff.The nested packages names make sense.The class naming is fine,the method naming is quite verbal and concise.
Had known this project 4 months ago. I am quite happy and impressed.

**Comment by frankfliu** [comment]
@LJWxyz thanks for pointing out the issue.

We changed from BufferedImage to out own Image because:
- depends on java.awt package is not a good idea, not all java system support awt (e.g Android, and some headless java distribution)
- User might use different image processing library other than imageIO (openCV, apache-commons-imaging, etc)

We missing some documentation that still referring to BufferedImage, we will do another scan and fix them.

**Comment by frankfliu** [comment]
> Side problem solved,total version needed =33.Not quite bad huh?compared to manually us training AI....Well anyway The library architecture is quite good.From my experience the internal core api is decently build.It's currently not too bloated or too huge to find relevant stuff.The nested packages names make sense.The class naming is fine,the method naming is quite verbal and concise.
> Had known this project 4 months ago. I am quite happy and impressed.

We try our best to minimize the dependencies, DJL actually only has 4 external dependencies:
- sl4fj-api
- Gson
- JNA
- commons-compress

Although DJL itself has many packages, but in a real production environment, the minimal dependencies can be:
- ai.djl:api
- one of the engine package (e.g. ai.djl.pytorch:pytorch-engine)
- one of the native engine library (e.g. ai.djl.pytorch:pytorch-native-auto)

**Comment by LJWxyz** [comment]
Awesome,thanks for the detailed guide and analysis.
I think the shift to custom Image is ok with those reasons.
For the dependencies,yes I think it's actually acceptable now since mxnet also probably relies on them,etc..
I can see those dependencies flying around,but at least the core is actually kinda independent so I am relieved.

**Comment by frankfliu** [comment]
@LJWxyz I added a document about DJL's dependencies: https://github.com/awslabs/djl/blob/master/docs/development/dependency_management.md
