### ISSUE TITLE
Block creation null pointer exception

### ISSUE THREAD

**Issue by aksrajvanshi** [awslabs/djl#123]
## Description
Null pointer exception when the block is created and built but isn't initialized with any sort of initializer. (Normal/Xavier)

### Expected Behavior
I expect that the block would print the details of how the shape would change if passed with an NDArray.

### Error Message
Null pointer exception. Attaching the error snips.

Expected output

![Screen Shot 2020-07-07 at 6 57 26 PM](https://user-images.githubusercontent.com/16722550/86853341-4ee3f600-c084-11ea-89fe-443cafe7df7a.png)

Actual output without initializing.

![Screen Shot 2020-07-07 at 6 58 10 PM](https://user-images.githubusercontent.com/16722550/86853350-53101380-c084-11ea-9a8a-1f6c4570aaaf.png)

**Comment by LJWxyz** [comment]
Extra note:problem probably started at Arrays.asList
>https://stackoverflow.com/questions/27268307/null-array-to-empty-list

**Comment by stu1130** [comment]
@aksrajvanshi Could you give me the script to reproduce the issue?
The initialization is required to create the parameters in each block.
We are planning to improve the user experience by having a default initializer

**Comment by aksrajvanshi** [comment]
@stu1130 in https://github.com/awslabs/djl/blob/master/jupyter/d2l-java/chapter_convolutional-neural-networks/lenet.ipynb, the cell where we create the SequentialBlock, try removing the code starting from `float lr = 0.9f` until the end of the cell. And then run the cell. You will face the same errors as mentioned above.

**Comment by stu1130** [comment]
Fixed by https://github.com/awslabs/djl/commit/23364c407f560ceb46b37d2be46ca47636fd3702
