### ISSUE TITLE
SpringBoot java.lang.UnsatisfiedLinkError: C:\Users\*\.pytorch\cache\1.4.0-20200327cpu-win-x86_64\fbgemm.dll: Can't find dependent libraries

### ISSUE THREAD

**Issue by hackedbyxx** [awslabs/djl#125]
## Description
I use pytorch as engine,the version is 0.5,firtsly 1.4.0/fbgemm.dll is not exist,i download 1.5.0 manually,and install Visual C++ Redistributable Packages still not working

### Error Message
java.lang.UnsatisfiedLinkError: C:\Users\sn78083\.pytorch\cache\1.4.0-20200327cpu-win-x86_64\fbgemm.dll: Can't find dependent libraries

### POM:

        <dependency>
            <groupId>ai.djl.spring</groupId>
            <artifactId>djl-spring-boot-starter-pytorch-auto</artifactId>
            <version>0.5</version>
        </dependency>

        <dependency>
            <groupId>ai.djl.spring</groupId>
            <artifactId>djl-spring-boot-starter-autoconfigure</artifactId>
            <version>0.5</version>
        </dependency>

**Comment by lanking520** [comment]
Could you please check if fbgemm is there. If not, could you please try to install a visual studio 2017 to get the most up-to-date vc compiler? I will take some time to investigate the issue you have.

**Comment by frankfliu** [comment]
@hackedbyxx 
Your dependency looks fine, most likely still related to VC++ redistributable package version.
Would you please try the sample application: https://github.com/awslabs/djl-spring-boot-starter/tree/master/djl-spring-boot-console-sample

I just tried on a fresh Windows (with VC++ 2019 pack), and changed dependency to pytorch, it works fine for me.

**Comment by hackedbyxx** [comment]
> Could you please check if fbgemm is there. If fbgemm is there, could you please try to install a VC++ 2019 redistributable package (https://github.com/awslabs/djl/blob/master/docs/development/troubleshooting.md#3-build-fails-on-windows-caused-by-unsatisfiedlinkerror) to get the most up-to-date vc compiler? I will take some time to investigate the issue you have. You can also use [Depedency Walker](http://dependencywalker.com/) to figure out what are the missing piece in the dependencies. You can bring a screen shot after doing so and we can help you with this information provided

I've tried to install VC++2019 and reboot,it does not work,i think the problem is i cant't download dll of pytorch, it seems the remote websites doesnt have  1.4.0-20200327cpu-win-x86_64\fbgemm.dll matched.I just find and download 1.5

**Comment by hackedbyxx** [comment]
> @hackedbyxx
> Your dependency looks fine, most likely still related to VC++ redistributable package version.
> Would you please try the sample application: https://github.com/awslabs/djl-spring-boot-starter/tree/master/djl-spring-boot-console-sample
> 
> I just tried on a fresh Windows (with VC++ 2019 pack), and changed dependency to pytorch, it works fine for me.
i've install VC++ 2019 pack,I've tried mxnet,it works ok,but pytorch not work well

**Comment by hackedbyxx** [comment]
> @hackedbyxx
> Your dependency looks fine, most likely still related to VC++ redistributable package version.
> Would you please try the sample application: https://github.com/awslabs/djl-spring-boot-starter/tree/master/djl-spring-boot-console-sample
> 
> I just tried on a fresh Windows (with VC++ 2019 pack), and changed dependency to pytorch, it works fine for me.

i've install VC++ 2019 pack,I've tried mxnet,it works ok,but pytorch not work well

**Comment by frankfliu** [comment]
@hackedbyxx 
Would you please try to clean your pytorch cache directory: C:\Users\*\.pytorch\cache\1.4.0-20200327cpu-win-x86_64\
and try to run our examples project from DJL repo:

```
cd djl
gradlew :examples:run -Dai.djl.default_engine=PyTorch -Dai.djl.logging.level=debug
```

It should print out more debug informations about loading pytorch engine

If that doesn't work
```
cd djl
gradle debugEnv -Dai.djl.default_engine=PyTorch
```
above command can print more information about your system configuration.

**Comment by stu1130** [comment]
@hackedbyxx Would you have the chance to try out the above comment?

**Comment by tspannhw** [comment]
I have seen this issue with NiFi, I get an issue if two apps/processors/microservices use the same library (say both use Pytorch)

**Comment by lanking520** [comment]
@hackedbyxx Any updates, do you still have this issue? @tspannhw as well

**Comment by stu1130** [comment]
close the stale issue. @hackedbyxx feel free to reopen it
