### ISSUE TITLE
What is the right terms for linking blocks

### ISSUE THREAD

**Issue by LJWxyz** [awslabs/djl#130]
I am unsure of the naming structure some neural network structure used in DJL,and how to fully utilize some interfaces provided.
From my experience,
1)Block seems to most similar to a neuron or simply a cell.However it's a interface which is very useful.It allows us human to label(Neuron system) and generalize or even abstract.The implemented classes is very good.Except one thing it's kinda distributed across the core?@@ .Any guidelines to help us navigate by some sort of characteristics?
2)The links between blocks cannot be found by me,the Connections and weights between the blocks doesn't seem to exist.I suspect it's >Linear.builder() ,but I am kinda confused,as I thought it would take a input layer and a output layer as arguments and link them with a specified function.I also notice that it's a block instead of some sort of connection[] ?Kinda confused.
3)The parameter and activations seems interchangeable which make sense to me.But the usage of SomeBigBlock.add(activationfunc) kinda doesn't make sense to me and I am kinda confused.

PS:I am very new to ML or simply ANN,please correct me if I am fundamentally wrong or simply link me to some article to do some reading.
I am following >https://github.com/awslabs/djl/blob/master/jupyter/tutorial/01_create_your_first_network.ipynb
I am Learning ML by my own,sorry if I seems like a dumb developer that simply loves create these question issues.
Many of these questions may actually be stupid ideas or limit that I suggest because I am a newbie and cannot scale my brain enough right now.
If that's the case please stand firmly and tell me I am wrong and simply tell me to go study some crucial concepts that you think will be useful.^^

**Comment by frankfliu** [comment]
@LJWxyz 
The analogy we are trying to use is Lego Block. The Block can small can be big or combined.
You can blocks together to form a neuron network.

You can use container Blocks (SequentialBlack, ParallelBlock) to connect each blocks. And you can use nested structure to build your block topology.

The weight and bias is internal property of a Block.

We are working a book for Java user that you can learn deep learning:
https://d2l-java.s3.amazonaws.com/index.html

The book is still working in progress, you can find jupyter notebooks in our repo: https://github.com/awslabs/djl/tree/master/jupyter/d2l-java

**Comment by stu1130** [comment]
The connection[] you are talking is actually the weight and bias. The formula of the linear block is as simple as the following formula
```
# w.T is weight.Transpose
y = w.T * x + b
```
Assume the shape of x is (32, 100) and you expect the shape of y is (32, 10). The shape of the w, b would be (10, 100) and (10) respectively. By using our Linear Block, we construct and manage weight and bias for you. We need the expected output shape and we can derive the inputShape from input data. That is the reason why you'll pass in the number of units which means the outputShape here.

**Comment by LJWxyz** [comment]
Thanks for all the comments it helped me cleared some of the clouds and I can understand how the framework works now.^^

**Comment by LJWxyz** [comment]
I think I understood how the analog and cleared my misconceptions.So I will close this issue.^^
