### ISSUE TITLE
Do you support GPU inference in pytorch-android ?

### ISSUE THREAD

**Issue by SofoklisKat** [awslabs/djl#131]

**Comment by lanking520** [comment]
We do support PyTorch Android: https://github.com/aws-samples/djl-demo/tree/master/android. But for Android GPU, could you explain more which kind of GPU accelerator you are looking for?

**Comment by SofoklisKat** [comment]
@lanking520 Thank you for your quick response.
For example tflite provides multiple options regarding the mobile implementation (CPU, GPU, NNAPI). For more info https://www.tensorflow.org/lite/performance/gpu_advanced .
PyTorch in it's current version does not provide such options in the mobile if I am correct. I think it only has CPU implementation. My question is if DJL have extend this functionality to include also inference in the mobile GPU.

**Comment by frankfliu** [comment]
@SofoklisKat 
1. We don't support Android on GPU out of box. The limitation is only the libtorch.so file. You should be able to build your libtorch.so file use Android NDK for your target system (e.g. Jetson tx2). We'd like to see community can contribute this type of effort.
2. DJL can also add TF-lite support. It's on our roadmap.
