### ISSUE TITLE
How to add an arm64 support for pytorch

### ISSUE THREAD

**Issue by ares89** [awslabs/djl#141]
## Description
Hi everyone. I am trying to use this library to inference on centos with arm cpu, how to add a support for this? thank you.
I had read the pytorch-native README.

### Will this change the current api? How?
this will not change any api.
### Who will benefit from this enhancement?
All people work with arm64 will benefit.

## References
1.  [pytorch arm64 daily build](https://github.com/pytorch/pytorch/issues/39558)

thank you.

**Comment by frankfliu** [comment]
@ares89 
DJL currently doesn't support pytorch arm64 build yet. You need build DJL pytorch JNI for arm64 from source. We will provide document about how to support build from source.

**Comment by stu1130** [comment]
@ares89 in addition to JNI, you might also need to build PyTorch for arm64 from source

**Comment by ares89** [comment]
@stu1130 @frankfliu 
in this url[http://status.openlabtesting.org/build/1d1885f4318248758d862339573f0cfe] , an arm64 version is built and the whl file can be downloaded.
Is this whl file useful to gen arm64 JNI? or need I to build the libtorch?

**Comment by stu1130** [comment]
@ares89 I will try out the artifact and get back to you

**Comment by stu1130** [comment]
@ares89 I reused the wheel you provided and built the JNI. It works perfectly (passing the SSD example & all the integration test).

**Comment by lanking520** [comment]
@ares89 Can you explain more on your use cases? We might consider adding a long-term support on ARM64 if there are some amount of users looking for support

**Comment by ares89** [comment]
@stu1130 thanks a lot, I am trying to follow the steps to get a arm64 version.

**Comment by ares89** [comment]
@lanking520 
AFAIK, Amazon Web Services and Huawei both launched computing instances that draw on server chips that use Arm’s processing architecture. AWS rank first in cloud computing domain, and Huawei don't have the x86 licence so they will spare no efforts to develop arm server chips.

**Comment by EdvinasKilbauskas** [comment]
I would appreciate the effort to add arm64 support. Currently using Mac M1 silicon and would like to install OpenAI's Gym library, but it gets stuck while building from source.

**Comment by stu1130** [comment]
@EdvinasKilbauskas You can follow the instruction here https://github.com/pytorch/pytorch/blob/master/docs/libtorch.rst to build libtorch from source on Mac M1 then build JNI again from source by using ./gradlew compileJNI. Let me know if you have any issue executing commands

**Comment by paipeng** [comment]
Hello DJL,

any roadmap plan for DJL on AArch64 official? 

Regards,

Pai

**Comment by frankfliu** [comment]
We already added aarch64 support for PyTorch. We also support macOS M1 machine. See: https://docs.djl.ai/engines/pytorch/pytorch-engine/index.html#for-aarch64-build

**Comment by paipeng** [comment]
thanks for reply. I just tried it and it works.
