### ISSUE TITLE
Native library mxnet 

### ISSUE THREAD

**Issue by FatosTorba** [awslabs/djl#142]
## Description
Loading mxnet library on linux is not working but it works on windows. 
### Expected Behavior
(what's the expected behavior?)
Should not fail to load native mxnet library on linux.
### Error Message
15:01:31.896 [main] INFO ai.djl.mxnet.jna.LibUtils - Downloading libgfortran.so.3 ...
15:01:32.564 [main] INFO ai.djl.mxnet.jna.LibUtils - Downloading libgomp.so.1 ...
15:01:32.724 [main] INFO ai.djl.mxnet.jna.LibUtils - Downloading libmkldnn.so.1 ...
15:01:34.125 [main] INFO ai.djl.mxnet.jna.LibUtils - Downloading libquadmath.so.0 ...
15:01:34.302 [main] INFO ai.djl.mxnet.jna.LibUtils - Downloading libmxnet.so ...
15:04:25.566 [main] DEBUG ai.djl.mxnet.jna.LibUtils - Loading mxnet library from: /home/fatos/.mxnet/cache/1.6.0-20200221cu101mkl-linux-x86_64/libmxnet.so

 A fatal error has been detected by the Java Runtime Environment:

 SIGILL (0x4) at pc=0x00007f767ae66674, pid=42826, tid=0x00007f77560f2700

 JRE version: OpenJDK Runtime Environment (8.0_252-b09) (build 1.8.0_252-8u252-b09-1ubuntu1-b09)
Java VM: OpenJDK 64-Bit Server VM (25.252-b09 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libmxnet.so+0xd97674]

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

## How to Reproduce?
try to load a model trained on mxnet using djl on linux 
or just run an example provided by djl that uses mxnet engine 

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by stu1130** [comment]
@FatosTorba What version of DJL do you use? If it is 0.6, it should depend on mxnet 1.7. You can clean up the cache (`rm -rf ~/.mxnet`)and rerun the gradle build againi

**Comment by Jzow** [comment]
you can just use mxnet-native-auto which will detect your environment and pick the right one for you

**Comment by FatosTorba** [comment]
I have tried your recommandation. It's still not working. Even when I try the examples of djl , it is not working. It works perfectly on windows. I'm using ubutnu  20.04 on dual boot with windows 10

**Comment by thhart** [comment]
The Mxnet libraries are built with special instruction sets for modern CPU which might fail on older ones. The solution might be to build Mxnet from source for specific CPUs however this is not easy and might be even more complicated since the binary libs are deeply nested into the dependencies.

**Comment by stu1130** [comment]
@FatosTorba you can maybe try out our latest 0.9.0. feel free to reopen the issue if the error still exists
