### ISSUE TITLE
Maven Compile Project Error

### ISSUE THREAD

**Issue by Jzow** [awslabs/djl#143]
## Description
Jdk ：1.8
Windows 10 X64 CPU 
Apache Maven 3.5
DLJ Version ：0.6.0
`<properties>
		<java.version>8</java.version>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<djl.version>0.6.0</djl.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.vmware</groupId>
			<artifactId>vijava</artifactId>
			<version>5.1</version>
		</dependency>
		<dependency>
			<groupId>commons-cli</groupId>
			<artifactId>commons-cli</artifactId>
			<version>1.4</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-slf4j-impl</artifactId>
			<version>2.12.1</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.5</version>
		</dependency>

		<dependency>
			<groupId>ai.djl</groupId>
			<artifactId>api</artifactId>
			<version>${djl.version}</version>
		</dependency>
		<dependency>
			<groupId>ai.djl</groupId>
			<artifactId>basicdataset</artifactId>
			<version>${djl.version}</version>
		</dependency>
		<dependency>
			<groupId>ai.djl</groupId>
			<artifactId>model-zoo</artifactId>
			<version>${djl.version}</version>
		</dependency>
		<dependency>
			<groupId>ai.djl.mxnet</groupId>
			<artifactId>mxnet-model-zoo</artifactId>
			<version>${djl.version}</version>
		</dependency>
		<dependency>
			<groupId>ai.djl.mxnet</groupId>
			<artifactId>mxnet-engine</artifactId>
			<version>${djl.version}</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>`
### Expected Behavior
Compiled Successfully

### Error Message
[WARN ] - Failed to load MXNet native library
java.lang.UnsatisfiedLinkError: Unable to load library 'mxnet':
Native library (win32-x86-64/mxnet.dll) not found in resource path (D:\demo\target\classes;C:\Users\Administrator\.m2\repository\com\vmware\vijava\5.1\vijava-5.1.jar;C:\Users\Administrator\.m2\repository\dom4j\dom4j\1.6.1\dom4j-1.6.1.jar;C:\Users\Administrator\.m2\repository\xml-apis\xml-apis\1.0.b2\xml-apis-1.0.b2.jar;C:\Users\Administrator\.m2\repository\commons-cli\commons-cli\1.4\commons-cli-1.4.jar;C:\Users\Administrator\.m2\repository\org\apache\logging\log4j\log4j-slf4j-impl\2.12.1\log4j-slf4j-impl-2.12.1.jar;C:\Users\Administrator\.m2\repository\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;C:\Users\Administrator\.m2\repository\org\apache\logging\log4j\log4j-api\2.12.1\log4j-api-2.12.1.jar;C:\Users\Administrator\.m2\repository\org\apache\logging\log4j\log4j-core\2.12.1\log4j-core-2.12.1.jar;C:\Users\Administrator\.m2\repository\com\google\code\gson\gson\2.8.5\gson-2.8.5.jar;C:\Users\Administrator\.m2\repository\ai\djl\api\0.6.0\api-0.6.0.jar;C:\Users\Administrator\.m2\repository\net\java\dev\jna\jna\5.3.0\jna-5.3.0.jar;C:\Users\Administrator\.m2\repository\org\apache\commons\commons-compress\1.20\commons-compress-1.20.jar;C:\Users\Administrator\.m2\repository\ai\djl\basicdataset\0.6.0\basicdataset-0.6.0.jar;C:\Users\Administrator\.m2\repository\ai\djl\model-zoo\0.6.0\model-zoo-0.6.0.jar;C:\Users\Administrator\.m2\repository\ai\djl\mxnet\mxnet-model-zoo\0.6.0\mxnet-model-zoo-0.6.0.jar;C:\Users\Administrator\.m2\repository\ai\djl\mxnet\mxnet-engine\0.6.0\mxnet-engine-0.6.0.jar)
Suppressed: java.lang.UnsatisfiedLinkError: The specified module was not found

**Comment by Jzow** [comment]
hope to provide a maven similar project，I don't use it very often Gradle

**Comment by zachgk** [comment]
It looks like you might be missing the dependency:
```
        <dependency>
            <!--
                See https://github.com/awslabs/djl/blob/master/mxnet/mxnet-engine/README.md for more MXNet library selection options
            -->
            <groupId>ai.djl.mxnet</groupId>
            <artifactId>mxnet-native-auto</artifactId>
            <version>1.7.0-a</version>
            <scope>runtime</scope>
        </dependency>
```

You can find it in our [example/pom.xml](https://github.com/awslabs/djl/blob/v0.6.0/examples/pom.xml)

**Comment by Jzow** [comment]
> It looks like you might be missing the dependency:
> 
> ```
> 
>         <dependency>
> 
>             
> 
>             <groupId>ai.djl.mxnet</groupId>
> 
>             <artifactId>mxnet-native-auto</artifactId>
> 
>             <version>1.7.0-a</version>
> 
>             <scope>runtime</scope>
> 
>         </dependency>
> 
> ```
> 
> 
> 
> You can find it in our [example/pom.xml](https://github.com/awslabs/djl/blob/v0.6.0/examples/pom.xml)

Thanks for you,I m try

**Comment by Jzow** [comment]
> It looks like you might be missing the dependency:
> 
> ```
> 
>         <dependency>
> 
>             
> 
>             <groupId>ai.djl.mxnet</groupId>
> 
>             <artifactId>mxnet-native-auto</artifactId>
> 
>             <version>1.7.0-a</version>
> 
>             <scope>runtime</scope>
> 
>         </dependency>
> 
> ```
> 
> 
> 
> You can find it in our [example/pom.xml](https://github.com/awslabs/djl/blob/v0.6.0/examples/pom.xml)


<dependency>
    <groupId>ai.djl.mxnet</groupId>
    <artifactId>mxnet-native-mkl</artifactId>
    <classifier>win-x86_64</classifier>
    <scope>runtime</scope>
    <version>1.7.0-b</version>
</dependency>
This dependency is win64 , Can I use it?

**Comment by stu1130** [comment]
@Jzow you can just `mxnet-native-auto` which will detect your environment and pick the right one for you

**Comment by Jzow** [comment]
<dependency>
    <groupId>ai.djl.mxnet</groupId>
    <artifactId>mxnet-native-mkl</artifactId>
    <classifier>win-x86_64</classifier>
    <scope>runtime</scope>
    <version>1.7.0-b</version> </dependency>



| |
jameszow
|
|
邮箱：jameszow@126.com
|

Signature is customized by Netease Mail Master

On 07/28/2020 07:35, Jake Lee wrote:

@Jzow you can just mxnet-native-auto which will detect your environment and pick the right one for you
