### ISSUE TITLE
how to load a  model which is packaged in jar flies ？

### ISSUE THREAD

**Issue by Mr-j-yangyu** [awslabs/djl#147]
## Question
 the model file is packaged with java project together，i want load local model in java project

**Comment by frankfliu** [comment]
In current version, DJL can only load model from file. If your model packaged inside your jar file. You need to extract them and save it into temp folder, and use Criteria to load the model for temp directory.

It's possible to add a JarRepository to automate the caching, see: http://docs.djl.ai/docs/load_model.html#implement-your-own-repository

There are a couple of reason that we don't support load model directly from InputStream:
1. Most of the engine's C API only support load model from file path. To support load model from memory requires use lower level C API.
2. A Model usually contains multiple files, and are different from engine to engine. It's very hard to create a high level abstraction works for all engines.

**Comment by Mr-j-yangyu** [comment]
thanks，I'll try

**Comment by stu1130** [comment]
@Mr-j-yangyu I think you get the answer, so I am going to close the issue. Feel free to reopen it if you have more questions
