### ISSUE TITLE
How to load MXNet model persisted in S3? 

### ISSUE THREAD

**Issue by airwindow** [awslabs/djl#148]
## Question
We are using SageMaker to train our MXNet-based model and the artifact was persisted as "***.tar.gz".
The compressed folder contains "model-0000.params" and "model-symbol.json".

We have followed the tutorial at
https://docs.djl.ai/3rdparty/aws-ai/index.html.

But keeps on getting exception "No matching model with specified Input/Output" type found.
Not sure what's going wrong at here, I have few questions to ask related the the usage.
1. When we persisted the MXNet Model, do we need to add some kind of "meta.json" in the folder for DJL to locate it?
2. For "Criteria.builder().setTypes(Image.class, Classifications.class)"... Is setTypes method must for DJL to locate it? 
3. Will DJL directly load the model from S3 or it will actually persist onto local file system first intermediately  then load it?

BTW...We have also tried to decompress the tar folder, but still does not work.
Thanks! :)

**Comment by stu1130** [comment]
@airwindow Thanks for reporting the issue. Could you provide the script that we can reproduce

1. no you don't need the meta.json.
2. yes the argument starts with set in its name is required. On the other hand, the name optXXX is optional
3. (@frankfliu correct me if I am wrong) It actually downloads the model to the local file system

**Comment by frankfliu** [comment]
Added more detail in: https://github.com/awslabs/djl/blob/master/docs/load_model.md#criteria-class
and made it explicit that setType() is required.
