### ISSUE TITLE
Potential ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by waooog** [awslabs/djl#15]
## Description
There is a potential `ArrayIndexOutOfBoundsException` in the method `latestMetric` in class `ai.djl.metric.Metrics`. 
In the following code snippet, if `list` is empty (not `null`), the `return list.get(list.size() - 1);` statement will has an `ArrayIndexOutOfBoundsException`.

`    public Metric latestMetric(String name) {`
      `  List<Metric> list = metrics.get(name);`
    `   if (list == null) {`
       `     throw new IllegalArgumentException("Could not find metric: " + name);`
       ` }`
  `      return list.get(list.size() - 1);`
    }
`

## What have you tried to solve it?

change ` if (list == null) ` to `if (list == null || list.isEmpty())`

**Comment by frankfliu** [comment]
@waooog 
Thanks for reporting this issue.

In current code, NPE should never happen since we never put empty list into metrics.
But I agree we should guard empty list case for custom metrics. And your suggestion is a good improvement.

Would you mind submit a PR to address this issue?

**Comment by frankfliu** [comment]
Fix has be merged: https://github.com/awslabs/djl/commit/f264cf82c8ef1465dd85ebc4eb873c753ee069a5
