### ISSUE TITLE
Models with more than one input

### ISSUE THREAD

**Issue by carlosuc3m** [awslabs/djl#157]
## Question
Hello everyone, I am starting to use DJL. After looking at all the examples provided I was wondering if it would be possible to use DJL to make inference with computer vision models that require more than one input (for example cyclegans or Mask R-CNN). 
Thank you for your time,
Carlos

**Comment by frankfliu** [comment]
Yes, DJL support multiple input and multiple output.
You can refer to this document: http://docs.djl.ai/jupyter/mxnet/load_your_own_mxnet_bert.html#construct-translator
The `Translator` API allows you convert your java object into `NDList`. The `NDList` class can hold multiple `NDArray`s.

**Comment by carlosuc3m** [comment]
Great, thanks.

**Comment by pmingkr** [comment]
> Yes, DJL support multiple input and multiple output. You can refer to this document: http://docs.djl.ai/jupyter/mxnet/load_your_own_mxnet_bert.html#construct-translator The `Translator` API allows you convert your java object into `NDList`. The `NDList` class can hold multiple `NDArray`s.

link is broken :(
could you provide the other one?

**Comment by frankfliu** [comment]
I updated the link: https://docs.djl.ai/docs/demos/jupyter/load_mxnet_model.html#step-3-create-a-translator
