### ISSUE TITLE
CSVDataset sample misses availableSize() and prepare(Progress progress)

### ISSUE THREAD

**Issue by deki** [awslabs/djl#161]
how_to_use_dataset.md contains the sample code CSVDataset. Unfortunately the implementations for availableSize() and prepare(Progress progress) are missing. How would a proper implementation look like?

**Comment by frankfliu** [comment]
@deki good catch. 
You can find example in this demo: https://github.com/aws-samples/djl-demo/blob/master/malicious-url-detector/src/main/java/com/example/CSVDataset.java#L86
and

https://github.com/aws-samples/djl-demo/blob/master/malicious-url-detector/src/main/java/com/example/CSVDataset.java#L124

Would you mind raise a PR to address this issue?
