### ISSUE TITLE
Is it possible to use a workaround to find the number of inputs and outputs of a Pytorch model?

### ISSUE THREAD

**Issue by carlosuc3m** [awslabs/djl#163]
## Question
Hello, I was wondering if it was possible right now to find the inputs and outputs of a Pytorch model. The method exists so I guess the functionality will be possible in the near future, but it is not implemented at the moment. So I was wondering if there existed a workaround to find this information.
Thank you,
Carlos

**Comment by frankfliu** [comment]
@carlosuc3m 
Currently the PyTorch model itself doesn't have this information available. We can only extract input/output information from TensorFlow SavedModel bundle. If you train the model with DJL, we save input/output information with model.

The the time being, the only option is store the input/output information in metadata. We are working on a feature that allow you to specify the model metadata.

**Comment by carlosuc3m** [comment]
Ok, great thanks!
