### ISSUE TITLE
LSTM example with training and inference

### ISSUE THREAD

**Issue by sujitbiswas** [awslabs/djl#18]
## Description
can you provide an LSTM example code with training and inference, preferably with time series data

### Will this change the current api? How?
no

### Who will benefit from this feature?
any one who wants to build an LSTM model using the api

## References
- list reference and related literature
- list known implementations

**Comment by zachgk** [comment]
We created an example on the LSTM branch at https://github.com/awslabs/djl/blob/lstm/examples/src/main/java/ai/djl/examples/training/TrainMnistWithLSTM.java. It currently depends on a different Engine version, so we will wait to close this issue until the Engine issue is resolved and the branch is merged

**Comment by frankfliu** [comment]
LSTM example has been merged into master branch now: 
https://github.com/awslabs/djl/blob/master/examples/src/main/java/ai/djl/examples/training/TrainMnistWithLSTM.java
