### ISSUE TITLE
Zero size of a splitted datasets

### ISSUE THREAD

**Issue by kkoripl** [awslabs/djl#201]
## Description
When using randomSplit function with set ratios and receiving sub-RandomAccessDatasets invoking size() function on each of them returns 0, even if data inside is available. 

### Expected Behavior
Function should return actual size of a dataset when limit property of a class RandomAccessDataset set for Long.max_value, as it is in this situation.

### Steps to reproduce
DatasetPath and batchSize come as a configuration for starting script.
Repository made out of custom MNIST image dataset setup as described in ImageFolder docs.
```
    private static final int MNIST_IMG_HEIGHT = 28;
    private static final int MNIST_IMG_WIDTH = 28;

    ImageFolder dataset = ImageFolder.builder()
                .optLimit(Long.MAX_VALUE)
                .setRepository(Repository.newInstance("mnistCustom", Paths.get(datasetPath)))
                .optPipeline(preprocessImages(MNIST_IMG_WIDTH, MNIST_IMG_HEIGHT))
                .setSampling(batchSize, true)
                .build();

        dataset.prepare();
        System.out.println(dataset.size());
        RandomAccessDataset[] sets = dataset.randomSplit(75, 25);
        for (RandomAccessDataset set : sets) {
            System.out.println(set.size());
        }
```

## What have you tried to solve it?

Debugging into RandomAccessDataset class showed that for some reason when invoking .size() function on subdatasets the limit property is set to 0, even though earlier was set to maximum. Debugging into split function showed that limit is MAX during that time. Don't have any idea why is that and how it's set. Setting up limit property by invoking setOptLimit don't work either.

## Environment Info
Maven:
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>java-machine-learning</artifactId>
    <version>1.0-SNAPSHOT</version>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <properties>
        <djl.version>0.6.0</djl.version>
        <log4j.version>2.12.1</log4j.version>
        <commons-cli.version>1.4</commons-cli.version>
        <logback.version>1.1.7</logback.version>
        <lombok.version>1.18.0</lombok.version>
        <commons-csv.version>1.8</commons-csv.version>
    </properties>

    <dependencies>
        
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>api</artifactId>
            <version>${djl.version}</version>
        </dependency>

        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>repository</artifactId>
            <version>0.4.1</version>
        </dependency>

        
        <dependency>
            <groupId>ai.djl.mxnet</groupId>
            <artifactId>mxnet-engine</artifactId>
            <version>${djl.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            
            <groupId>ai.djl.mxnet</groupId>
            <artifactId>mxnet-native-auto</artifactId>
            <version>1.7.0-b</version>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>ai.djl.mxnet</groupId>
            <artifactId>mxnet-model-zoo</artifactId>
            <version>${djl.version}</version>
        </dependency>

        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>model-zoo</artifactId>
            <version>${djl.version}</version>
        </dependency>

        
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>basicdataset</artifactId>
            <version>${djl.version}</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-cli</groupId>
            <artifactId>commons-cli</artifactId>
            <version>${commons-cli.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-csv</artifactId>
            <version>${commons-csv.version}</version>
        </dependency>
</project>`

**Comment by frankfliu** [comment]
@kkoripl I'm able to reproduce this issue, this is a bug in SubDataset constructor.

**Comment by frankfliu** [comment]
Feel free to re-open the issue if you still have issue
