### ISSUE TITLE
Steps for creating a custom dataset

### ISSUE THREAD

**Issue by ffazil** [awslabs/djl#21]
Am trying out `djl` and really excited to finally try out object detection in Java. What are the steps to label images for object detection? 

I see that images needs to be separated in to train and test directories and also see `index.file` containing the coordinates of annotated objects. What tool can be used to annotate images to generate `index.file`?

**Comment by frankfliu** [comment]
@ffazil 
You can try AWS SageMaker ground truth: https://aws.amazon.com/sagemaker/groundtruth/

**Comment by lanking520** [comment]
Hi @ffazil, in order to train a basic classification or object detection model, you need to label each images.

About custom dataset, you can try some tools to generate labels for you. As an example:
 [SageMaker Ground Truth](https://aws.amazon.com/sagemaker/groundtruth/?nc1=h_ls) or [Mechanical turk](https://www.mturk.com/).

**Comment by zachgk** [comment]
@ffazil Also, you are not required to follow the same formats as `PikachuDetection` dataset. You can just create your own dataset class extending `RandomAccessDataset` and then format your data in whatever way works best for you.

**Comment by stu1130** [comment]
> @ffazil Also, you are not required to follow the same formats as `PikachuDetection` dataset. You can just create your own dataset class extending `RandomAccessDataset` and then format your data in whatever way works best for you.

You can follow the instruction here if you want to extend `PikachuDetection` dataset
https://github.com/awslabs/djl/blob/master/docs/development/how_to_use_dataset.md#how-to-create-your-own-dataset

**Comment by ffazil** [comment]
Thank you all.

**Comment by thhart** [comment]
Hi contributors thanks for the suggestions added here. However I have some criticism and I have to say the documentation is very incomplete. Maybe it is worth to put some more effort in this whole topic.

1. SageMaker is a very high level labeling tool which does not answer how to integrate a dataset into DJL.
2. PikachuDetection is a good basic example which unfortunately only contains 1 label, further it is not clear how the Pikachu is woven into a record dataset. From the index structure I can see it is a relative bounding box structure. But still it is unclear how multiple labels can be converted to a NDArray record structure.
3. Finally your link to the own dataset creation only addresses a different AI problem and not image labeling for object detection not to speak of image segmentation.
