### ISSUE TITLE
 Build failed cause mxnet.dll is not a valid Win32 application

### ISSUE THREAD

**Issue by ntbdusty** [awslabs/djl#22]
Hello, guys. Could you help me?
When I tried to build app I've got an error
"Unable to load library 'C:\Users\Default\.mxnet\cache\1.6.0-b-SNAPSHOT-20200120mkl-win-x86_64\mxnet.dll':
2020-01-23T03:20:04.060+0300 [ERROR] [system.err] %1 is not a valid Win32 application."

Command for build is "./gradlew run -Dmain=ai.djl.examples.training.TrainMnist"

It's strange, because I have the environment showed below:

java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

Microsoft Windows [Version 10.0.17763.864]
OS Name	Microsoft Windows 10 Enterprise LTSC
Version	10.0.17763 Build 17763
System Type	x64-based PC

Gradle 6.0.1
Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Windows 10 10.0 amd64

**Comment by frankfliu** [comment]
@ntbdusty 
"Unable to load library 'C:\Users\Default.mxnet\cache\1.6.0-b-SNAPSHOT-20200120mkl-win-x86_64\mxnet.dll'
This message looks suspicious. Somehow java think you are running as user "Default", that's strange.

Would you please run following command and collect the output:
```
cd integration
gradlew debugEnv

**Comment by ntbdusty** [comment]
Ouch, I have to explain, do not pay attention to it. I just replaced manually real user name.
It should looks like "" 'C:\Users\UserName\.mxnet\cache\1.6.0-b-SNAPSHOT-20200120mkl-win-x86_64\mxnet.dll'
Also, see logs in attach:
[build.log](https://github.com/awslabs/djl/files/4101789/build.log)
[debugEnv.log](https://github.com/awslabs/djl/files/4101790/debugEnv.log)

**Comment by frankfliu** [comment]
@ntbdusty 
I guess this is caused by you running gradle in MingW64 shell. Please try to run gradle in command prompt.

**Comment by ntbdusty** [comment]
@frankfliu 
Unfortunately, the same result in command prompt. =(

**Comment by frankfliu** [comment]
@ntbdusty 
This is really strange, mxnet.dll is a 64-bit DLL, and your java and windows are both 64-bit. Somehow your system trying to load mxnet.dll in 32-bit mode and failed.

Can you try one more thing: delete C:\Users\UserName\.mxnet folder and try it again?

**Comment by ntbdusty** [comment]
@frankfliu 
Many thanks, reinstalling vs2015 solved the problem.
I should have read Troubleshooting more accurate.
