### ISSUE TITLE
How to import paddlepaddle model

### ISSUE THREAD

**Issue by yanchaoguo** [awslabs/djl#225]
请问支持百度paddle模型导入吗有没有操作使用的例子

**Comment by lanking520** [comment]
Currently PaddlePaddle doesn't have a Java API we can connect with. But there is a plan to support Paddle with Paddle team in Java in the coming weeks. If you are interested to participate on that,  please let me know.

**Comment by lanking520** [comment]
PaddlePaddle now is almost there. https://github.com/awslabs/djl/pull/430 .Please check this out and play around with the mask classification examples
