### ISSUE TITLE
BOM should contain definitions for artifacts with classifiers

### ISSUE THREAD

**Issue by deki** [awslabs/djl#226]
## Description
djl/bom should also contain dependency declarations for artifacts with classifiers (osx-x86_64, win-x86_64, linux-x86_64) like mxnet-native-mkl. Currently these definitions are missing (maybe due to https://github.com/gradle/gradle/issues/8561)

Example usecase: if you remove mxnet.native.version from https://github.com/awslabs/djl-spring-boot-starter/ you'll get  'dependencies.dependency.version' for ai.djl.mxnet:mxnet-native-mkl:jar:linux-x86_64 is missing as https://repo1.maven.org/maven2/ai/djl/bom/0.8.0/bom-0.8.0.pom has no entry for that.

### Will this change the current api? How?
No

### Who will benefit from this enhancement?
Users will no longer have to maintain versions on their own.

**Comment by frankfliu** [comment]
@deki BOM doesn't really need include classifier
Please take a look the following example: https://github.com/aws-samples/djl-demo/blob/master/canary/build.gradle#L52

**Comment by deki** [comment]
@frankfliu I know Gradle handles this differently but IMHO Maven somehow requires the declarations. Please let me know if you see an option to achieve it without adding them.

**Comment by deki** [comment]
Thanks Frank. One workaround mentioned in https://github.com/gradle/gradle/issues/8561 is to do post processing using pom.withxml.

**Comment by frankfliu** [comment]
@deki 
I created a PR to address this issue: https://github.com/awslabs/djl/pull/230

Please the BOM 0.9.0 snapshot version will be available by tomorrow. Please let me know if it works for you.

**Comment by deki** [comment]
Should the snapshot be available in https://oss.sonatype.org/content/repositories/snapshots/?

Also tried to build it locally but although there are multiple publishing goals, I never managed to have the 0.9.0-SNAPSHOT bom in my local maven repo.

**Comment by frankfliu** [comment]
Yes, you can see: https://github.com/awslabs/djl/blob/master/examples/pom.xml#L17-L22

I changed the examples pom.xml https://github.com/awslabs/djl/blob/master/examples/pom.xml#L76
to:

```
            <artifactId>mxnet-native-mkl</artifactId>
            <classifier>osx-x86_64</classifier>
```

And it works fine.

If you want to build bom locally, you need publish the package to .m2 folder:
```
./gradlew publishToMavenLocal
```

**Comment by deki** [comment]
Thanks, I missed to run it in them bom folder separately. It's working great!
