### ISSUE TITLE
Load libmxnet.so from jar

### ISSUE THREAD

**Issue by belenot** [awslabs/djl#23]
## Description
Can you please allow loading native library from jar? I didn't find a way to do it. But you could you NativeUtils for loading libraries from jar. And e.g. expose some system variable for specifying path in jar.

### Will this change the current api? How?
No

### Who will benefit from this feature?
End users

**Comment by zachgk** [comment]
We should support loading a native MXNet library that is stored in a jar. There is a required format for how to construct the jars. You can find examples of such jars [here](https://search.maven.org/search?q=g:ai.djl.mxnet%20AND%20a:mxnet-native-*). For reference, we use the [mxnet-native](https://github.com/awslabs/djl/tree/master/mxnet/native) module to construct the jars and the jars are picked up by [LibUtils](https://github.com/awslabs/djl/blob/master/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/jna/LibUtils.java#L74).

**Comment by belenot** [comment]
Please, can you point me where I am wrong?
I built jar with such content

```
...
        0  2020-01-28 06:03   lib/
        0  2020-01-28 06:03   lib/native/
  1206376  2019-02-28 22:40   lib/native/libgfortran.so.3
   261192  2019-02-28 22:40   lib/native/libquadmath.so.0
 79996184  2019-02-28 22:40   lib/native/libmxnet.so
        0  2020-01-28 06:03   cub/
     1600  2019-02-28 22:26   cub/LICENSE.TXT
   123725  2019-02-28 22:48   lib/native/libmxnet-scala.so
        0  2020-01-28 06:03   native/
        0  2020-01-28 06:03   native/lib/
       17  2019-11-18 16:25   native/lib/mxnet.properties
...
```
And here is my dependencies list 
```
24dependencies {
25  implementation 'com.google.code.gson:gson:2.8.5'
26  implementation 'org.slf4j:slf4j-api:1.7.25'
27  implementation 'ch.qos.logback:logback-classic:1.2.3'
28  implementation 'org.apache.mxnet:mxnet-full_2.11-linux-x86_64-cpu:1.4.0'
29  //implementation 'ai.djl.mxnet:mxnet-native-mkl:1.6.0-b'
30  implementation 'ai.djl.mxnet:mxnet-native-cu92mkl:1.6.0-b'
31  implementation files('/home/belenot/programming/src/deep-java-library/djl/api/build/libs/api-0.3.0-SNAPSHOT.jar')
32  implementation files('/home/belenot/programming/src/deep-java-library/djl/basicdataset/build/libs/basicdataset-0.3.0-SNAPSHOT.jar')
33  implementation files('/home/belenot/programming/src/deep-java-library/djl/model-zoo/build/libs/model-zoo-0.3.0-SNAPSHOT.jar')
34  implementation files('/home/belenot/programming/src/deep-java-library/djl/repository/build/libs/repository-0.3.0-SNAPSHOT.jar')
35  implementation files('/home/belenot/programming/src/deep-java-library/djl/mxnet/build/libs/mxnet-0.3.0-SNAPSHOT.jar')
36  implementation files('/home/belenot/programming/src/deep-java-library/djl/mxnet/mxnet-engine/build/libs/mxnet-engine-0.3.0-SNAPSHOT.jar')
37  implementation 'net.java.dev.jna:jna:5.3.0'
38}
```
Than I got that Exception:
```
Caused by: java.lang.IllegalStateException: You are using a placeholder jar. Make sure that the Maven Dependency Classifier includes your system type
	at ai.djl.mxnet.jna.LibUtils.findLibraryInClasspath(LibUtils.java:115)

```
If I remove 30 line in dependencies, than I got exception:
```
Exception in thread "main" java.util.ServiceConfigurationError: ai.djl.engine.EngineProvider: Provider ai.djl.mxnet.engine.MxEngineProvider could not be instantiated
...
libmxnet.so: cannot open shared object file: No such file or directory
libmxnet.so: cannot open shared object file: No such file or directory
Native library (linux-x86-64/libmxnet.so) not found in resource path (build/libs/hello-djl-0.0.1-SNAPSHOT-all.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)

```
Builts are done with gradle
I don't understand what I should to do

**Comment by frankfliu** [comment]
@belenot 
I'm really confused about what are you trying to achieve.

First of all you dependency was not specified correctly:
```
implementation 'ai.djl.mxnet:mxnet-native-cu92mkl:1.6.0-b'
```
It should be:
```
implementation 'ai.djl.mxnet:mxnet-native-cu92mkl:1.6.0-b:linux-x86_64'
```
See: https://github.com/awslabs/djl/tree/master/mxnet/mxnet-engine#linux

The error message indicate that you didn't specify classifier: <b>linux-x86_64</b>

DJL already provided pre-built mxnet native library: ai.djl.mxnet:mxnet-native-cu92mkl:1.6.0-b:linux-x86_64.
This dependency is sufficient for any MXNet functionality. Why you need another libmxnet.so file?

If you really need a custom build libmxnet.so file, you can use MXNET_LIBRARY_PATH environment variable to override the file provided in the jar.

- DJL has nothing to do with MXNet scala/java library, org.apache.mxnet:mxnet-full_2.11-linux-x86_64-cpu:1.4.0 will not work for DJL.

**Comment by belenot** [comment]
Thank you! I got build.gradle from examples, and copied script that computes needed library, but really it wasn't obvious for me :) 
I am average java junior developer, and never faced with jypiter and native libraries. I think, maybe it worth to explain differences between cu92 cu101 mkl, or point reader's attention on it in readme? 
Maybe I missed something while was reading that?

**Comment by frankfliu** [comment]
@belenot 
MXNet native library is platform specific, you must select the matching library for your machine.
In our example project gradle file, we trying to detect the platform and select one for you.

We use <b>classifier</b> for operating system selection, current available choice are (may expend to arm in future):
- osx-x86_64
- win-x86_64
- linux-x86_64

mxnet-native-mkl is optimized for Intel CPU, if you have GPU and has Nvidia cuda library installed, using mxnet-native-cuXXXmkl will significantly improve your performance. The GPU version of native library must match the cuda version you installed on your machine, cu101 means cuda 10.1, and cu92 means cuda 9.2.

We are trying to document it in: https://github.com/awslabs/djl/tree/master/mxnet/mxnet-engine#linux

Would you mind submit a PR to improve the document that can help other developer?

The gradle dependency in your file looks fine to me, does it work now?
You can see real dependency tree that used by example project by running:
```
cd examples
./gradlew dep
```

**Comment by belenot** [comment]
Yes, it works now. At free time I'll be playing with it, so if I find possibility for improvement, I'll make pr. 
In thit case, I think it was just mine misunderstanding. 
It seems that question is answered, so I close it, thank you again :)
