### ISSUE TITLE
Got invalid dimensions for input

### ISSUE THREAD

**Issue by eanemo** [awslabs/djl#238]
## Question
I am trying to use a model for segmentation that I have exported to ONNX format. I have tested the model in this format previously on Python code and works fine. However if I try to use the ONNX model using DJL Java code I obtain a invalid dimension error for the input of the model. I have checked that the image size is correct. So, I am using a custom transform class that I am using in the pipeline. The code I am using is the following:

`public class CustomTransform implements Transform {

    private Logger logger = Logger.getLogger(CustomTransform.class.getName());

    @Override
    public NDArray transform(NDArray array) {
        logger.info("Array shape " + array.getShape());
        NDArray tmp = array.toDense();
        String str = tmp.getShape().toString();
        logger.info("Array shape " + tmp.getShape());
        NDArray result = NDImageUtils.toTensor(tmp);
        logger.info("Result shape " + result.getShape());
        String str2 = result.getShape().toString();
        return result;
    }
}`

The error I am getting is:

ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: Got invalid dimensions for input: input_1 for the following indices
 index: 1 Got: 3 Expected: 416
 index: 2 Got: 416 Expected: 608
 index: 3 Got: 608 Expected: 3
 Please fix either the inputs or the model.

However in the log I obtain the following messages:

INFO: Array shape (416, 608, 3)
INFO: Result shape (3, 416, 608)
[main] TRACE ai.djl.inference.Predictor - Predictor input data: NDList size: 1
0 : (1, 3, 416, 608) float32

Why I am getting the error if the shape appear to be correct after applying the custom transform. The pipeline is correctly build and the custom transform is also well added to the pipeline.

Any idea?

Thank you in advance.

**Comment by lanking520** [comment]
@eanemo Hi, the default outcome from our image loader are HWC (Height, width channel) format. You may need some additional operation to make it to CHW (ONNX model looked for). We did that by calling `NDImageUtils.toTensor()`. This will make the NDArray from HWC to CHW and also do the normalization on the inputs

**Comment by eanemo** [comment]
I obtain the image from an inputStream like that:

ImageFactory.getInstance().fromInputStream(in);

I have changed to default ToTensor() transform and I get the same error. The problem is that if I debug the code, the translator does not execute the code in the processOutput method, so I think that the problem is not in the translator. The full code that load and executed the model is the following:

`if (image.getHeight() != this.f_height || image.getWidth() != this.f_width) {
      throw new BadResultException("The image is not " + f_width + "x" + f_height);
    }

    Pipeline pipeline = new Pipeline();
    pipeline.add(new ToTensor());

    Criteria<Image, Mask> criteria = Criteria.builder()
      .setTypes(Image.class, Mask.class) // Types of the model
      .optApplication(Application.CV.SEMANTIC_SEGMENTATION)
      .optTranslator(RootsSegmentationTranslator.builder().setPipeline(pipeline).build()) // Translation performed on input/output for the model
      .optEngine("OnnxRuntime") // Force to use the Onnx engine for this model
      .optModelName(modelName) // Model file name
      .optModelUrls(getModelDir().toAbsolutePath().toUri().toURL().toString()) // search models in specified path
      .optProgress(new ProgressBar()).build();

    logger.log(Level.INFO, "Loading the model {0}/" + modelName, getModelDir().toAbsolutePath().toString());

    ZooModel<Image, Mask> model = ModelZoo.loadModel(criteria);

    logger.log(Level.INFO, "Performing predictions ...");
    image.save(new FileOutputStream("C:\\tmp\\tmp.jpg"), "jpg");
    Predictor<Image, Mask> predictor = model.newPredictor();
    Mask mask = predictor.predict(image);
    // Get output prob dist
    float dist[][] = mask.getProbDist();`

The error comes out in the "Mask mask = predictor.predict(image);" line, and I does not manage to debug intermediate code, so I think that the problem is not in the translator.

Any idea?

Thank you in advance.

**Comment by lanking520** [comment]
Do you have the erorr log to share? You can use these to get the full logs. About the postprocessing. Since you are using hybrid mode, the output should be effectively dealt with the second engine of. your choice. What is in your `RootsSegmentationTranslator`. 

```
    runtimeOnly "org.slf4j:slf4j-api:1.7.26"
    runtimeOnly "org.slf4j:slf4j-simple:1.7.26"
```

You can also share me the model you try to on inference on, I can write some sample code to help you out

**Comment by lanking520** [comment]
Change the default `ToTensor` doesn't help much since it is also calling toTensor() below. The issue is you may call this toTensor() method twice in your preprocessing step. I would recommend to use some IDE (e.g IntelliJ) and use debug mode to dig in and see what NDArray operation are being done.

**Comment by eanemo** [comment]
> 
> 
> Do you have the erorr log to share? You can use these to get the full logs. About the postprocessing. Since you are using hybrid mode, the output should be effectively dealt with the second engine of. your choice. What is in your `RootsSegmentationTranslator`.
> 
> ```
>     runtimeOnly "org.slf4j:slf4j-api:1.7.26"
>     runtimeOnly "org.slf4j:slf4j-simple:1.7.26"
> ```
> 
> You can also share me the model you try to on inference on, I can write some sample code to help you out

Hi, I have obtained the following log:

[main] DEBUG ai.djl.engine.Engine - Engine loaded from provider: PyTorch
[main] DEBUG ai.djl.engine.Engine - Engine loaded from provider: OnnxRuntime
[main] WARN ai.djl.engine.Engine - More than one deep learning engines found.
[main] DEBUG ai.djl.engine.Engine - Found default engine: PyTorch
[main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: undefined ai.djl.localmodelzoo:model
[main] DEBUG ai.djl.repository.Resource - Preparing artifact: file:/D:/example/java/JavaProjects/WebProjects/MachineLearningService/target/test-classes/com/example/machinelearning/service/processors/rootsSegmentation/model/, ai.djl.localmodelzoo:model:N/A {}
[main] DEBUG ai.djl.repository.SimpleRepository - Skip prepare for local repository.

Loading:     100% |????????????????????????????????????????|
oct. 25, 2020 11:50:50 A. M. com.example.machinelearning.service.processors.djl.RootSegmentationProcessor calcResultFromTensor
INFO: Performing predictions ...
[main] TRACE ai.djl.inference.Predictor - Predictor input data: NDList size: 1
0 : (1, 3, 416, 608) float32

[Finalizer] WARN ai.djl.BaseModel - Model: model was not closed explicitly.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.829 s <<< FAILURE! - in com.example.machinelearning.service.processors.ImageProcessorTest
com.example.machinelearning.service.processors.ImageProcessorTest.rootsSegmentationTest  Time elapsed: 5.814 s  <<< ERROR!
ai.djl.engine.EngineException: 
ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: Got invalid dimensions for input: input_1 for the following indices
 index: 1 Got: 3 Expected: 416
 index: 2 Got: 416 Expected: 608
 index: 3 Got: 608 Expected: 3
 Please fix either the inputs or the model.
	at com.example.machinelearning.service.processors.ImageProcessorTest.lambda$rootsSegmentationTest$6(ImageProcessorTest.java:174)
	at com.example.machinelearning.service.processors.ImageProcessorTest.runTestProcessorDJL(ImageProcessorTest.java:78)
	at com.example.machinelearning.service.processors.ImageProcessorTest.testProcessorDJL(ImageProcessorTest.java:91)
	at com.example.machinelearning.service.processors.ImageProcessorTest.testProcessorDJL(ImageProcessorTest.java:84)
	at com.example.machinelearning.service.processors.ImageProcessorTest.rootsSegmentationTest(ImageProcessorTest.java:172)
Caused by: ai.onnxruntime.OrtException: 
Error code - ORT_INVALID_ARGUMENT - message: Got invalid dimensions for input: input_1 for the following indices
 index: 1 Got: 3 Expected: 416
 index: 2 Got: 416 Expected: 608
 index: 3 Got: 608 Expected: 3
 Please fix either the inputs or the model.
	at com.example.machinelearning.service.processors.ImageProcessorTest.lambda$rootsSegmentationTest$6(ImageProcessorTest.java:174)
	at com.example.machinelearning.service.processors.ImageProcessorTest.runTestProcessorDJL(ImageProcessorTest.java:78)
	at com.example.machinelearning.service.processors.ImageProcessorTest.testProcessorDJL(ImageProcessorTest.java:91)
	at com.example.machinelearning.service.processors.ImageProcessorTest.testProcessorDJL(ImageProcessorTest.java:84)
	at com.example.machinelearning.service.processors.ImageProcessorTest.rootsSegmentationTest(ImageProcessorTest.java:172)

I have sent a copy of the model I am trying to use in the ONNX format. Thank your help and time.

**Comment by lanking520** [comment]
Thanks, I will try to get it work on my end

**Comment by lanking520** [comment]
@eanemo I managed to get it work locally by doing this transformation

```java
.setPipeline(new Pipeline()
        .add(new Resize(608, 416)) // make height to 608 width to 416
        .add(new ToTensor())
        .add(array -> array.transpose(1, 2, 0))) // CHW to HWC
```

Your model prefer HWC input type. `ToTensor` will by default making HWC to CHW. You can choose to not using `toTensor` at all and use our source code to implement this method. (normalize the image input) Or simply use the workaround above to avoid shape mismatch issue.

**Comment by eanemo** [comment]
Hi,

I have used the solution you have provided and works fine. 

Thanks a lot.

**Comment by besmaGuesmi** [comment]
Hi @lanking520 
I have met the same issue! where I have added your lines of code? to test.py file?

Thanks

**Comment by frankfliu** [comment]
@besmaGuesmi 
The pipeline is for your customized Translator, see: https://github.com/deepjavalibrary/djl/blob/master/api/src/main/java/ai/djl/modality/cv/translator/BaseImageTranslator.java#L109
