### ISSUE TITLE
Clarity on what the parameters do for MxModelZoo.BERT_QA

### ISSUE THREAD

**Issue by salamanders** [awslabs/djl#24]
## Description
The "BBC Japan" example is great, but doesn't quite give enough info for the user to start experimenting on their own.

1. How much text can go into the `paragraph` variable?
2. Are there other datasets available beyond "book_corpus_wiki_en_uncased"?
3. (most importantly) What is the magic "384" number in `QAInput(question, paragraph, 384)` - should it be adjusted up or down, and when?
4. Is there a way to see any of the details (embeddings, or uncertainty, or answers that were below a confidence score), or is a CSV string the only output of a call to `predict`?

### Will this change the current api? How?
No.

### Who will benefit from this feature?
New users.

## References
examples/docs/BERT_question_and_answer.md

**Comment by lanking520** [comment]
384 is the maximum sequence length, or your total input word length. The model has been trained under this number, if the total words is no more than 384, padding will be added.

**Comment by zachgk** [comment]
@lanking520 Can we add this information to the example itself for future readers with the same question?

**Comment by salamanders** [comment]
So if I'm understanding: total word count (source paragraph plus question) must be <= 384 for any interaction that uses book_corpus_wiki_en_uncased?

Oh!   There goes my hopes of querying a large FAQ or an entire Wikipedia page.

**Comment by stu1130** [comment]
@salamanders we have PyTorch BERT QA that doesn't have this max length limitation.
Here is the [example](https://github.com/awslabs/djl/blob/master/jupyter/BERTQA.ipynb) and how you can [load your own bert](https://github.com/awslabs/djl/blob/master/jupyter/pytorch/load_your_own_pytorch_bert.ipynb).

**Comment by stu1130** [comment]
@salamanders I have updated the documents.
Feel free to reopen the issue or provide the feedback with PyTorch BERT
