### ISSUE TITLE
Parameter file not found in

### ISSUE THREAD

**Issue by androuino** [awslabs/djl#247]
## Question
Hi, after hybridizing a trained model(ssd_300_vgg16_atrous_voc) in mxnet and created a ssd_300_vgg16_atrous_voc.tar.gz, and loading it in djl using this code example:
```
 Translator<Image, DetectedObjects> translator = SingleShotDetectionTranslator.builder()
                .optRescaleSize(300, 300)
                .addTransform(new Resize(300, 300))
                .addTransform(new ToTensor())
                .optSynset(classes)
                .optThreshold(0.9f)
                .build();

        Criteria<Image, DetectedObjects> criteria =
                Criteria.builder()
                        .optApplication(Application.CV.OBJECT_DETECTION)
                        .setTypes(Image.class, DetectedObjects.class)
                        .optModelUrls("file:///Users/user/face-ssd-mxnet/ssd_300_vgg16_atrous_voc.tar.gz")
                        .optTranslator(translator)
                        .build();
```
Inside the ssd_300_vgg16_atrous_voc.tar.gz has two files which are: ssd_300_vgg16_atrous_custom-0000.params and ssd_300_vgg16_atrous_custom-symbol.json.

I am alway having this error:
```
Parameter file not found in: /Users/user/.djl.ai/cache/repo/model/undefined/ai/djl/localmodelzoo/260015bef62b6beefba7757bb955fb7c
```
This line in https://github.com/awslabs/djl/blob/9008e7a04f7d9352d25497a54bde4276a0e35a5f/api/src/main/java/ai/djl/BaseModel.java#L253-L269, epochs always returns -1.

Thanks.

**Comment by androuino** [comment]
Nevermind, I fixed it already.

**Comment by zachgk** [comment]
@androuino Can you share what you fixed for future users who run across this issue?
