### ISSUE TITLE
Double-Checked Locking

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [awslabs/djl#253]
https://github.com/awslabs/djl/blob/f4f35244b74efa2f50c5a23289922d143cad64dc/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxSymbolBlock.java#L167-L169

Double-Checked Locking is widely cited and used as an efficient method for implementing lazy initialization in a multithreaded environment.
Unfortunately, it will not work reliably in a platform independent way when implemented in Java, without additional synchronization.

**Comment by frankfliu** [comment]
Double-Checked Locking is discouraged for singleton implementation, and doesn't really work in Java 1.4 and before.

In this case, the `first` is just a boolean, and assignment is atomic (we probably should add `volatile` to it). It should be working fine here.
