### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [awslabs/djl#254]
https://github.com/awslabs/djl/blob/f4f35244b74efa2f50c5a23289922d143cad64dc/basicdataset/src/main/java/ai/djl/basicdataset/ImageNet.java#L104

The program can potentially fail to release a system resource.

**Comment by frankfliu** [comment]
@QiAnXinCodeSafe Good catch.
Would you mind raise a PR to resolve this issue?
