### ISSUE TITLE
train sentiment analysis

### ISSUE THREAD

**Issue by hs2222** [awslabs/djl#257]
## Description
I ran the TrainSentimentAnalysis class with arguments ("-g", "1", "-e", "1", "-m", "2") in TrainSentimentAnalysisTest class, then the program throws an exception.

### Expected Behavior
train well

### Error Message
09:13:26.483 [main] DEBUG ai.djl.repository.Resource - Preparing artifact: MXNet, ai.djl.mxnet:glove:0.0.1 {"dimensions":"50"}
09:13:26.484 [main] DEBUG ai.djl.repository.AbstractRepository - Files have been downloaded already: /Users/hs/.djl.ai/cache/repo/model/nlp/word_embedding/ai/djl/mxnet/glove/50/0.0.1
09:13:26.882 [main] DEBUG ai.djl.BaseModel - Try to load model from /Users/hs/.djl.ai/cache/repo/model/nlp/word_embedding/ai/djl/mxnet/glove/50/0.0.1/glove-0000.params
09:13:26.883 [main] DEBUG ai.djl.BaseModel - Loading saved model: glove parameter
09:13:27.004 [main] DEBUG ai.djl.BaseModel - DJL model loaded successfully
09:13:28.270 [main] DEBUG ai.djl.repository.Resource - Preparing artifact: BasicDataset, ai.djl.basicdataset:stanford-movie-review:1.0 {}
09:13:28.271 [main] DEBUG ai.djl.repository.AbstractRepository - Files have been downloaded already: /Users/hs/.djl.ai/cache/repo/dataset/nlp/ai/djl/basicdataset/stanford-movie-review/1.0
09:13:31.347 [main] DEBUG ai.djl.repository.Resource - Preparing artifact: BasicDataset, ai.djl.basicdataset:stanford-movie-review:1.0 {}
09:13:31.347 [main] DEBUG ai.djl.repository.AbstractRepository - Files have been downloaded already: /Users/hs/.djl.ai/cache/repo/dataset/nlp/ai/djl/basicdataset/stanford-movie-review/1.0
09:13:34.254 [main] INFO  a.d.t.l.LoggingTrainingListener - Training on: cpu().
09:13:34.255 [main] INFO  a.d.t.l.LoggingTrainingListener - Load MXNet Engine Version 1.7.0 in 0.046 ms.
09:13:34.314 [main] ERROR ai.djl.training.dataset.DataIterable - java.lang.IllegalArgumentException: The desired shape has too many dimensions
09:13:34.352 [main] ERROR c.tigerobo.javadl.train.PtSATrainer - train failed!
java.lang.IllegalStateException: Data loading failed
	at ai.djl.training.dataset.DataIterable.next(DataIterable.java:155)
	at ai.djl.training.dataset.DataIterable.next(DataIterable.java:41)
	at ai.djl.training.EasyTrain.fit(EasyTrain.java:44)
	at com.tigerobo.javadl.train.PtSATrainer.train(PtSATrainer.java:99)
	at com.tigerobo.javadl.PtSATest.train(PtSATest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: The desired shape has too many dimensions
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at ai.djl.training.dataset.DataIterable.next(DataIterable.java:152)
	... 26 common frames omitted
Caused by: java.lang.IllegalArgumentException: The desired shape has too many dimensions
	at ai.djl.mxnet.engine.MxNDArray.repeatsToMatchShape(MxNDArray.java:1466)
	at ai.djl.mxnet.engine.MxNDArray.repeat(MxNDArray.java:1308)
	at ai.djl.translate.PaddingStackBatchifier.batchify(PaddingStackBatchifier.java:68)
	at ai.djl.training.dataset.DataIterable.fetch(DataIterable.java:175)
	at ai.djl.training.dataset.DataIterable.access$100(DataIterable.java:41)
	at ai.djl.training.dataset.DataIterable$PreFetchCallable.call(DataIterable.java:224)
	at ai.djl.training.dataset.DataIterable$PreFetchCallable.call(DataIterable.java:211)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

## How to Reproduce?
https://github.com/awslabs/djl/blob/v0.8.0/examples/src/main/java/ai/djl/examples/training/TrainSentimentAnalysis.java

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.set the arguments for main function as ("-g", "1", "-e", "1", "-m", "2")
2.run TrainSentimentAnalysis class

## What have you tried to solve it?

1.I tried to change the new shape's dimension on line 196, but I don't know set to set well

## Environment Info

Please run the command `./gradlew debugEnv` from the root directory of DJL (if necessary, clone DJL first). It will output information about your system, environment, and installation that can help us debug your issue. Paste the output of the command below:

[INFO ] - ----------System Properties----------
[INFO ] - io.netty.allocator.numHeapArenas: 1
[INFO ] - java.vendor.version: JBR-11.0.8.10-944.34-jcef
[INFO ] - java.specification.version: 1.8
[INFO ] - pty4j.preferred.native.folder: /Applications/IntelliJ IDEA CE.app/Contents/lib/pty4j-native
[INFO ] - file.encoding: UTF-8
[INFO ] - pty4j.tmpdir: /Users/hs/Library/Caches/JetBrains/IdeaIC2020.2/tmp
[INFO ] - jdk.module.illegalAccess.silent: true
[INFO ] - org.gradle.internal.publish.checksums.insecure: true
[INFO ] - java.vm.name: OpenJDK 64-Bit Server VM
[INFO ] - line.separator: 

[INFO ] - idea.jre.check: true
[INFO ] - user.dir: /Users/hs/Projects/niubi/djl/integration
[INFO ] - java.ext.dirs: /Users/hs/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java
[INFO ] - idea.max.intellisense.filesize: 2500
[INFO ] - os.arch: x86_64
[INFO ] - java.awt.graphicsenv: sun.awt.CGraphicsEnvironment
[INFO ] - kotlinx.coroutines.debug: off
[INFO ] - jna.platform.library.path: /usr/lib:/usr/lib
[INFO ] - java.rmi.server.hostname: 127.0.0.1
[INFO ] - java.vendor.url.bug: https://bugreport.java.com/bugreport/
[INFO ] - java.io.tmpdir: /var/folders/3g/2drk3qmj39b7h61rwf6w8f8w0000gn/T/
[INFO ] - sun.cpu.endian: little
[INFO ] - sun.os.patch.level: unknown
[INFO ] - io.netty.allocator.numDirectArenas: 1
[INFO ] - java.vm.specification.version: 1.8
[INFO ] - idea.popup.weight: heavy
[INFO ] - idea.xdebug.key: -Xdebug
[INFO ] - java.vm.specification.name: Java Virtual Machine Specification
[INFO ] - jdk.debug: release
[INFO ] - io.netty.machineId: 28:f0:76:ff:fe:16:65:0e
[INFO ] - sun.java.command: ai.djl.integration.util.DebugEnvironment
[INFO ] - java.class.path: /Users/hs/Projects/niubi/djl/integration/build/classes/java/main:/Users/hs/Projects/niubi/djl/integration/build/resources/main:/Users/hs/.gradle/caches/modules-2/files-2.1/commons-cli/commons-cli/1.4/c51c00206bb913cd8612b24abd9fa98ae89719b1/commons-cli-1.4.jar:/Users/hs/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-slf4j-impl/2.13.3/7cca27a921a18645139cf651c04b83b1a19cfd76/log4j-slf4j-impl-2.13.3.jar:/Users/hs/Projects/niubi/djl/basicdataset/build/libs/basicdataset-0.8.0-SNAPSHOT.jar:/Users/hs/Projects/niubi/djl/model-zoo/build/libs/model-zoo-0.8.0-SNAPSHOT.jar:/Users/hs/Projects/niubi/djl/testing/build/libs/testing-0.8.0-SNAPSHOT.jar:/Users/hs/.gradle/caches/modules-2/files-2.1/org.testng/testng/7.1.0/7504709f2d0b6e5070d1c6a0cae6c1c605489f8/testng-7.1.0.jar:/Users/hs/Projects/niubi/djl/mxnet/mxnet-model-zoo/build/libs/mxnet-model-zoo-0.8.0-SNAPSHOT.jar:/Users/hs/Projects/niubi/djl/mxnet/mxnet-engine/build/libs/mxnet-engine-0.8.0-SNAPSHOT.jar:/Users/hs/.gradle/caches/modules-2/files-2.1/ai.djl.mxnet/mxnet-native-auto/1.7.0-backport/ee5b368ef94c1fcec4ade4a6edacffb420fefce7/mxnet-native-auto-1.7.0-backport.jar:/Users/hs/Projects/niubi/djl/api/build/libs/api-0.8.0-SNAPSHOT.jar:/Users/hs/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.30/b5a4b6d16ab13e34a88fae84c35cd5d68cac922c/slf4j-api-1.7.30.jar:/Users/hs/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.13.3/4e857439fc4fe974d212adaaaa3b118b8b50e3ec/log4j-core-2.13.3.jar:/Users/hs/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.13.3/ec1508160b93d274b1add34419b897bae84c6ca9/log4j-api-2.13.3.jar:/Users/hs/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-csv/1.8/37ca9a9aa2d4be2599e55506a6d3170dd7a3df4/commons-csv-1.8.jar:/Users/hs/.gradle/caches/modules-2/files-2.1/com.beust/jcommander/1.72/6375e521c1e11d6563d4f25a07ce124ccf8cd171/jcommander-1.72.jar:/Users/hs/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/4.1.0/faf9ee8ac09eafd1128091426dd367a8c0085d55/guice-4.1.0-no_aop.jar:/Users/hs/.gradle/caches/modules-2/files-2.1/org.yaml/snakeyaml/1.21/18775fdda48574784f40b47bf478ab0593f92e4d/snakeyaml-1.21.jar:/Users/hs/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.8.6/9180733b7df8542621dc12e21e87557e8c99b8cb/gson-2.8.6.jar:/Users/hs/.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna/5.3.0/4654d1da02e4173ba7b64f7166378847db55448a/jna-5.3.0.jar:/Users/hs/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-compress/1.20/b8df472b31e1f17c232d2ad78ceb1c84e00c641b/commons-compress-1.20.jar:/Users/hs/.gradle/caches/modules-2/files-2.1/javax.inject/javax.inject/1/6975da39a7040257bd51d21a231b76c915872d38/javax.inject-1.jar:/Users/hs/.gradle/caches/modules-2/files-2.1/aopalliance/aopalliance/1.0/235ba8b489512805ac13a8f9ea77a1ca5ebe3e8/aopalliance-1.0.jar:/Users/hs/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/19.0/6ce200f6b23222af3d8abb6b6459e6c44f4bb0e9/guava-19.0.jar
[INFO ] - java.runtime.name: OpenJDK Runtime Environment
[INFO ] - java.vm.vendor: AdoptOpenJDK
[INFO ] - gopherProxySet: false
[INFO ] - org.gradle.internal.http.socketTimeout: 120000
[INFO ] - library.jansi.path: /Users/hs/.gradle/native/jansi/1.18/osx
[INFO ] - java.library.path: /Users/hs/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
[INFO ] - java.vendor.url: http://java.oracle.com/
[INFO ] - apple.laf.useScreenMenuBar: true
[INFO ] - java.specification.vendor: Oracle Corporation
[INFO ] - java.version.date: 2020-07-14
[INFO ] - user.home: /Users/hs
[INFO ] - idea.dynamic.classpath: false
[INFO ] - idea.platform.prefix: Idea
[INFO ] - log4j.defaultInitOverride: true
[INFO ] - io.netty.processId: 31859
[INFO ] - org.gradle.internal.http.connectionTimeout: 60000
[INFO ] - awt.toolkit: sun.lwawt.macosx.LWCToolkit
[INFO ] - idea.cycle.buffer.size: 1024
[INFO ] - sun.io.unicode.encoding: UnicodeBig
[INFO ] - javax.swing.rebaseCssSizeMap: true
[INFO ] - java.awt.printerjob: sun.lwawt.macosx.CPrinterJob
[INFO ] - idea.max.content.load.filesize: 20000
[INFO ] - com.jetbrains.suppressWindowRaise: false
[INFO ] - user.variant: 
[INFO ] - idea.no.launcher: false
[INFO ] - idea.smooth.progress: false
[INFO ] - java.vm.version: 25.265-b01
[INFO ] - path.separator: :
[INFO ] - jdk.http.auth.tunneling.disabledSchemes: ""
[INFO ] - os.version: 10.15.7
[INFO ] - java.vm.info: mixed mode
[INFO ] - java.home: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre
[INFO ] - user.country: CN
[INFO ] - java.class.version: 52.0
[INFO ] - file.separator: /
[INFO ] - java.specification.name: Java Platform API Specification
[INFO ] - sun.cpu.isalist: 
[INFO ] - sun.jnu.encoding: UTF-8
[INFO ] - file.encoding.pkg: sun.io
[INFO ] - jna.tmpdir: /Users/hs/Library/Caches/JetBrains/IdeaIC2020.2/tmp
[INFO ] - java.endorsed.dirs: 
[INFO ] - java.util.concurrent.ForkJoinPool.common.threadFactory: com.intellij.concurrency.IdeaForkJoinWorkerThreadFactory
[INFO ] - sun.arch.data.model: 64
[INFO ] - user.timezone: Asia/Shanghai
[INFO ] - swing.bufferPerWindow: true
[INFO ] - java.version: 1.8.0_265
[INFO ] - CVS_PASSFILE: ~/.cvspass
[INFO ] - java.vm.compressedOopsMode: Zero based
[INFO ] - jna.nosys: true
[INFO ] - idea.fatal.error.notification: disabled
[INFO ] - io.netty.allocator.useCacheForAllThreads: false
[INFO ] - sun.boot.library.path: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib
[INFO ] - jdk.attach.allowAttachSelf: true
[INFO ] - idea.version: 2020.2.3
[INFO ] - user.language: en
[INFO ] - idea.home.path: /Applications/IntelliJ IDEA CE.app/Contents
[INFO ] - idea.active: true
[INFO ] - java.rmi.server.disableHttp: true
[INFO ] - io.netty.allocator.cacheTrimIntervalMillis: 600000
[INFO ] - user.name: hs
[INFO ] - io.netty.serviceThreadPrefix: Netty 
[INFO ] - jna.loaded: true
[INFO ] - jb.vmOptionsFile: /Users/hs/Library/Application Support/JetBrains/IdeaIC2020.2/idea.vmoptions
[INFO ] - java.runtime.version: 1.8.0_265-b01
[INFO ] - java.vm.specification.vendor: Oracle Corporation
[INFO ] - sun.boot.class.path: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/classes
[INFO ] - os.name: Mac OS X
[INFO ] - jnidispatch.path: /Users/hs/Library/Caches/JetBrains/IdeaIC2020.2/tmp/jna13913931625936226942.tmp
[INFO ] - idea.vendor.name: JetBrains
[INFO ] - ai.djl.logging.level: debug
[INFO ] - idea.paths.selector: IdeaIC2020.2
[INFO ] - sun.management.compiler: HotSpot 64-Bit Tiered Compilers
[INFO ] - idea.executable: idea
[INFO ] - sun.java.launcher: SUN_STANDARD
[INFO ] - com.apple.mrj.application.live-resize: false
[INFO ] - java.vendor: AdoptOpenJDK
[INFO ] - 
[INFO ] - ----------Environment Variables----------
[INFO ] - PATH: /usr/local/Caskroom/miniconda/base/condabin:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin:/Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3/bin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[INFO ] - SHELL: /bin/zsh
[INFO ] - CONDA_EXE: /usr/local/Caskroom/miniconda/base/bin/conda
[INFO ] - JAVA_HOME: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
[INFO ] - HOMEBREW_BOTTLE_DOMAIN: https://mirrors.aliyun.com/homebrew/homebrew-bottles
[INFO ] - OLDPWD: /
[INFO ] - CONDA_PYTHON_EXE: /usr/local/Caskroom/miniconda/base/bin/python
[INFO ] - USER: hs
[INFO ] - TMPDIR: /var/folders/3g/2drk3qmj39b7h61rwf6w8f8w0000gn/T/
[INFO ] - SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.SyN0JB68If/Listeners
[INFO ] - _CE_CONDA: 
[INFO ] - MAVEN_HOME: /Applications/IntelliJ IDEA CE.app/Contents/plugins/maven/lib/maven3
[INFO ] - XPC_FLAGS: 0x0
[INFO ] - MYSQL_HOME: /usr/local/mysql
[INFO ] - VERSIONER_PYTHON_VERSION: 2.7
[INFO ] - _CE_M: 
[INFO ] - JAVA_MAIN_CLASS_30188: ai.djl.integration.util.DebugEnvironment
[INFO ] - __CF_USER_TEXT_ENCODING: 0x1F5:0x0:0x0
[INFO ] - LOGNAME: hs
[INFO ] - LC_CTYPE: en_US.UTF-8
[INFO ] - XPC_SERVICE_NAME: com.jetbrains.intellij.ce.9060
[INFO ] - CONDA_SHLVL: 0
[INFO ] - HOME: /Users/hs
[INFO ] - 
[INFO ] - ----------Default Engine----------
[DEBUG] - cudart library not found.
[DEBUG] - Using cache dir: /Users/hs/.djl.ai/mxnet
[DEBUG] - Loading mxnet library from: /Users/hs/.djl.ai/mxnet/1.7.0-backport-mkl-osx-x86_64/libmxnet.dylib
[DEBUG] - Engine loaded from provider: MXNet
[DEBUG] - Found default engine: MXNet
[INFO ] - Engine name: MXNet
[INFO ] - Engine version: 1.7.0
[DEBUG] - Using cache dir: /Users/hs/.djl.ai/mxnet
[INFO ] - MXNet Library: /Users/hs/.djl.ai/mxnet/1.7.0-backport-mkl-osx-x86_64/libmxnet.dylib
[INFO ] - MXNet Features: BLAS_APPLE, CPU_SSE, SIGNAL_HANDLER, LAPACK, CPU_SSE2, CPU_SSE3, CPU_SSE4_1, OPENCV, MKLDNN
[INFO ] - 
[INFO ] - ----------Hardware----------
[INFO ] - Available processors (cores): 8
[INFO ] - Byte Order: LITTLE_ENDIAN
[INFO ] - Free memory (bytes): 206323872
[INFO ] - Maximum memory (bytes): 3817865216
[INFO ] - Total memory available to JVM (bytes): 257425408
[INFO ] - Heap committed: 257425408
[INFO ] - Heap nonCommitted: 20709376
[INFO ] - GPU Count: 0
[INFO ] - Default Device: cpu()
[INFO ] - GCC: 
[INFO ] - Apple clang version 12.0.0 (clang-1200.0.32.2)
[INFO ] - Target: x86_64-apple-darwin19.6.0
[INFO ] - Thread model: posix
[INFO ] - InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by lanking520** [comment]
@hs2222 Just added a fix ⬆️ . Please check if this change helps!

**Comment by hs2222** [comment]
> @hs2222 Just added a fix ⬆️ . Please check if this change helps!

Thanks for your answer. I pulled the code and ran it, but the train process stuck at 98% for an hour, the log is as follows:

14:22:28.331 [main] DEBUG ai.djl.util.cuda.CudaUtils - cudart library not found.
14:22:28.334 [main] DEBUG ai.djl.mxnet.jna.LibUtils - Using cache dir: /Users/hs/.djl.ai/mxnet
14:22:28.340 [main] DEBUG ai.djl.mxnet.jna.LibUtils - Loading mxnet library from: /Users/hs/.djl.ai/mxnet/1.7.0-backport-mkl-osx-x86_64/libmxnet.dylib
14:22:28.605 [main] DEBUG ai.djl.engine.Engine - Engine loaded from provider: MXNet
14:22:28.610 [main] DEBUG ai.djl.pytorch.jni.LibUtils - Using cache dir: /Users/hs/.djl.ai/pytorch
14:22:28.612 [main] DEBUG ai.djl.pytorch.jni.LibUtils - Loading pytorch library from: /Users/hs/.djl.ai/pytorch/1.6.0-cpu-osx-x86_64/0.8.0-SNAPSHOT-cpu-libdjl_torch.dylib
14:22:28.749 [main] INFO  ai.djl.pytorch.engine.PtEngine - Number of inter-op threads is 4
14:22:28.749 [main] INFO  ai.djl.pytorch.engine.PtEngine - Number of intra-op threads is 1
14:22:28.749 [main] DEBUG ai.djl.engine.Engine - Engine loaded from provider: PyTorch
14:22:28.754 [main] DEBUG ai.djl.tensorflow.engine.LibUtils - Using cache dir: /Users/hs/.djl.ai/tensorflow
14:22:28.754 [main] DEBUG ai.djl.tensorflow.engine.LibUtils - Loading TensorFlow library from: /Users/hs/.djl.ai/tensorflow/2.3.0-cpu-osx-x86_64/libjnitensorflow.dylib
2020-11-03 14:22:29.249014: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-03 14:22:29.249300: I external/org_tensorflow/tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
14:22:29.251 [main] DEBUG ai.djl.engine.Engine - Engine loaded from provider: TensorFlow
14:22:29.251 [main] DEBUG ai.djl.engine.Engine - Found default engine: MXNet
14:22:29.265 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Searching model in zoo provider: ai.djl.basicmodelzoo.BasicZooProvider
14:22:29.281 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Searching model in zoo provider: ai.djl.repository.zoo.DefaultZooProvider
14:22:29.282 [main] DEBUG ai.djl.repository.zoo.ModelZoo - No model zoo found in zoo provider: ai.djl.repository.zoo.DefaultZooProvider
14:22:29.283 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Searching model in zoo provider: ai.djl.mxnet.zoo.MxZooProvider
14:22:29.289 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Searching model in zoo provider: ai.djl.pytorch.zoo.PtZooProvider
14:22:29.294 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Searching model in zoo provider: ai.djl.tensorflow.zoo.TfZooProvider
14:22:29.295 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.zoo:resnet
14:22:29.295 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.zoo:mlp
14:22:29.295 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/object_detection ai.djl.zoo:ssd
14:22:29.295 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/object_detection ai.djl.mxnet:ssd
14:22:29.295 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/object_detection ai.djl.mxnet:yolo
14:22:29.295 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:alexnet
14:22:29.295 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:darknet
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:densenet
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:googlenet
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:inceptionv3
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:mlp
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:mobilenet
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:resnest
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:resnet
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:resnext
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:senet
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:se_resnext
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:squeezenet
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:vgg
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:xception
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/pose_estimation ai.djl.mxnet:simple_pose
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/instance_segmentation ai.djl.mxnet:mask_rcnn
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/action_recognition ai.djl.mxnet:action_recognition
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: nlp/question_answer ai.djl.mxnet:bertqa
14:22:29.296 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: nlp/word_embedding ai.djl.mxnet:glove
14:22:29.351 [main] DEBUG ai.djl.repository.Resource - Preparing artifact: MXNet, ai.djl.mxnet:glove:0.0.1 {"dimensions":"50"}
14:22:29.351 [main] DEBUG ai.djl.repository.AbstractRepository - Files have been downloaded already: /Users/hs/.djl.ai/cache/repo/model/nlp/word_embedding/ai/djl/mxnet/glove/50/0.0.1
14:22:29.775 [main] DEBUG ai.djl.BaseModel - Try to load model from /Users/hs/.djl.ai/cache/repo/model/nlp/word_embedding/ai/djl/mxnet/glove/50/0.0.1/glove-0000.params
14:22:29.776 [main] DEBUG ai.djl.BaseModel - Loading saved model: glove parameter
14:22:29.894 [main] DEBUG ai.djl.BaseModel - DJL model loaded successfully
14:22:29.904 [main] DEBUG ai.djl.repository.Resource - Preparing artifact: BasicDataset, ai.djl.basicdataset:stanford-movie-review:1.0 {}
14:22:29.904 [main] DEBUG ai.djl.repository.AbstractRepository - Files have been downloaded already: /Users/hs/.djl.ai/cache/repo/dataset/nlp/ai/djl/basicdataset/stanford-movie-review/1.0
14:22:40.048 [main] DEBUG ai.djl.repository.Resource - Preparing artifact: BasicDataset, ai.djl.basicdataset:stanford-movie-review:1.0 {}
14:22:40.048 [main] DEBUG ai.djl.repository.AbstractRepository - Files have been downloaded already: /Users/hs/.djl.ai/cache/repo/dataset/nlp/ai/djl/basicdataset/stanford-movie-review/1.0
14:22:48.102 [main] INFO  a.d.t.l.LoggingTrainingListener - Training on: cpu().
14:22:48.102 [main] INFO  a.d.t.l.LoggingTrainingListener - Load MXNet Engine Version 1.7.0 in 0.056 ms.
Training:     98% |████████████████████████████████████████| SoftmaxCrossEntropyLoss: 0.67, speed: 2.80 items/sec

**Comment by lanking520** [comment]
@hs2222 I am able to reproduce your issue. Will take a look.

**Comment by YuJiankun** [comment]
The problem might be in class FixedBucketSampler.Iterate. The constructor and method next may cause infinite loop.

**Comment by lanking520** [comment]
@hs2222 please try out the fix
