### ISSUE TITLE
Add direct API support to override arguments when loading zoo models

### ISSUE THREAD

**Issue by shapirov103** [awslabs/djl#26]
## Description
Feature to allow passing argument overrides when loading models. Such argument overrides may, for example, allow changing default threshold for translators or adjust other parameters. 

### Will this change the current api? How?

Yes, the API will change, specifically, load methods.

For example at present the method signature is: 

    ai.djl.repository.zoo.ModelLoader#loadModel(Map<java.lang.String,java.lang.String> criteria);

It would be nice to get a flavor like:

   ai.djl.repository.zoo.ModelLoader#loadModel(Map<java.lang.String,java.lang.String> criteria, Map<> argumentOverrides);

The above is a trivialized approach that may be too simplistic. 

### Who will benefit from this feature?

Library consumers who would like to load models and adjust default parameters. 

## Additional Info

This may be beneficial if customers are trying to externalize configuration parameters needed to load models, predictors, translators and allow creating generic configuration in IoC environments like Spring.

**Comment by zachgk** [comment]
We just created a global load model method with signature `ModelZoo.loadModel(Criteria<I, O> criteria)`. You can pass override arguments as part of the `Criteria` by using

```java
criteria = Criteria.builder()
  ...
  .optArguments(mapOfOverrideArguments)
  .optArgument("overrideArgumentName", overrideArgumentValue)
  .build();
```
