### ISSUE TITLE
Onnx CPU inference performance problem

### ISSUE THREAD

**Issue by thhart** [awslabs/djl#284]
## Description
I have a performance problem using the Onnx engine. Using Onnx runtime directly (without DJL) I have a warm-up of 3 s when doing inference but after short time the prediction goes fast down to 400 ms. All this is done in one Onnx session.

Using the DJL wrapper it looks like the warm-up is done always so prediction keeps at 3 s. All this is done in one DJL predictor.

This is on top  of 0.9-SNAPSHOT. I know all this is not much information and I try to provide a test case ASAP however  I wanted to ask you if you have any idea already in front?

**Comment by frankfliu** [comment]
@thhart  You can use our benchmar tool to test the inference performance:

```
./gradlew benchmark --args="-n YOUR_MODEL_NAME -c 1000 -s 1,224,224,3" -Dai.djl.repository.zoo.location=file://$PWD/models/YOUR_MODEL_NAME -Dai.djl.default_engine=OnnxRuntime
```

**Comment by lanking520** [comment]
@thhart Can you share the code you tried to benchmark ONNX runtime on? We are creating new Environment everytime new input comes.

**Comment by thhart** [comment]
> We are creating new Environment everytime new input comes.

Yes, this I was afraid of and might explain my problems, will try to provide a test/case model/example asap, thanks for the quick reply.

**Comment by frankfliu** [comment]
@thhart OrtEnvironment.getEnvironment() should not create a new instance, it re-use the static OrtEnvironment.INSTANCE if possible. It must be something else.

**Comment by thhart** [comment]
@frankfliu Yes, your are right the environment is not recreated indeed, check in a debug, will dig further...

**Comment by thhart** [comment]
Tried to run this with a local model file but somehow benchmark is distorting the path and does not load the model.

<pre>
 ./gradlew benchmark --args="-n yolov5s.onnx -c 1000 -s 1,224,224,3" -Dai.djl.repository.zoo.location=file://$PWD/yolov5s.onnx -Dai.djl.default_engine=OnnxRuntime 


> Task :examples:benchmark FAILED
[INFO ] - Load library 1.4.0 in 106.253 ms.
[INFO ] - Running Benchmark on: cpu().
[ERROR] - Unexpected error
ai.djl.repository.zoo.ModelNotFoundException: No matching model with specified Input/Output type found.
        at ai.djl.repository.zoo.ModelZoo.loadModel(ModelZoo.java:173) ~[api-0.9.0-SNAPSHOT.jar:?]
        at ai.djl.examples.inference.benchmark.util.AbstractBenchmark.loadModel(AbstractBenchmark.java:301) ~[main/:?]
        at ai.djl.examples.inference.benchmark.Benchmark.predict(Benchmark.java:44) ~[main/:?]
        at ai.djl.examples.inference.benchmark.util.AbstractBenchmark.runBenchmark(AbstractBenchmark.java:131) [main/:?]
        at ai.djl.examples.inference.benchmark.Benchmark.main(Benchmark.java:33) [main/:?]

</pre>

**Comment by frankfliu** [comment]
@thhart 
You need create a folder `yolov5s` and put yolov5s.onnx in `yolov5s`, the call:

```
./gradlew benchmark --args="-n yolov5s -c 1000 -s 1,224,224,3" -Dai.djl.repository.zoo.location=file://$PWD/yolov5s -Dai.djl.default_engine=OnnxRuntime 
```

**Comment by thhart** [comment]
@frankfliu Hi Frank, checking all this I found out your Onnx engine is not implemented yet (see OrtNDArray for UnsupportedOperationException). All I do right now is to use Mxnet engine injection somehow as I have these in the dependency list as well. Looks like DJL is either by fault or not misusing the Mxnet layer then for tensor data handling before passing to Onnx models loaded. With this I successful get the Onnx model running. I am not into you architecture if this is wished or not however I can confirm it is working as the network is giving out correct results. Of course this might have other side effects as well.
I am still working on a test case...

**Comment by thhart** [comment]
The problem was in output parsing within YoloV5Translator. Created PR for this.
https://github.com/awslabs/djl/pull/286
