### ISSUE TITLE
Loading ExtraFilesMap in Java?

### ISSUE THREAD

**Issue by macster110** [awslabs/djl#312]
## Question

When saving a trained model using Pytorch, extra information can be added in Python or C++ using an ExtraFilesMap object. In Python this extra metadata can be extracted from a saved model e.g. via

```
# load the jit model and associated settings. 
extra_files = torch._C.ExtraFilesMap()
extra_files['dataOpts'] = ''
model = torch.jit.load(filepath_model, _extra_files=extra_files)
```

Using djl, a trained model can be loaded in Java, however, however, there does not appear to be any method to extract the ExtraFileMap information? I've spent some time trying to find a solution with no luck. Am I missing something - is this possible using djl? 

If not, can we bump this to a feature request. It's very useful having metadata such as this stored with the model. 

Thanks for any help!

**Comment by lanking520** [comment]
@macster110 DJL are currently using this C++ API to load extra files: https://pytorch.org/cppdocs/api/function_namespacetorch_1_1jit_1a3382df04456abc67b49bd1b6b3aacdb2.html#exhale-function-namespacetorch-1-1jit-1a3382df04456abc67b49bd1b6b3aacdb2 

We already implemented the JNI for it. However, we didn't expose loading extra_files functionalities since we find if hard to find a model with extramaps. If you happened to have a sample model that contains extraFileMaps, we can definitely look into it and provide this feature to our frontend.

**Comment by lanking520** [comment]
After some looking: https://pytorch.org/cppdocs/api/typedef_namespacetorch_1_1jit_1a1a5415ba7fa76a3e8f1ff20b7285e317.html. This seemed just to be a `Map<String, String>`.  We can offer this additional input from the model loading sections

**Comment by frankfliu** [comment]
DJL's model API already support metadata: https://github.com/awslabs/djl/blob/master/api/src/main/java/ai/djl/Model.java#L178

We should be able to put those information in model's property.

**Comment by lanking520** [comment]
⬆️ After the fix. You should be able to do the followings:

```java
Criteria<Image, Classifications> criteria = Criteria.builder()
  .setTypes(Image.class, Classifications.class)
  .optModelUrls(modelUrl)
  .optOption("extraFiles.dataOpts", "your value")  // <- pass in here 
  .optTranslator(ImageClassificationTranslator.builder()
                 .setPipeline(new Pipeline()
                              .add(new Resize(224, 224))
                              .add(new ToTensor()))
                 .optApplySoftmax(true).build())
```
or load the model manually by passing the Map of options.

**Comment by macster110** [comment]
@lanking520 , Thanks very much for this. I have model file [here](https://drive.google.com/file/d/1NqxZcv7LY0lEiDYjehlxhM8oVXFh_i9Q/view?usp=sharing) which works fine with djl and has an extra files map saved. 
The python code that loads the extra information is below - perhaps that will be useful for testing.  

So do you envisage this feature being available in the next release? 

Thanks again. 

```
# load the jit model and associated settings. 
extra_files = torch._C.ExtraFilesMap()
extra_files['dataOpts'] = ''
model = torch.jit.load(filepath_model, _extra_files=extra_files)

model.eval();

print(extra_files['dataOpts'] )

# get the string arguments
dlparams = extra_files['dataOpts']

# convert the string to a dictionary, 
dlparamsdict = eval(dlparams) 

#settings for stuff. 
n_fft =  dlparamsdict['n_fft']
hop_length = dlparamsdict['hop_length']
n_freq_bins = dlparamsdict['n_freq_bins']
sr = dlparamsdict['sr']
fmin = dlparamsdict['fmin']
fmax = dlparamsdict['fmax']
```

**Comment by lanking520** [comment]
@macster110 Hi, I just saw your use case, are you trying to pull data out of the pt file instead of loading extra?

**Comment by lanking520** [comment]
Ok, I optimized our import procedure. You will be able to fetch these information through:

```java
Criteria<Image, Classifications> criteria = Criteria.builder()
  .setTypes(Image.class, Classifications.class)
  .optModelUrls(modelUrl)
  .optOption("extraFiles", "dataOpts")  // <- pass in here 
  .optTranslator(ImageClassificationTranslator.builder()
                 .setPipeline(new Pipeline()
                              .add(new Resize(224, 224))
                              .add(new ToTensor()))
                 .optApplySoftmax(true).build())

ZooModel<Image, Classifications> model = ModelZoo.load(criteria);
model.getProperty("dataOpts"); // String representation of your dictionary
```

I tested with the model you have provided and it is working now. You can get the SNAPSHOT version and use it today. We have nightly snapshot published to maven everyday.

**Comment by macster110** [comment]
Awesome, thanks very much for this. I will test and get back to you.

**Comment by macster110** [comment]
Great, thanks v ery much @lanking520 . This now works. For future reference here is the code to manually load in a PyTorch model we trained with extra_files added. 

```
		Path modelDir = Paths.get("/Users/au671271/Google Drive/Aarhus_research/PAMGuard_bats_2020/deep_learning/BAT/models/bats_denmark/");
		String modelName= "BAT_4ms_256ft_8hop_128_NOISEAUG_40000_100000_-100_0_256000_JAMIE.pk";

		Map<String, String> hashMap = new HashMap<String, String>();
		hashMap.put("extraFiles" , "dataOpts");

		try {
			model.load(modelDir, modelName, hashMap);
		} catch (MalformedModelException | IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}

		System.out.println("Model properties " + model.getProperty("dataOpts"));
```

Also, in the current snapshot there is a bug in  PtModel line 76. If you use model.load(modelDir, modelName) then a null exception occurs. I think line PtModel line 76 should be   if (option!=null && options.containsKey("extraFiles")) {... ?

Thanks again!

**Comment by lanking520** [comment]
@macster110, please feel free to raise a PR to fix it :)
