### ISSUE TITLE
Build mxnet-native-cu102mkl for ppc64le architecture

### ISSUE THREAD

**Issue by lazystone** [awslabs/djl#33]
## Description
Right now there are builds of mxnet-native* for osx-x86_64 and linux-x86_64.

It would benefit DJL a lot if there will be a possibility of running it on IBM's Power servers(ppc64le).

### Will this change the current api? How?
No API changes.

### Who will benefit from this feature?
All who's using IBM's Power servers

## References
- https://www.ibm.com/downloads/cas/KDQRVQRR

**Comment by frankfliu** [comment]
@lazystone 
Thanks for filing this issue.

Currently MXNet doesn't officially support power PC (https://github.com/apache/incubator-mxnet/issues/15553). However you should be able to build mxnet from source: https://mxnet.apache.org/get_started/ubuntu_setup

Once you build your libmxnet.so file, you can use DJL to load your version of libmxnet.so for ppc: https://github.com/awslabs/djl/blob/master/docs/development/troubleshooting.md#4-how-to-run-djl-using-other-versions-of-mxnet
```
export MXNET_LIBRARY_PATH=/USER_MXNET_LIB_FOLDER
```

If you are willing to contribute to DJL with PPC mxnet and build mxnet for PPC, we can consider release mxnet-native for PPC in future release.

**Comment by lazystone** [comment]
Yeah, I see.

I'd like to contribute, but my knowledge about ML is very limited. We use python-based approach and for me that was a nightmare - solving python dependency hell is horrible, so I started to play with DJL to try to understand if we can build some parts using java.

Saying all this - we do have some power servers and that would be possible to discuss with the management to use those for building mxnet...

But. My advice. Even if somebody offers you to do that - don't do that from security point of view.

Binaries which you build and distribute must be built on hardware and infrastructure which you own - you don't want to distribute something that mines bitcoins(in the best case).

P.S: I'll try to build mxnet  and djl for ppc when/if I have time though - thanks for an instruction!

**Comment by zachgk** [comment]
We plan to wait until MXNet officially supports ppc64le before we add support for it in our DJL MXNet Engine. Please reopen this issue if MXNet begins to support it.
