### ISSUE TITLE
The equivalent mapping of various pytorch python parts in DJL

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [awslabs/djl#333]
By mapping I mean classes.
For example,torch.nn.Module,...Conv1d

What is the equivalent of it in djl.

Are there any direct mapping to it.
Say we have a python script that uses the pytorch lib,by importing it.

A one by one mapping does not seems to make sense since DJL supports many backend.
How does it work,the djl java backend is c pytorch which can be refer to cpp frontend or c library api.

However,pytorch seems to have those classes.https://pytorch.org/cppdocs/api/namespace_torch__nn.html
But how do we create and access them with djl?
Djl does not seem to have "Conv1d or Conv2d".How to represent it and feed it to the pytorch backend?

**Comment by lanking520** [comment]
DJL does have https://github.com/awslabs/djl/blob/master/model-zoo/src/main/java/ai/djl/basicmodelzoo/cv/classification/ResNetV1.java#L52 like PyTorch implementation. if you already have PyTorch pretrained model, you can convert it to TorchScript and load in DJL for inference. http://docs.djl.ai/docs/pytorch/how_to_convert_your_model_to_torchscript.html.

**Comment by zachgk** [comment]
There is mostly a 1:1 mapping between the concepts in pytorch and DJL. We use `Block` instead of pytorch's `Module`. The operations like convolutions can be found within the `ai.djl.nn` packages such as the convolutions in [ai.djl.nn.convolutional](https://javadoc.io/static/ai.djl/api/0.8.0/index.html?ai/djl/nn/convolutional/package-summary.html).

**Comment by xwaeaewcrhomesysplug** [comment]
Thanks,sorry did not check the convolution package.
With that it seems that we have two choice.
implement it from scratch with djl or train the model in python then use djl runtime.

zachgk,thank you for your clarifications.I shall note this down and make sure search it throughly next time.

However,it seems like using the trained model or TorchScript model does not gives access to the djl wide bankend selection.
(Actually,I think trained model can be loaded by djl java api,and use any backend right?While Torchscript is also one of the djl suppported model.)
I may be wrong,quite confused about the compatibility and processes required to port models or codes.

Last question,are there any tools you know of that can load a customized(Refers to not existed parts as of now)
Codes or pytorch python modules into djl or any backend?

I suppose it should be no.As A is not equal to B which is modified version of A.Thus need manual port.
I think I missunderstood the language agnostic meaning or something else.

Either way,if the answer for last question is no.Feel free to close this issue.
You may find a new question issue I create specifically for manually porting QPPWG.
Which probably heavily utilizes djl or whatever that needs to make it work.

**Comment by zachgk** [comment]
Right. If you use an imported TorchScript model, we use the PyTorch engine to load it into a special Block (`PtSymbolBlock`) and it can only be run run the PyTorch engine. If you were to create a model using DJL itself, it could be run using any DJL engine (note that some engines don't implement the full DJL specification and may not support all operations).

If you want to move models between backends, you could try looking into ONNX. ONNX is a standardized model encoding format and most backends have some integration with importing and exporting into it.

**Comment by frankfliu** [comment]
Feel free to re-open this issue if you have further questions.
