### ISSUE TITLE
parameter file not found but it exisits

### ISSUE THREAD

**Issue by IrisDinge** [awslabs/djl#339]
## Question
Hi
first, nice work and a bad question following from java freshman;(
 when i want to do object detection task for pikachu using pikachu-ssd-0002.params after
running TrainPikachu.java, it appeared bug that i cannot fix. 

i coded like this:

        Translator<Image, DetectedObjects> translator =
                SingleShotDetectionTranslator.builder()
                //.optRescaleSize(300, 300)
                //.addTransform(new Resize(300, 300))
                        .addTransform(new ToTensor())
                        .optSynsetArtifactName("file:///build/model/pikachu-ssd-0002.params")
                        .optThreshold(0.7f)
                        .build();

        Criteria<Image, DetectedObjects> criteria =
                Criteria.builder()
                        .optApplication(Application.CV.OBJECT_DETECTION)
                        .setTypes(Image.class, DetectedObjects.class)
                        .optModelUrls("file:///build/model/pikachu-ssd-0002.params")
                        .optTranslator(translator)
                        .build();

Besides, i referenced https://github.com/awslabs/djl/issues/220

Then,

> Task :examples:run FAILED
[WARN ] - Simple repository pointing to a non-archive file.
Exception in thread "main" java.io.IOException: Parameter file not found in: C:\Users\TM_DJ\djl\examples\build\model\pikachu-ssd-0002.params
        at ai.djl.mxnet.engine.MxModel.load(MxModel.java:98)
        at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:142)
        at ai.djl.repository.zoo.ModelZoo.loadModel(ModelZoo.java:162)
        at ai.djl.examples.inference.ObjectDetection.predict(ObjectDetection.java:87)
        at ai.djl.examples.inference.ObjectDetection.main(ObjectDetection.java:57)

FAILURE: Build failed with an exception.

i'm sure there is .params called pikachu-ssd-0002.params in this directory.
pls help, thk in advanced.

**Comment by frankfliu** [comment]
@IrisDinge 
A model usually has multiple files (.params and synset.txt etc.). The .optModelUrls(url) expects a folder or archive file.
When you specify a model Url, by default, DJL use the folder(or archieve file) name as model name, and looking for `model_name-xxxx.params` file in the folder. If you folder name are different from the model name, you can add `.optModelName()` to set the model name. or add querystring to the url: "file:///abc/?model_name=bla"

**Comment by IrisDinge** [comment]
@frankfliu 
Thk for ur kind reply;)

could u pls offer a template to demostrate how was a setblock like in Inference task?

`Exception in thread "main" java.io.FileNotFoundException: Symbol file not found: C:\Users\TM_DJ\djl\examples\build\model\pikachu-s
sd-symbol.json, please set block manually for imperative model.
`

**Comment by frankfliu** [comment]
You can refer to Pikachu example: https://github.com/awslabs/djl/blob/master/examples/src/main/java/ai/djl/examples/training/TrainPikachu.java#L101-L108

In the example, the trained block is slightly different from the block used for inference. If you want to use the same Block for inference you need override the default translator:

```
        SingleShotDetectionTranslator.Builder builder = SingleShotDetectionTranslator.builder()
                .addTransform(new ToTensor())
                .optSynset(Collections.singletonList("pikachu")) // there only one class in Pikachu SSD
                .optThreshold(0.7f);

        SingleShotDetectionTranslator translator = new SingleShotDetectionTranslator(builder) {

            @Override
            public NDList processInput(TranslatorContext ctx, Image input) {
                NDList list = super.processInput(ctx, input);
                NDArray array = list.get(0).expandDims(0);
                return new NDList(array);
            }

            @Override
            public DetectedObjects processOutput(TranslatorContext ctx, NDList list) {
                NDArray anchors = list.get(0);
                NDArray classPredictions = list.get(1).softmax(-1).transpose(0, 2, 1);
                NDArray boundingBoxPredictions = list.get(2);
                MultiBoxDetection multiBoxDetection =
                        MultiBoxDetection.builder().build();
                NDList detections =
                        multiBoxDetection.detection(
                                new NDList(
                                        classPredictions,
                                        boundingBoxPredictions,
                                        anchors));
                list = detections.singletonOrThrow().split(new long[]{1, 2}, 2);
                NDList output = new NDList(list.size());
                for (NDArray array : list) {
                    output.add(array.squeeze(0));
                }
                return super.processOutput(ctx, output);
            }

            @Override
            public Batchifier getBatchifier() {
                return null;
            }
        };

        Block block = getSsdTrainBlock(); // use the same trained block to load the model
        Criteria<Image, DetectedObjects> criteria = Criteria.builder()
                .optApplication(Application.CV.OBJECT_DETECTION)
                .setTypes(Image.class, DetectedObjects.class)
                .optBlock(block). // set the block in criteria
                .optModelPath(Paths.get(outputDir)) // load model from your folder
                .optModelName("pikachu-ssd") // specify the parameter file name
                .optTranslator(translator)
                .build();

        try (ZooModel<Image, DetectedObjects> model = ModelZoo.loadModel(criteria);
             Predictor<Image, DetectedObjects> predictor = model.newPredictor(translator)) {
            Image image = ImageFactory.getInstance().fromUrl(imageFile);
            DetectedObjects detectedObjects = predictor.predict(image);
            image.drawBoundingBoxes(detectedObjects);
            Path out = Paths.get(outputDir).resolve("pikachu_output.png");
            image.save(Files.newOutputStream(out), "png");
            // return number of pikachu detected
            return detectedObjects.getNumberOfObjects();
        }
```

**Comment by IrisDinge** [comment]
@frankfliu 

get√, thks again;)
