### ISSUE TITLE
Good visualization

### ISSUE THREAD

**Issue by jSaso** [awslabs/djl#36]
## Description
Visual representation of neural network, model score, parameter ratios, learning parameter,...
All aspect of neural network parameter that can be visualized in timely manner (iteration).

### Will this change the current api? How?
Present already provided parameters from network, **visually**.

### Who will benefit from this feature?
Everybody, with visualization you can quickly see network over fitting, under fitting, network behavior. It makes easier to determine right network parameter and right network architecture.

## References
Good example of very good visualization (web based, local or remote): https://deeplearning4j.konduit.ai/tuning-and-training/visualization

**Comment by keerthanvasist** [comment]
Thank you for creating this issue @jSaso. We already have one more issue tracking visualization [here``](https://github.com/awslabs/djl/issues/34). I will close this issue.
