### ISSUE TITLE
ai.djl:api:0.8.0 the lower version of JNA caused mxnet error report to not find the engine

### ISSUE THREAD

**Issue by Jzow** [awslabs/djl#373]
## Description
A known problem is reported. When djl version 0.8.0 is used, if the mxnet of the local environment or the cached mxnet is loaded correctly, if the JNA version is too low, the mxnet engine cannot be loaded, and an error prompts that the mxnet engine does not exist.

### Will this change the current api? How?
**I personally feel that JNA in djl 0.8.0 should be upgraded from 4.5.2 to 5.3.0**
`<dependency>`
	`<groupId>net.java.dev.jna</groupId>`
	`<artifactId>jna</artifactId>`
	`<version>5.3.0</version>`
`</dependency>`

### Who will benefit from this enhancement?
All windows users using djl0.8.0

## References
https://github.com/awslabs/djl/blob/master/gradle.properties#L25

**Comment by Jzow** [comment]
If I don't upgrade, I need to import Maven JNA-5.3.0.jar myself ，I think this is a bad experience. It is reasonable to say that the API package should load the supported JNA instead of the wrong low version of JNA

**Comment by frankfliu** [comment]
ai.djl:api:0.8.0 dependens on jna-5.3.0, see: https://search.maven.org/artifact/ai.djl/api/0.8.0/jar

Lookes like you configuration somehow included a different version of JNA.

**Comment by Jzow** [comment]
@frankfliu  I have seen the API jar of 0.8.0, which may be related to my configuration. Thank you for your timely reply
