### ISSUE TITLE
Custom dataset for object detection

### ISSUE THREAD

**Issue by IrisDinge** [awslabs/djl#374]
## Question
Hi, questions coming again!

case: i want to train my custom dataset which contains only one class and every image contains only one target. That's much similar with PikachuObjectDetection. 

what i have done: i finished inference part of ObjectDetectionPikachu using pre-trained model which producted by running TrainPikachu. That works perfectly;)

Q1: after checking doc, i would like to confirm, is ImageFolder only used for classification task?
Q2: i'm trying use CSVDataset and convert format to CSV like:

filename,width,height,class,xmin,ymin,xmax,ymax
000009a592af8d72a4ea5615ed8cc020f9df32.jpg,416,416,mouse,171,225,201,266
000240rf.ae0a7e8758c02b05903e2ae793ef8e66.jpg,416,416,mouse,45,235,73,273

Q3: could u pls offer templates for doing object detection task using custom dataset since available instances all for classification.

Thk in advanced;p

**Comment by frankfliu** [comment]
@IrisDinge 
ObjectDetection dataset need two types of data:
- Image file
- bounding box metadata for each image

You can implement your own dataset by use either of ImageFolder or CsvDataset as base class.
If you use ImageFolder as base class, you can inherit Image processing part, but you have to override label with bounding information.
If you use CsvDataset as base class, it makes mapping image file to label easier, but you have to implement Featurizer to processing image to NDArray.
