### ISSUE TITLE
Why Gradle but not maven?

### ISSUE THREAD

**Issue by SidneyLann** [awslabs/djl#379]
Maven is more common in backend java development.

**Comment by SidneyLann** [comment]
Deeplearing4j, Java-TF and more java DL frameworks are using maven.

**Comment by frankfliu** [comment]
See: https://gradle.org/maven-vs-gradle/

1. From dependency management point of view, gradle can do whatever maven can do
2. Gradle build script is essentially Groovy code, it's more flexible, you can write plugin on the fly
3. Gradle can invoke maven or ant tasks if needed

**Comment by SidneyLann** [comment]
Maven is more common in backend java development.

**Comment by frankfliu** [comment]
Gradle almost can do whatever maven can and maven is old school.

The major reason we choose gradle is:
1. We have many custom build rule and dynamic plugin, it's very hard to achieve by maven, unless we create our own maven plugin and publish them.
2. Gradle has excellent incremental build support which reduce build time. This is huge gain for daily development.
