### ISSUE TITLE
Possible NDArray Splicing Bug

### ISSUE THREAD

**Issue by gatordevin** [awslabs/djl#383]
Hey all. I may have encountered an issue with NDIndex splicing of NDArrays when using splice increments.

Exception in thread "main" ai.djl.engine.EngineException: MXNet engine call failed: MXNetError: Check failed: src.Size() == dst->Size() (3 vs. 2) : Cannot reshape array of size 3 into shape [1,2]

```
NDManager manager = NDManager.newBaseManager();
NDArray targetBox = manager.ones(new Shape(1, 5));
targetBox.set(new NDIndex(":, 0::2"), array -> array.mul(-1).add(1));
```
Code to reproduce the error is shown above. If one of the lines is changed to the following it works as expected with no issues. Splicing could be running too far off the array so the size is different but I am not sure.
targetBox.set(new NDIndex(":, 1::2"), array -> array.mul(-1).add(1));

**Comment by lanking520** [comment]
Can you provide the corresponding numpy behavior if you would like to do something similar? @zachgk

**Comment by stu1130** [comment]
I can't find similar numpy function that do the same thing. The closest one is
```
a = np.ones((1,5))
a[:,0::2] *= -1
a[:,0::2] += 1
```
The error is from https://github.com/awslabs/djl/blob/ea501c9bdce9695c973beb32439bb90f135730ed/mxnet/mxnet-engine/src/main/java/ai/djl/mxnet/engine/MxNDArrayIndexer.java#L75. @zachgk Could you take a look at set method?
