### ISSUE TITLE
Training as listener

### ISSUE THREAD

**Issue by jSaso** [awslabs/djl#39]
## Description
Implement training as listener, so we can subscribe to training listener. We need more information to each of the provided listeners:
- normalize/de-normalize class (separate feature request)
- train data set
- test data set
- last best model
- last best model score

In this way we can do whatever we want: 
- calculate prediction from best model data set with our test data set, 
- de-normalize test data set and compare with de-normalized predicted data set
- create our own evaluation with real vs. predicted data
- create evaluation on train data
- create evaluation on test data
- on complete we want latest best model (with best score), the sam onEpoch listener
- on completion listener we can save training model for later use - transfer learning
- combined with early stop configuration - so we can check which termination condition stop training (separate feature request)

### Will this change the current api? How?
Yes, training should be implemented as listener, so we can subscribe to listener.
Interface should have:
**onStart
onEpoch
onCompletion**

### Who will benefit from this feature?
Everybody, subscribe to the listener and we have all information we need

## References
Reference implementation: https://github.com/eclipse/deeplearning4j/blob/b5f0ec072f3fd0da566e32f82c0e43ca36553f39/deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/earlystopping/listener/EarlyStoppingListener.java
but we need more information inside each of onStart, onEpoch and onCompletion method - see above

**Comment by keerthanvasist** [comment]
Thank you for creating this issue @jSaso.

**Comment by zachgk** [comment]
@jSaso We have a [TrainingListener](https://github.com/awslabs/djl/blob/master/api/src/main/java/ai/djl/training/listener/TrainingListener.java) class that was added in 0.3.0. Does this look like it will work or do you see any issues with it?

**Comment by zachgk** [comment]
Since we have this feature and there is no response, I will close the issue for now. Please feel free to reopen or open a new issue
