### ISSUE TITLE
Freeze a block for training

### ISSUE THREAD

**Issue by efrancis59** [awslabs/djl#392]
## Question
Is there a way to freeze a block for transfer learning ? something similar to Keras **trainable = False** ?

**Comment by lanking520** [comment]
Currently, DJL is hard to achieve that, but it is possible to use a Predictor from the block in your application. You can checkout my use case from the Amazon Review https://github.com/awslabs/djl/blob/master/jupyter/rank_classification_using_BERT_on_Amazon_Review.ipynb . The wordEmbedding is a BERT layer not used for training.

**Comment by efrancis59** [comment]
Thanks
