### ISSUE TITLE
Cannot build without testing

### ISSUE THREAD

**Issue by tribbloid** [awslabs/djl#4]
## Description
To quickly compile the artifact sometimes I want to skip tests while building, but this is prohibited in by the gradle task ':integration:jacocoTestReport'.

### Expected Behavior
The project should be able to compile without any test

### Error Message
```
$ ./gradlew build -x test

> Configure project :basicdataset
GPU 0: GeForce RTX 2070 (UUID: GPU-ccda497c-7a55-7df7-49ad-b68e31743286)

> Configure project :examples
GPU 0: GeForce RTX 2070 (UUID: GPU-ccda497c-7a55-7df7-49ad-b68e31743286)

> Configure project :integration
GPU 0: GeForce RTX 2070 (UUID: GPU-ccda497c-7a55-7df7-49ad-b68e31743286)

> Configure project :mxnet:mxnet-engine
[WARN ] Header file has been changed in open source project: mxnet/c_api.h.

> Task :integration:jacocoTestReport FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integration:jacocoTestReport'.
> Unable to read execution data file /home/peng/git-release/djl/integration/build/jacoco/test.exec

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 4s
66 actionable tasks: 32 executed, 34 up-to-date

```

## How to Reproduce?
just running `./gradlew build -x test` under project

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1. `./gradlew build -x test`

## Environment Info
Please provide the following information:

* Operating System: Ubuntu 18.04 LTS
* Hardware(Machine) Info: 
* CUDA version(if available): 10.0
* Deep Java Library version: 0.2.0-SNAPSHOT
* MXNet version: haven't installed

**Comment by frankfliu** [comment]
@tribbloid 
Thanks for reporting this issue. I created a commit to address this issue: https://github.com/awslabs/djl/commit/20cb68dea7511bfaf080048b774ce63ecfa35f2b

Feel free to reopen this issue if you still see it.

**Comment by tribbloid** [comment]
roger that, thanks a lot!
