### ISSUE TITLE
How to load pytorch model file directly?

### ISSUE THREAD

**Issue by csxiang18** [awslabs/djl#408]
## Question

I've already export a pytorch model into a pt file. For example: `model/my_model.pt`, this directory is under the resources directory.

When I want to load this model, I use this way: 
    
    String modelPath = "model";
    URI modelUri = classLoader.getResource(modelPath).toURI();
    Path modelDir = Paths.get(modelUri);
    Model ptModel = Model.newInstance("my_model", Device.cpu());
    ptModel.load(modelDir);

Is there any other way that I could use like this, load the pt file directly: `ptModel.load("model/my_model.pt")`?

**Comment by lanking520** [comment]
Starting from 0.9.0, you can load from modelDir from ModelZoo:

https://github.com/awslabs/djl/blob/master/api/src/main/java/ai/djl/repository/zoo/Criteria.java#L343

You can refer to our doc here: http://docs.djl.ai/docs/load_model.html. There are many ways to load: like http, hdfs, s3 or simply local file paths are all supported.

If you are looking for loading the model directly, you can do the followings:
```
ptModel.load(Paths.get("model"), "my_model");
```
Which is very similar when you create new instance of the model. There seemed to be no way to bypass setting model name from the `Model` API. But doable if you try to load from the `ZooModel` api

**Comment by frankfliu** [comment]
@csxiang18 If you put model in resource file, most likely you will pack the model in a jar file when deploy it.

I this case, you have to use jar:// url to load the model: http://docs.djl.ai/docs/load_model.html#load-model-from-a-url

**Comment by csxiang18** [comment]
Thanks for answering this question, as it's my first time to try DJL, so may some API I do not use very correctly. In fact I want to pack the model in the jar file as a lib to deploy so that others could use this. Maybe I could state the problem more clearly. So here are some questions:
@frankfliu my model is a self-defined model, for-example, a 3 layer dnn, no existing model in ModelZoo. I follow this doc: [Export Pytorch Model](https://djl.ai/docs/pytorch/how_to_convert_your_model_to_torchscript.html) to export the model as a my_model.pt file. Then I put the model file under the resource directory so that I could use getResouce to load the model. 
```
ClassLoader classLoader = LoadModelTest.class.getClassLoader();
String modelPath = "model";
URI modelUri = classLoader.getResource(modelPath).toURI();
```
Then I want to provide a lib, and write like this, so others could use the function like this: `LoadModelTest.predict(features)`

```
package com.test;

public class LoadModelTest {
    public static Model model;
    static {
        try {
            loadModel();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public static void main(String[] args) {
        float[] features = new float[199];
        float[] output = predict(features);
        System.out.println(output[0]);
    }

    public static float[] predict(float[] features) {
        try {
            Predictor<float[], float[]> predictor = model.newPredictor(new FloatToFloatTranslator());
            return predictor.predict(features);

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    public static void loadModel() throws Exception {
        ClassLoader classLoader = LoadModelTest.class.getClassLoader();
        String modelPath = "model";
        URI modelUri = classLoader.getResource(modelPath).toURI();
        Path modelDir = Paths.get(modelUri);
        model = Model.newInstance("my_model", Device.cpu());
        model.load(modelDir);
    }

    private static final class FloatToFloatTranslator implements Translator<float[], float[]> {

        @Override
        public Batchifier getBatchifier() {
            return Batchifier.STACK;
        }

        @Override
        public float[] processOutput(TranslatorContext translatorContext, NDList ndList) throws Exception {
            NDArray tempArray = ndList.get(0);
            return tempArray.toFloatArray();
        }

        @Override
        public NDList processInput(TranslatorContext translatorContext, float[] features) throws Exception {
            NDManager manager = translatorContext.getNDManager();
            return new NDList(manager.create(features));
        }
    }
}

```

The above script works fine when I wrote the lib. However, when I package this lib, it could not load the model correctly. As `my_model.pt` is in the Jar file and Paths could not parse the model directory correctly. So how could I solve this?

**Comment by frankfliu** [comment]
@csxiang18 
The PyTorch engine can only load model from file system. So the `loadModel()` can only take `Path`

If you package your classes in a jar file, the URL returned from `classLoader.getResource` is a special URL that only supported by JVM something like: "jar://your.jar!/model". `Path modelDir = Paths.get(modelUri);` won't give you a correct file system path, so load model will fail since Path is not valid.

To resolve this issue, you can use Criteria API to load your model as I posted earlier. The api can take care both jar and unjared case.
