### ISSUE TITLE
DJL PyTorch has a spike in latency during the long run

### ISSUE THREAD

**Issue by lanking520** [awslabs/djl#416]
## Question

IHAC asking for DJL issue with PyTorch inference run. His model is a general PyTorch CV model and loading in k8s with RPC calls. The general latency is around 30ms, however, around 8/1000 cases he saw the latency get up to hundred to thoudsands of ms. There is no anomaly in the system or GC behavior. There is also no reboot on the server side. He already elminate the cold-start run time.

After he switch the model from PyTorch to TensorFlow, the problem just gone. Not sure what could be the root cause.

**Comment by stu1130** [comment]
I think we can only investigate the issue if we have reproducible script. Suspect those 8 cases are running when GC kicks in.

**Comment by lanking520** [comment]
Cloes this issue for now since it is not clear how to reproduce...
