### ISSUE TITLE
BERT Inference Demo using pytorch

### ISSUE THREAD

**Issue by HerbJiang** [awslabs/djl#42]
## Description
Could you provide an jupyter notebook sample for BERT inference demo using pytorch?
Just like current [BERT inference demo using mxnet](https://github.com/awslabs/djl/blob/master/jupyter/BERTQA.ipynb) 

### Who will benefit from this feature?
People already pretrained / fine-tuned their own model using pytorch can easily migrate into this project.

Thanks.

**Comment by lanking520** [comment]
Currently, we can only do PyTorch Traced model. There are a few examples that may allow us import in DJL:

[TorchHub example](https://pytorch.org/hub/pytorch_fairseq_roberta/)

[thirdparty popular BERT pretrained model](https://github.com/huggingface/transformers/blob/master/docs/source/torchscript.rst)

If you are interested, please feel free to search for a BERT pretrained model. You can tested it out using DJL with Jupyter Notebook and help us grow the model zoo! :)

**Comment by stu1130** [comment]
Hey @HerbJiang,
I have uploaded the HuggingFace Bert Question Answering Model. You can try it out with
```
git clone https://github.com/awslabs/djl.git
cd djl
./gradlew :examples:run -Dmain=ai.djl.examples.inference.BertQaInference -Dai.djl.default_engine=PyTorch
```
The code is [here].(https://github.com/awslabs/djl/blob/master/examples/src/main/java/ai/djl/examples/inference/BertQaInference.java)
I am working on the jupyter notebook, stay tuned

**Comment by stu1130** [comment]
@HerbJiang 
I completed the pytorch BERT QA [jupyter notebook](https://github.com/awslabs/djl/blob/master/jupyter/pytorch/load_your_own_pytorch_bert.ipynb).
You can use it with your pretrained BERT along with vocabulary from HuggingFace.
Remember to convert your model to TorchScript.
If you need any help, please let us know.

**Comment by stu1130** [comment]
feel free to open the issue, if you have any question
