### ISSUE TITLE
"Create our first networt" incomplete code snippet 

### ISSUE THREAD

**Issue by jesuino** [awslabs/djl#482]
In this tutorial there's an incomplete code snippet at the end of the tutorial, there's a lost "block" line, which I don't know what to do, should I just delete and ignore it?

https://github.com/awslabs/djl/blob/master/jupyter/tutorial/01_create_your_first_network.ipynb

This is also weird in the website: 

https://docs.djl.ai/jupyter/tutorial/01_create_your_first_network.html

Thanks!

**Comment by keerthanvasist** [comment]
That line is only required in the notebook to show the output. You can remove it.

**Comment by keerthanvasist** [comment]
Closing the issue. Please reopen ticket if you have encounter any issue.

**Comment by frankfliu** [comment]
> That line is only required in the notebook to show the output. You can remove it.

The line "block" is jupyter notebook specific shortcut for: System.out.println(block);

**Comment by jesuino** [comment]
thanks @frankfliu and @keerthanvasist
