### ISSUE TITLE
Pytorch model training does not create .pt file upon model.save()

### ISSUE THREAD

**Issue by barkeldiho** [awslabs/djl#483]
## Description
Currently I am developing a forecasting model with the PyTorch engine and DJL. As dependency I utilize:
```
<dependency>
    <groupId>ai.djl.spring</groupId>
    <artifactId>djl-spring-boot-starter-pytorch-auto</artifactId>
    <version>0.7</version>
</dependency>
```
So far everything is running smoothly, I can see the progress of the training progress etc. The related code fragment is:

```java
final Model model = Model.newInstance(trainingModel.getInstanceName());
// Results in a SequentialBlock...
model.setBlock(this.getMlpBlockForTrainingModel(trainingModel));
final Trainer trainer = this.getConfiguredTrainer(model, trainingModel);

int epoch = 5;
for (int i = 0; i < epoch; ++i) {
    try {
        for (Batch batch : trainer.iterateDataset(dataset)) {
            EasyTrain.trainBatch(trainer, batch);
            trainer.step();
            batch.close();
        }
    } catch (Exception e) {
        throw new RuntimeException("Error during model training in epoch.");
    }
    trainer.notifyListeners(listener -> listener.onEpoch(trainer));
}

model.setProperty("Item", itemIdentifier);
model.setProperty("Epoch", String.valueOf(epoch));
model.setProperty("Timestamp", ZonedDateTime.now().toString());
```

Nontheless, upon saving the trained model:
```java
final Path modelDir = Paths.get(MLP_DIRECTORY + "/" + RandomStringUtils.randomAlphanumeric(5));
model.save(modelDir, instanceName);
```

I only find a **.params** file and no **.pt** file. Obviously it is rather problematic to load a model without, well a model. Since I am pretty new to the whole topic I am wondering if I miss anything. The training process seems to finish as expected and I dont get any exceptions.

### Expected Behavior
model.save() should create a .pt file at the specified path.

### Error Message
No displayed error.

Id be happy to receive any information on how to proceed in this case and whether it is a bug somewhere in DJL or PyTorch or if I am missing something obvious.

Much appreciated.
Take care.

**Comment by frankfliu** [comment]
If you trained your model in DJL, the model will be saved in DJL model format (.params file). The DJL model is portable, it can be loaded with by both MXNet or PyTorch engine.

Currently, we don't support export DJL model into Engine specific model. We won't be able to export to .pt format in current version.

**Comment by barkeldiho** [comment]
Thank u for your reply and the information.

Ok, so far so good :) But when I call model.load() it gives me the error „Cannot find .pt file...“. I would expect it to simply load a model from .params file, wouldnt I?

Anyhow, that means the expected procedure is: save() -> params file -> convert to pt file -> load()?

Thanks for your help!
Best

**Comment by frankfliu** [comment]
You should be able to load your saved .params model back.
Since you trained your model with imperative blocks, the .params only works together with your Block.
What you need to do is set the Block when you load your model:

```
Criteria<Image, Classifications> criteria = Criteria.builder()
                .setTypes(Image.class, Classifications.class) // define input and output
                .optModelPath(...)
                .optBlock(block)
                .optTranslator(your translator)
                .build();
```

**Comment by barkeldiho** [comment]
Works. Thanks for the help.
