### ISSUE TITLE
How to inferrence with more than 1 arguments

### ISSUE THREAD

**Issue by jinlong-hao** [awslabs/djl#485]
## Question

I have trainned and export a model from the pytorch tutorial(https://pytorch.org/tutorials/beginner/text_sentiment_ngrams_tutorial.html), and the model definition is:

~~~python
import torch.nn as nn
import torch.nn.functional as F
class TextSentiment(nn.Module):
    def __init__(self, vocab_size, embed_dim, num_class):
        super().__init__()
        self.embedding = nn.EmbeddingBag(vocab_size, embed_dim, sparse=True)
        self.fc = nn.Linear(embed_dim, num_class)
        self.init_weights()

    def init_weights(self):
        initrange = 0.5
        self.embedding.weight.data.uniform_(-initrange, initrange)
        self.fc.weight.data.uniform_(-initrange, initrange)
        self.fc.bias.data.zero_()

    def forward(self, text, offsets):
        embedded = self.embedding(text, offsets)
        return self.fc(embedded)
~~~

but there are 2 paremeter in forward method, but the Predictor.predict in djl  only have one parameter.
how can i pass both input and offsets to the predict method?

**Comment by zachgk** [comment]
When you build the NDList input to the model, you can have it with two NDArrays: one for the text and one for the offsets. The Predictor exists to convert between the numeric NDArrays and convenient Java classes. So, you could create a simple POJO or record to pass both the text and offset into the predictor and then the predictor preprocessing would convert them into the two NDArrays for your model.

**Comment by jinlong-hao** [comment]
@zachgk If I create a pojo like below, How  can I implement the Translator?

~~~java
public class MyPOJO{
    private NDArray text;
    private NDArray offsets;

   // getter and setters
   // ....
}
~~~

**Comment by stu1130** [comment]
our input is a NDList which can takes multiple NDArray
```
// assume you have created text and offsets NDArray
NDList inputs = new NDList(text, offsets);
predict.predict(inputs);
```

**Comment by zachgk** [comment]
It would be:

```java
class MyTranslator {
  NDList processInput(TranslatorContext ctx, MyPOJO input) {
    return new NDList(input.getText(), input.getOffsets());
  }
}
```

Usually, you want to create the text and offsets NDArrays inside of the processInput method though. Then, you can use the `ctx`'s `NDManager` which will automatically take care of the memory for you.

**Comment by jinlong-hao** [comment]
@zachgk @stu1130 Thanks very much!  the inference works all right!

**Comment by jinlong-hao** [comment]
@zachgk @stu1130 Thanks very much!  the inference works all right!
