### ISSUE TITLE
A more clear documentation to distinguish those optional .optX() and those compulsory .setX() for Criteria.Builder<I,O> and other builders

### ISSUE THREAD

**Issue by billweasley** [awslabs/djl#486]
## Description

From [JavaDoc of Criteria.Builder](https://javadoc.io/doc/ai.djl/api/latest/ai/djl/repository/zoo/Criteria.Builder.html) and [JavaDoc of ResNetV1.Builder](https://javadoc.io/static/ai.djl/model-zoo/0.3.0/ai/djl/basicmodelzoo/cv/classification/ResNetV1.Builder.html), one could guess that the naming of builders' methods in DJL world follow the following rules: .optX() methods are optional settings, and .setX() methods are compulsory ones, which needed to be invoked before calling .build().

I might do miss something, but in the tutorials (e.g. [README](https://github.com/awslabs/djl/blob/master/README.md), and [train_cifar10_resnet.md](https://github.com/awslabs/djl/blob/master/examples/docs/train_cifar10_resnet.md)), there is no clear indication of this naming design. People may have trouble to run their model when they forget to set a compulsory field, and have to find the JavaDoc to find why it is in that case (and probably still need to have some guesses because those JavaDoc does not really mention this convention in its class description).

Will this change the current api? How?

None major. Trivial documentation improvements.

Who will benefit from this enhancement?
Novice for this project.

## References
- list reference and related literature
- list known implementations

**Comment by lanking520** [comment]
Please feel free to add some Javadoc in the API to make it clear.

**Comment by frankfliu** [comment]
The `.optXXX()` behavior is documented in: http://docs.djl.ai/docs/load_model.html#criteria-class

I agree, we should add to javadoc as well.
