### ISSUE TITLE
Support for recent PyTorch version

### ISSUE THREAD

**Issue by waldekkot** [awslabs/djl#506]
Hi,

I would have a kind request to release DJL version supporting the latest PyTorch version (at the moment this is Pytorch 1.7.1). Especially important is the built in support for cuDNN 8.0.5 in the context of RTX 30xx GPUs...

Thanks :-) !

BTW: djl is a nice piece of work - thank you guys !

**Comment by frankfliu** [comment]
@waldekkot pytorch 1.7.1 is published to maven central. It's currently not included in 0.9.0 bom, you have need manually specify 1.7.1 to use it.

**Comment by waldekkot** [comment]
Great ! I have just updated my project to use pytorch-native-cu110 1.7.1 on Windows (and the cpu version 1.7.1 on Linux) and so far it has been working fine 👍 

I know it is not easy - and I appreciate your work a lot - but maybe you guys could come up with some solution to keep the versions of the "underlying" libraries (like PyTorch and CUDA) more frequently synchronized with the recent versions ? 

Thanks a million again :-)
