### ISSUE TITLE
specify which gpu in training process

### ISSUE THREAD

**Issue by IrisDinge** [awslabs/djl#507]
## Description
specify which gpu in inference, no problem
However, during training, it needs to do some extra setting 

### Expected Behavior
run training process in expected gpu

## How to Reproduce?
with help of @Jzow, in training.TrainPikachu.java have tried the following code:

    public static TrainingResult runExample(String[] args) throws IOException, TranslateException {
        Arguments arguments = Arguments.parseArgs(args);
        if (arguments == null) {
            return null;
        }

        try (Model model = Model.newInstance("pikachu-ssd")) {
            model.setBlock(getSsdTrainBlock());
            RandomAccessDataset trainingSet = getDataset(Dataset.Usage.TRAIN, arguments);
            RandomAccessDataset validateSet = getDataset(Dataset.Usage.TEST, arguments);
            Device[] devices= new Device[]{Device.gpu(1)};

            DefaultTrainingConfig config = setupTrainingConfig(arguments);

            config.optDevices(devices);
            try (Trainer trainer = model.newTrainer(config)) {
                trainer.setMetrics(new Metrics());

                Shape inputShape = new Shape(arguments.getBatchSize(), 3, 256, 256);
                trainer.initialize(inputShape);

                EasyTrain.fit(trainer, arguments.getEpoch(), trainingSet, validateSet);

                return trainer.getTrainingResult();
            }
        }
    }

then, it works well as we chatted about in wechat group;)

**Comment by frankfliu** [comment]
@IrisDinge By default, DJL will use all GPUs for training, you can limit number of GPUs of select specific GPU by:

```
config.optDevices(Device.getDevices(1));
```

If you specified GPU, and it worked then this seems expected behavior

**Comment by lanking520** [comment]
@frankfliu It seemed to be a bug if you set `optDevice(Device.gpu(1))`, both GPU 0 and GPU 1 are used for training. Shouldn't this be setting single GPU?

**Comment by frankfliu** [comment]
We don't have API `optDevice(Device device)` in `DefaultTrainingConfig`, we only have `optDevices(Device[] devices)`
The behavior is as design, and I just verified it will only use one device if you limit the GPUs.

I think you might get confused about `RandomAccessDataset.optDevice(Device device)` API. the device to load the dataset is different from training devices. setting device for dataset won't limit the device for training.

Feel free to reopen this issue if you have further questions.
