### ISSUE TITLE
Load Deep Learning engine from dynamic classloader

### ISSUE THREAD

**Issue by carlosuc3m** [awslabs/djl#523]
## Question
Hello, 
I am designing an application that runs inside a program (ImageJ/Fiji) to deploy Deep Learning models. This program loads the .jar libraries dinamically after starting the application with a custom classloader. I have realised thar in order to load the EngineProvider.class service, djl uses the Thread contextClassLoader. Is there an workaround to start the Deep Learning Engine using a custom ClassLoader?
Here is the line where my problem appears:
https://github.com/awslabs/djl/blob/79fa9ac1e44326e2a6548ddde003f055ff35e4c1/api/src/main/java/ai/djl/engine/Engine.java#L56

`ServiceLoader<EngineProvider> loaders = ServiceLoader.load(EngineProvider.class);` 
loads the Thread ContexClassLoader, however with 
`ServiceLoader<EngineProvider> loaders = ServiceLoader.load(EngineProvider.class, CustomClassLoader);` 
we can use our own ClassLoader.
Regards and thank you for your time,
Carlos

**Comment by frankfliu** [comment]
@carlosuc3m 
What preventing you set the ContextClassLoader?
```
Thread.currentThread().setContextClassLoader(CustomClassLoader);
```

I created a PR to address your issue, you can manually initialize the Engine:
```
Engine.initEngine(CustomClassLoader);
```
This solution has 2 drawback:
1. You will see loading engine failed when Engine class is loaded
2. You must call Engine.initEngine() before any other DJL code executing.

Please try it out and let me know if this works for you.

I would prefer not merge this PR if setContextClassLoader() works for you. Please let me know your test result.

**Comment by carlosuc3m** [comment]
Your solution works fine thanks!
With `Thread.currentThread().setContextClassLoader(CustomClassLoader);` it should be enough :)
