### ISSUE TITLE
Bug when trying to load multiple engines in DJL

### ISSUE THREAD

**Issue by roywei** [awslabs/djl#57]
There are a few bugs in DJL right now when you try to use multiple engines.

For example if we use MXNet and TensorFlow engine together. If I set -Dai.djl.default_engine=MXNet, and call a TfEngine or TfModelZoo method, MxEngine and MxModelZoo is actually returned.

1) `TfEngine.getInstance()` will return Default Engine instead of TfEngine.

2) `TfModelZoo.RESNET.loadModel()` will return MxModel.RESNET if default engine is MXNet, will return PyModel.RESNET if default engine is Pytorch. But user already specified to use TfModelZoo

3) In `Criteria.builder()` the `.optEngine("TensorFlow")` option is not used by ModelZoo during loading model.

Right now the 2 ways to work with multiple engines are:

1) manually switch engine by setting system property `ai.djl.default_engine` back and forth
2) use `newInstance` with engineName will return the correct implementation under that engine:
`Model tfModel = Model.newInstance(Device.defaultDevice(), "TensorFlow")`

**Comment by roywei** [comment]
cc @jonathan016 @frankfliu

**Comment by roywei** [comment]
@JonTanS

**Comment by JonTanS** [comment]
Fixed and merged, reference commit id: a8c4bfc885a3cb39d333d3487a4f64e4fd2ac898
