### ISSUE TITLE
DJL training on CPU is much slower on python

### ISSUE THREAD

**Issue by lanking520** [awslabs/djl#621]
## Question

On behalf of the author. Just open the issue here. I built a simple NN with 60k data. Training on PyTorch cost around 273s however 3h 2min on DJL. Just wondering if any parts I did is wrong. Help is appreciated. 

File is attached here.
[issue.zip](https://github.com/awslabs/djl/files/5945817/issue.zip)

The above file includes python and Java code and some fake sample data.

**Comment by stu1130** [comment]
I took a look into the code. A few of comments.
Python script
* you don't need Variable. PyTorch merge Tensor & Variable. Whenever you need Variable, just call tensor. requires_grad().
```
# you don't create dataset with Variable as parameters are the one that need gradient
# when doing training, you are optimizing the parameters instead of dataset
x_data = Variable(torch.tensor(TrainData).float(), volatile = True)
```
To do a fair comparison 
1. add a dataloader and TensorDataset. As a result, both Java and Python fetch 6000 items and construct a huge batch with size 6000. Now the python just skip small dataset construction DJL do which takes time.
2. add the optimzier.step in the end of dataloader iteration
```
# the code you need to add
dataset = TensorDataset(x_data, y_label)
loader = DataLoader(dataset, batch_size=6000, shuffle=False)

for k in range(i):
        optimizer.zero_grad()
        for data, labels in loader:
            out = model(data)
            loss = loss_fuc(out, labels)
            loss.backward()
            optimizer.step()
```

Java script
1. you don't need the batchFlatten as first layer 

After the above change is made, the performance is still 3, 4 time slower than Python. I found the data loader is the bottleneck by following experiment.
```
# python
for _ in range(100000):
    data = x_data[100]
# java
for(int epoch = 1; epoch <= numEpoch; epoch++) {
    for(Batch batch : mytrainer.iterateDataset(dataset_train)) {
	;
    }
}
```
PyTorch python implements __getitem__ in pure C++ while in Java we do lots of preprocessing before calling slice op. I will try to create another special JNI call to work around it

**Comment by shuli0721** [comment]
Thanks for correcting.
I was so careless in providing code and data to lanking520 that I missed optimizer.step(). You really made me discover that I need to deepen my understanding of models as a beginner.

**Comment by shuli0721** [comment]
There is another question, does this phenomenon also exist in spark clusters under Linux environment?

**Comment by stu1130** [comment]
@shuli0721 I created a PR to boost the data loading https://github.com/awslabs/djl/pull/638

**Comment by stu1130** [comment]
@shuli0721 The PR has been merged. You shouldn't see much difference now.

**Comment by shuli0721** [comment]
@stu1130  WOW  You guys solve problems so quickly.  Hope I can do the same day. 
I will fix my code.
 And happy Spring festival to all your team members. 🥟春节快乐！

**Comment by lanking520** [comment]
@shuli0721 close this issue for now since there are no additional issues. Please feel free to reopen if you have any more concerns :) Happy Lunar New Year!
