### ISSUE TITLE
Find saved model in subdirectory of downloaded .zip

### ISSUE THREAD

**Issue by murphye** [awslabs/djl#66]
## Description
When I specify a model contained in a `.zip` such as:
```
-Dai.djl.repository.zoo.location=https://djl-tensorflow-javacpp.s3.amazonaws.com/tensorflow-models/covid-19/saved_model.zip
```

This is out output of the extraction:
```
% ls /Users/ermurphy/.djl.ai/cache/repo/model/undefined/ai/djl/localmodelzoo/9cd10ffd7f1adba3a00d0425403b69f7
saved_model
```

Notice a subdirectory of `saved_model` is present. This is where the model files reside.

```
% ls /Users/ermurphy/.djl.ai/cache/repo/model/undefined/ai/djl/localmodelzoo/9cd10ffd7f1adba3a00d0425403b69f7/saved_model 
assets          saved_model.pb  variables
```

Here is the output when running the model from this `.zip`:

```
org.tensorflow.exceptions.TensorFlowException: Could not find SavedModel .pb or .pbtxt at supplied export directory path: /Users/ermurphy/.djl.ai/cache/repo/model/undefined/ai/djl/localmodelzoo/9cd10ffd7f1adba3a00d0425403b69f7
```

This results in an error because it's looking in the parent directory, and not the `saved_model` directory. See how `saved_model` is missing from the path from the `TensorFlowException`.

### Expected Behavior

There should be a way to specify a subdirectory for where the model files reside from a `.zip`. It cannot be expected that they will be in the parent directory. The DJL Java code might also search the subdirectories first to find the `.pb` before giving a path to TensorFlow.

### Additional Info

Criteria when loading the model. This comes from the COVID example code.

```
Criteria<BufferedImage, Classifications> criteria = Criteria.builder()
                .setTypes(BufferedImage.class, Classifications.class).optTranslator(new MyTranslator())
                .optProgress(new ProgressBar()).build();
```

**Comment by frankfliu** [comment]
@murphye Thanks for reporting this issue.
I will take a look and see how can we improve this.

**Comment by murphye** [comment]
@frankfliu In looking at the underlying code, there seems to be some code that looks for a `.pb` but maybe its not recursing into subdirectories. Sorry I lost the reference.

**Comment by frankfliu** [comment]
@murphye I fixed this bug in [this commit](https://github.com/awslabs/djl/commit/30c578ef1027f9ff24a691ca1e58a9cf0622f0e8)

Please see documentation regarding customize model directory in url: https://github.com/awslabs/djl/blob/master/docs/load_model.md#load-model-from-a-url
