### ISSUE TITLE
Add support for Ellipsis notation

### ISSUE THREAD

**Issue by waicool20** [awslabs/djl#69]
## Description

DJL currently has `:` notation support for ndarray access using `NDIndex` but no `...` notation which is typically used to signify unspecified dimensions.

### Who will benefit from this feature?

Existing `:` based index can be simplified eg. `:, :, :, 2` => `..., 2`
It should also make it easier to port python examples to DJL that use such notation.

## References
https://python-reference.readthedocs.io/en/latest/docs/brackets/ellipsis.html

**Comment by stu1130** [comment]
@waicool20 ellipsis is supported by https://github.com/awslabs/djl/commit/7ed0b145519f67f601413937e7c88a1899b565dc

**Comment by waicool20** [comment]
Thanks, works great!
