### ISSUE TITLE
Ability to load modules from TensorFlow Hub

### ISSUE THREAD

**Issue by cowwoc** [awslabs/djl#70]
## Description
Please add the ability to load modules from TensorFlow Hub. For example, I'd want to be able to download, save and use their universal-sentence-encoder model.

**Comment by frankfliu** [comment]
@cowwoc DJL can load a model from a http url already:
```
        System.setProperty("ai.djl.repository.zoo.location", "https://storage.googleapis.com/tfhub-modules/google/universal-sentence-encoder/1.tar.gz?artifact_id=encoder");
        Criteria.Builder<NDList, NDList> builder =
                Criteria.builder()
                        .setTypes(NDList.class, NDList.class)
                        .optArtifactId("ai.djl.localmodelzoo:encoder")
                        .build();
        ZooModel<NDList, NDList> model = ModelZoo.loadModel(criteria);

```

We will add a document to describe how to do it a bit later

**Comment by cowwoc** [comment]
@frankfliu General feedback, I dislike the use of `System.setProperty` for input parameters as it is not thread-safe. I assume you plan to add a separate thread-safe API method to input the URL?

**Comment by frankfliu** [comment]
The system property is a model zoo repository search path, you can specify multiple path with a comma delimited string.
It's not meant to be used in runtime. We can consider add a TfHubModelZoo module that handles url indexing to make it easy to access tf-hub models.

**Comment by frankfliu** [comment]
@cowwoc I added a Criteria.optModelUrls() API, so you don't need to rely on system property any more. See: https://github.com/awslabs/djl/blob/master/docs/load_model.md#load-model-from-a-url
