### ISSUE TITLE
Load my own pytorch or tensorflow model(Not the standard model in model zoo)

### ISSUE THREAD

**Issue by beHappy666** [awslabs/djl#71]
Can i use my own pre-trained model for inferencing?

**Comment by stu1130** [comment]
Sure @beHappy666 you can take a look at [load_your_mxnet_model](https://github.com/awslabs/djl/blob/master/jupyter/load_mxnet_model.ipynb) and [load_your_pytorch_model](https://github.com/awslabs/djl/blob/master/jupyter/load_pytorch_model.ipynb)

**Comment by frankfliu** [comment]
@beHappy666 you can use ModelZoo API load your own model from local file system, http server or even [S3 bucket](https://github.com/awslabs/djl/tree/master/3rdparty/aws-ai#load-model-from-aws-s3-bucket).

And you can also create your own model zoo by implementing: [ZooProvider](https://github.com/awslabs/djl/blob/master/api/src/main/java/ai/djl/repository/zoo/ZooProvider.java) interface

**Comment by beHappy666** [comment]
@stu1130 @frankfliu  thanks

**Comment by frankfliu** [comment]
@beHappy666 I added a document regarding how to load model from local file system and URL: https://github.com/awslabs/djl/blob/master/docs/load_model.md

**Comment by HaoWei-TomTom** [comment]
After reading the links above, I still did not get how to load my own pytorch model. 
I have trained my own pytorch model, and I want to use it in Java. 
Could someone please explain how to do it, or paste an example? Thanks!

**Comment by frankfliu** [comment]
@HaoWei-TomTom Here is youtube link talking about loading a model: https://www.youtube.com/watch?v=POIVT0L_P58

Here is the document about trace pytorch model: https://docs.djl.ai/docs/pytorch/how_to_convert_your_model_to_torchscript.html

And here is the link about how to load pytorch mode: https://docs.djl.ai/jupyter/load_pytorch_model.html

And here is jupyter notebook about how to create translator and load a pytorch BERT model: https://github.com/deepjavalibrary/djl/blob/master/jupyter/pytorch/load_your_own_pytorch_bert.ipynb
