### ISSUE TITLE
BiLSTM support

### ISSUE THREAD

**Issue by raghukiran1224** [awslabs/djl#725]
## Description

Support for BiLSTM layer in DJL.

### Will this change the current api? How?
This will add a new API for layers similar to LSTM, CNN, etc. It should not effect any other APIs.

### Who will benefit from this enhancement?
Folks using BiLSTM models, several new models use BiLSTM layers similar to BERT.

## References
- https://guillaumegenthial.github.io/sequence-tagging-with-tensorflow.html
- https://towardsdatascience.com/lstm-text-classification-using-pytorch-2c6c657f8fc0

**Comment by zachgk** [comment]
There is an option for bidirectional as part of the LSTM block. You can set it like:

```java
Block biLSTM = LSTM.builder()
  .optBidrectional(true)
  ...
  .build()
```

Is that what you are looking for?

**Comment by raghukiran1224** [comment]
Perfect, thank you @zachgk - this is what I was looking for :)

Closing this issue!
