### ISSUE TITLE
Remove no-op {@inheritDoc}

### ISSUE THREAD

**Issue by cowwoc** [awslabs/djl#74]
I noticed multiple instances where the code contains the following Javadoc: `/** {@inheritDoc} */`

This behavior is already the default. Try removing the Javadoc and regenerating the documentation and you will notice that nothing has changed.

The only time you need to use `{@inheritDoc}` is if you plan to augment the inherited Javadoc, which in the above case you do not.

I suggest removing such instances from the source-code.

**Comment by frankfliu** [comment]
@cowwoc there is slightly difference between using *Automatically inherit comment* vs *Explicitly inherit*.

Using *inheritDoc* explicitly can suppress annoying: "Description copied from interface:" in javadoc. And it gave you a bit more control, 
see: https://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javadoc.html#inheritingcomments

**Comment by cowwoc** [comment]
I personally don't mind "Description copied from [interface/class]: X" but understand that you might feel differently. It's odd/unfortunate that we can't configure this behavior once (from command-line?) instead of repeating this preference for every method. You might want to file a RFE with Oracle.
