### ISSUE TITLE
how to do same things in djl ?

### ISSUE THREAD

**Issue by RussiaVk** [awslabs/djl#744]
Following is numpy code ,how to do same things in djl ?

`depth_image[depth_image>250]=0`

**Comment by lanking520** [comment]
array.set(array.gte(250), 0);

**Comment by RussiaVk** [comment]
> array.set(array.gte(250), 0);

It give me error:
The method set(NDIndex, NDArray) in the type NDArray is not applicable for the arguments (NDArray, int)

**Comment by lanking520** [comment]
https://numpy.org/doc/stable/reference/generated/numpy.where.html, DJL has this method as `NDArray.where`. It can solve your issue for now. In 0.11.0 we will add a new set method allow you to throw booleanMask

**Comment by lanking520** [comment]
Now you should be able to do the above operation in 0.11.0-SNAPSHOT :). Close this issue for now. please feel free to reopen if you are still facing the same issue.
