### ISSUE TITLE
How to convert NDArray into opencv Mat Type ?

### ISSUE THREAD

**Issue by RussiaVk** [awslabs/djl#745]
```
color_image = np.array(color_image,dtype='uint8')     
color_gray=cv2.cvtColor(color_image,cv2.COLOR_BGR2GRAY)
```

Hi there,
Above is some python code ,numpy array can be direct put in cvtColor  as arg.
But in java ,"cvtColor"  function need "Mat" as arg.
I tryed bellow java code,But it gave me exception "Invalid number of channels in input image".
So How to convert NDArray into opencv Mat Type ?

```
color_image = manager.create(new Shape(color_image.toLongArray()), DataType.UINT8);
MatOfInt mat_color_image = new MatOfInt();
mat_color_image.fromArray(color_image.toIntArray());
MatOfInt mat_color_gray = new MatOfInt();
Imgproc.cvtColor(mat_color_image, mat_color_gray, Imgproc.COLOR_BGR2GRAY);
```

**Comment by frankfliu** [comment]
@RussiaVk 
By default, DJL Image class read the data as RGB, and Imgcodecs.imread() as BGR.

See the following example:
```
        String filePath = "kitten.jpg";

        ImageFactory factory = ImageFactory.getInstance();
        Image image = factory.fromFile(Paths.get(filePath));
        NDManager manager = NDManager.newBaseManager();
        NDArray array = image.toNDArray(manager);
        byte[] buf = array.toByteArray();
        int width = image.getWidth();
        int height = image.getHeight();

        Mat tmp = new Mat(height, width, CvType.CV_8UC3);
        tmp.put(0, 0, buf);

        Mat matBgr = new Mat();
        Imgproc.cvtColor(tmp, matBgr, Imgproc.COLOR_RGB2GRAY);

        MatOfByte matOfByte = new MatOfByte();
        Imgcodecs.imencode(".jpg", matBgr, matOfByte);
        byte[] byteArray = matOfByte.toArray();

        Path path = Paths.get("kitten_cv.jpg");
        Files.write(path, byteArray);
```

**Comment by RussiaVk** [comment]
> @RussiaVk
> 默认情况下，DJL Image类将数据读取为RGB，将Imgcodecs.imread（）读取为BGR。
> 
> 请参见以下示例：
> 
> ```
>         String filePath = "kitten.jpg";
> 
>         ImageFactory factory = ImageFactory.getInstance();
>         Image image = factory.fromFile(Paths.get(filePath));
>         NDManager manager = NDManager.newBaseManager();
>         NDArray array = image.toNDArray(manager);
>         byte[] buf = array.toByteArray();
>         int width = image.getWidth();
>         int height = image.getHeight();
> 
>         Mat tmp = new Mat(height, width, CvType.CV_8UC3);
>         tmp.put(0, 0, buf);
> 
>         Mat matBgr = new Mat();
>         // Imgproc.cvtColor(tmp, matBgr, Imgproc.COLOR_RGB2GRAY);
>         Imgproc.cvtColor(tmp, matBgr, Imgproc.COLOR_RGB2BGR);
> 
>         MatOfByte matOfByte = new MatOfByte();
>         Imgcodecs.imencode(".jpg", matBgr, matOfByte);
>         byte[] byteArray = matOfByte.toArray();
> 
>         Path path = Paths.get("kitten_cv.jpg");
>         Files.write(path, byteArray);
> ```
Thank you for your reply


> @RussiaVk
> By default, DJL Image class read the data as RGB, and Imgcodecs.imread() as BGR.
> 
> See the following example:
> 
> ```
>         String filePath = "kitten.jpg";
> 
>         ImageFactory factory = ImageFactory.getInstance();
>         Image image = factory.fromFile(Paths.get(filePath));
>         NDManager manager = NDManager.newBaseManager();
>         NDArray array = image.toNDArray(manager);
>         byte[] buf = array.toByteArray();
>         int width = image.getWidth();
>         int height = image.getHeight();
> 
>         Mat tmp = new Mat(height, width, CvType.CV_8UC3);
>         tmp.put(0, 0, buf);
> 
>         Mat matBgr = new Mat();
>         // Imgproc.cvtColor(tmp, matBgr, Imgproc.COLOR_RGB2GRAY);
>         Imgproc.cvtColor(tmp, matBgr, Imgproc.COLOR_RGB2BGR);
> 
>         MatOfByte matOfByte = new MatOfByte();
>         Imgcodecs.imencode(".jpg", matBgr, matOfByte);
>         byte[] byteArray = matOfByte.toArray();
> 
>         Path path = Paths.get("kitten_cv.jpg");
>         Files.write(path, byteArray);
> ```

Thank you for your reply，But I just need convert a "UINT8" type of NDArray into Mat Type 。Is any example about that? thinks again !

**Comment by frankfliu** [comment]
@RussiaVk 
```
// Assume you have a 450 x 300 color image, you can create a NDArray shape is (300, 450, 3), three channel 

int width = 450;
int height = 300;
NDArray nd = manager.create(new Shape(height, width, 3), DataType.UINT8);
...

byte[] buf = nd.toByteArray();
Mat tmp = new Mat(height, width, CvType.CV_8UC3);
tmp.put(0, 0, buf);

```

**Comment by RussiaVk** [comment]
> @RussiaVk
> 
> ```
> // Assume you have a 450 x 300 color image, you can create a NDArray shape is (300, 450, 3), three channel 
> 
> int width = 450;
> int height = 300;
> NDArray nd = manager.create(new Shape(height, width, 3), DataType.UINT8);
> ...
> 
> byte[] buf = nd.toByteArray();
> Mat mat = new Mat(height, width, CvType.CV_8UC3);
> mat.put(0, 0, buf);
> 
> // you got your mat and you can do whatever you want this Mat
> ```

Reall appreciate for your help
