### ISSUE TITLE
How to "return offset mappings" like in hugging face tokenizers?

### ISSUE THREAD

**Issue by KonevDmitry** [awslabs/djl#793]
Good time of day!

How to "return offset mappings" like in hugging face tokenizers for BERT model?
Or, to be more exact, how to return position in original untokenized sequence (text) along with tokens?

Example what I want:

Input sequence:
```
    def cleanup_inner_wrapper(seconds, remove_cmd, remove_reply,
                          args, kwargs, func,  
                          bot, queue, message):  
    # Hook message method on Bot  
    # So everything after that will be catched  
    # And also removed  
    orig_fn = _hook_message(bot, lambda msg: (  
         _remove_message_after(msg, queue, seconds)  
    ))  
    ...  
```
    
 Output:
 ```
    [(0, (0, 0)),  
    ('def', (0, 3)),  
    ('Ġcleanup', (4, 11)),  
    ('_', (11, 12)),  
    ('inner', (12, 17)),  
    ('_', (17, 18)),  
    ('wrapper', (18, 25)),  
    ('(', (25, 26)),  
    ('seconds', (26, 33)),  
    (',', (33, 34)),  
    ('Ġremove', (35, 41)),  
    ('_', (41, 42)),  
    ('cmd', (42, 45)),  
    (',', (45, 46)),  
    ('Ġremove', (47, 53)),  
    ('_', (53, 54)),  
    ('reply', (54, 59)),  
    ...
```

I already implemented needed tokenizer and now I have only tokens from output. How can I find indexes of this tokens? (I hope, there is no need to do it by myself with regex...)

**Comment by lanking520** [comment]
Hi @KonevDmitry Can you point me to the Python code and examples? Basically there is a dictionary (vocabulary) provided by the model, most of the BERT model has a single standard for it. You can just map token into indices.

**Comment by KonevDmitry** [comment]
@lanking520 Hi! 
If I understood correctly, mapped indices from tokens will return token position inside vocabulary while I need position in input sequence.

Here are details what I need: 
Firstly, here is the documentation from [hugging face](https://huggingface.co/transformers/main_classes/tokenizer.html). Parameter is called "return_offsets_mapping". To be brief, text needed to be mentioned is: ```return_offsets_mapping: (optional) Set to True to return (char_start, char_end) for each token (default False).```
Example what I need:
1. [Issue on StackOverflow](https://stackoverflow.com/questions/61821515/how-to-extract-position-input-output-indeces-from-huggingface-transformer-text-t). Here person needed indexes of words inside the sentence. So, if input will be "I love DJL", than the output will be tokens with words positions: <tokens>, [[0,1],[2,6], [7,10]].
2. Here is python code that I need to reproduce:
```
sentence_line1 = tokenizer(data_batch_i['body'], padding='max_length', truncation=True, return_offsets_mapping=True, return_length=True)
```
3. I found collab notebook with output example (last cell): [here](https://colab.research.google.com/drive/1e2a3iyLF9NSMWZR50pnDYRhpizcsRV_6#scrollTo=6a6zknJKB5ax)

4. And finally full Python code that I am trying to move to djl:
```
    source_code = 'def main(task) :\n\n    original = task[\'description\']\n    task[\'description\'] = re.sub(\n        r\'\\b(tw-\\d+)\\b\',\n        r\'https://github.com/GothenburgBitFactory/taskwarrior/issues/\\1\',\n        original,\n        flags=re.IGNORECASE\n    )\n\n    if original != task[\'description\']:\n        logger.info("Link added")'
    tokenizer(source_code, padding='max_length', truncation=True,  return_offsets_mapping=True)
```
Output from code (I will shorten it because it is too huge):
```
{'input_ids': [0, 9232, 1049, ....],  'attention_mask': [1, 1, 1, 1, 1, 1, ...],  'offset_mapping': [(0, 0), (0, 3), (4, 8), (8, 9), (9, 13), (13, 14), (15, 16), (16, 18), (19, 19), (20, 20), ...]}
```
I am interested in field 'offset mappings'.

Can it be achieved with DJL?

**Comment by lanking520** [comment]
From my understanding, this is just some python logics to build the output. DJL current did not offer similar options generate offset_mapping. In fact, all currently avaiable tokenizer are purely implemented in Java referring to the HuggingFace python logic. 

It should be straightforward for you to implment these in Java. Just some regex and space removal operations. The offset mapping is just adding token lengths to the total lengths.

**Comment by KonevDmitry** [comment]
Ok, thank you!
