### ISSUE TITLE
How to use djl to transform image Base64 to NDArray or Tensor

### ISSUE THREAD

**Issue by doctorbean** [awslabs/djl#807]
## Description

(A clear and concise description of what the feature is.)

Will this change the current api? How?
maybe
Who will benefit from this enhancement?
CV developer
## References
- list reference and related literature
- list known implementations

**Comment by frankfliu** [comment]
@doctorbean 
You can use java built-in Base64 encoder to decode the base64 string to byte[] and use ImageFactory to convert to NDArray:
```
byte[] buf = Base64.getDecoder().decode(base64Image);
ImageFactory factory = ImageFactory.getInstance();
Image image = factory.fromInputStream(new ByteArrayInputStream(buf));
NDArray array = image.toNDArray(manager);
```

**Comment by doctorbean** [comment]
thanks



---Original---
From: "Frank ***@***.***&gt;
Date: Fri, Apr 2, 2021 11:15 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [awslabs/djl] How to use djl to transform image Base64 to NDArray or Tensor (#807)




 
@doctorbean
 You can use java built-in Base64 encoder to decode the base64 string to byte[] and use ImageFactory to convert to NDArray:
 byte[] buf = Base64.getDecoder().decode(base64Image); ImageFactory factory = ImageFactory.getInstance(); Image image = factory.fromInputStream(new ByteArrayInputStream(buf)); NDArray array = image.toNDArray(manager);
