### ISSUE TITLE
MuZero on DJL - need advice on stability

### ISSUE THREAD

**Issue by enpasos** [awslabs/djl#813]
I have implemented MuZero with DJL  ([source code](https://github.com/enpasos/muzero)) following closely DeepMind's paper. I have tested it on the trivial game TicTacToe on a single GPU (NVIDIA GeForce RTX 3090). Starting from scratch it learns perfect play within 100.000 training steps and 4.000.000 game plays in a little less than a day.

However, likely due to my lack of deep DJL knowledge, sometimes the DJL code freezes with
"WARN ai.djl.BaseModel - Model: XYZmodel was not closed explicitly."
In that case I stop the java vm and restart it - and everything goes on.

I would like to clean up my code and go on to train non trivial games. But first I would like to get the base running reproducable stable - assuring that I build on solid ground. It would be super awesome if a DJL hero could help me over this hurdle.

**Comment by lanking520** [comment]
Do you have more detailed log of your program? Or code I can take a look?

**Comment by enpasos** [comment]
Hi @lanking520, thank you for looking at the problem. At the moment I can not provide more logging information. If you have something in mind I could switch on, just tell me. You find the source code that I run at https://github.com/enpasos/muzero. Any hint, like "known problem due to typical misusage" or "likely a stability problem in ... that is fixed with version ..." would help.

**Comment by lanking520** [comment]
If there is a warning message about the Model is not closed. It usually caused by the Resource not closed before the process ends. So if you see the warning there, probably the process itself already killed itself. You can try to track the memory consumption of your application and make sure there is no memory leak during the training process.

**Comment by enpasos** [comment]
@lanking520 Thank you for your hints. I will investigate in this direction.

**Comment by enpasos** [comment]
@lanking520 Thanks for you directive. My picture is clearing up. I have a fix candidate and I am testing. Looks like DJL code works like a sharm and the "bug" was on my side using the DJL code.

I can imagine that google/deepmind's muzero is of broader interest due to its proven power to perform, its generallity and its simplicity. Therefore it deserves a better interfacing to DJL than my current lines of code - especially in the area of the "bug" I produced ... and hopefully fixed. 

Let me descibe the problematic area. Maybe you can direct be to a better coded solution (in terms of using DJL nicely, stable, performant).

The MuZero network consists of three functions: representation, prediction and dynamics (sketched in https://enpasos.ai/network2.svg). 
* representation produces a hidden state representation of the current observation derived from the the environment's state.
* prediction produces a policy that suggests what action to take next by providing a probability on all actions in actionspace. And it produces a value that predicts how likely it is to win.
* dynamics takes the hidden state one timestep (half-move in board-games) forward to a new hidden state (+ reward for non board-games)

During selfplay games are played from start to end. Using monte carlo tree search (mcts) is thereby used to decide which (inter)action with the environment to take. To decide on one such action the mcts plays a given number of steps forward (800 in the MuZero paper) "in mind" starting with applying the repesentation function once and then moving forward purely in mind using the dynamics function. With the help of the prediction function the decision tree walked along with the given steps (800) is clever reduced in width (roughly by using the policy) and height (roughly by using the value). 

Now comes the problematic area: Moving data between main memory and GPU is very expensive in terms of performance for the hardware I use (AMD board with  with PCIe4 and NVIDIA RTX 3090).
Therefore I decided to leave the hiddenstate completely on the GPU and never move it to main memory and later back to the GPU. During one mcts run I do not delete any of the hiddenstates as any of them could be necessary later on to use in unfolding the decision tree. However, as far as memory is available on the GPU I run mcts for different games in parallel. 

Leaving the result of inference like the hiddenstate on the device is one aspect that I think is a nontypical usage of DJL. Another aspect is that the training of the functions happens in a combined network that recurrently goes a number of timesteps (5) forward.

My approach was to define the training network the usual way, but defining a "SubModel" for each of the functions, that does not remove the hiddenstate during inference after one inference step is done, but removing them with the full Model after each mcts run.

**Comment by enpasos** [comment]
@lanking520  My tests are ok now. With my fix and the latest DJL snapshot build I do not see the issue anymore. Therefore I can move on with the project. Thanks a lot ... and sure I would be very happy about more advice about how to do a better interfacing to DJL in the area described in my previous comment. However, it would not be fair to keep this issue open for it. 
**Problem Solved :-)  Thank you!**
