### ISSUE TITLE
Just A Question?regarding gpu 

### ISSUE THREAD

**Issue by nikkisingh111333** [awslabs/djl#815]
hey can anybody tell me is djl jupyter kernel provide online GPU training cos i dont have gpu in my machine.please do tell me

**Comment by frankfliu** [comment]
@nikkisingh111333 
You can run DJL jupyter notebook on the machine which has GPU. We are working on a blogpost about running DJL jupyter notebook on AWS SageMaker.

You can also run DJL jupyter notebook on Google Colab. But you need install IJava kernel manually.

**Comment by nikkisingh111333** [comment]
So sir please can you provide me guide of how can I setup dJL on Google
colab I m almost a begginer due to My java environment I just stopped using
deeplearning4j cause it's something broken library ...Please send me some
guide on how to setup djl on colab for faster GPU online training..Glad
