### ISSUE TITLE
MXNET GPU CUDA missmatch Problem?

### ISSUE THREAD

**Issue by nikkisingh111333** [awslabs/djl#824]
hey i m  new here ,today i have successfully install ijava kernel in google colab and java is running successfully BUT when i train i got this ERROR :
`ai.djl.engine.EngineException: MXNet engine call failed: MXNetError: Compile with USE_CUDA=1 to enable GPU usage
Stack trace:
 File "src/storage/storage.cc", line 119
 at ai.djl.mxnet.jna.JnaUtils.checkCall(JnaUtils.java:1909)
at ai.djl.mxnet.jna.JnaUtils.createNdArray(JnaUtils.java:349)
	at ai.djl.mxnet.engine.MxNDManager.create(MxNDManager.java:91)
	at ai.djl.mxnet.engine.MxNDManager.create(MxNDManager.java:34)
	at ai.djl.ndarray.NDManager.create(NDManager.java:526)
	at ai.djl.mxnet.engine.MxNDArray.duplicate(MxNDArray.java:184)
	at ai.djl.mxnet.engine.MxNDArray.toDevice(MxNDArray.java:197)
	at ai.djl.training.ParameterStore.getValue(ParameterStore.java:110)
	at ai.djl.training.Trainer.lambda$initialize$1(Trainer.java:120)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at ai.djl.training.Trainer.initialize(Trainer.java:117)
	at .(#76:1)`
heres my training phase:

**_int batchSize = 32;
int limit = Integer.MAX_VALUE; // change this to a small value for a dry run
// int limit = 160; // limit 160 records in the dataset for a dry run
Pipeline pipeline = new Pipeline(
    new ToTensor(),
    new Normalize(new float[] {0.4914f, 0.4822f, 0.4465f}, new float[] {0.2023f, 0.1994f, 0.2010f}));
Cifar10 trainDataset = 
    Cifar10.builder()
    .setSampling(batchSize, true)
    .optUsage(Dataset.Usage.TRAIN)
    .optLimit(limit)
    .optPipeline(pipeline)
    .build();
trainDataset.prepare(new ProgressBar());
DefaultTrainingConfig config = new DefaultTrainingConfig(Loss.softmaxCrossEntropyLoss())
    //softmaxCrossEntropyLoss is a standard loss for classification problems
    .addEvaluator(new Accuracy()) // Use accuracy so we humans can understand how accurate the model is
    .optDevices(new Device[]{Device.gpu(0)}) // Limit your GPU, using more GPU actually will slow down coverging
    .addTrainingListeners(TrainingListener.Defaults.logging());
// Now that we have our training configuration, we should create a new trainer for our model
Trainer trainer = model.newTrainer(config);
int epoch = 10;
Shape inputShape = new Shape(1, 3, 32, 32);
trainer.initialize(inputShape);
for (int i = 0; i < epoch; ++i) {
    int index = 0;
    for (Batch batch : trainer.iterateDataset(trainDataset)) {
        EasyTrain.trainBatch(trainer, batch);
        trainer.step();
        batch.close();
    }
    // reset training and validation evaluators at end of epoch
    trainer.notifyListeners(listener -> listener.onEpoch(trainer));
}`_**

I know it CUDA related error in google colab its showing cuda-10.0 installed i have alse tried installing mxnet-cu90 using this Cmd:
`!pip install mxnet-cu90` 
Still not working ..
Please help me through this ??

**Comment by zachgk** [comment]
What are you maven/gradle dependencies? It looks like you are using the CPU MXNet (ai.djl.mxnet:mxnet-native-mkl:1.7.0-backport:linux-x86_64). It doesn't include support for GPU. You should switch to either the GPU version or auto (ai.djl.mxnet:mxnet-native-auto). See the [MXNet Engine docs](http://docs.djl.ai/mxnet/mxnet-engine/index.html) for more details

**Comment by nikkisingh111333** [comment]
heres my dependency check it out:
`%maven ai.djl:api:0.10.0
%maven ai.djl:basicdataset:0.10.0
%maven ai.djl.mxnet:mxnet-engine:0.10.0
%maven ai.djl.mxnet:mxnet-model-zoo:0.10.0
%maven org.slf4j:slf4j-api:1.7.26
%maven org.slf4j:slf4j-simple:1.7.26
%maven net.java.dev.jna:jna:5.3.0
// See https://github.com/awslabs/djl/blob/master/mxnet/mxnet-engine/README.md
// for more MXNet library selection options
%maven ai.djl.mxnet:mxnet-native-auto:1.7.0-backport`
what should i change ??

**Comment by aksrajvanshi** [comment]
Depending on your OS, you should be using `ai.djl.mxnet:mxnet-native-auto:1.7.0-backport` for windows, `ai.djl.mxnet:mxnet-native-cu102mkl:1.7.0-backport:linux-x86_64` - CUDA 10.2
`ai.djl.mxnet:mxnet-native-cu101mkl:1.7.0-backport:linux-x86_64 `- CUDA 10.1 for linux and the corresponding CUDA version.

**Comment by nikkisingh111333** [comment]
i understand but what about mxnet whats the current MXnet Version and Which cuda version should i use ?

**Comment by nikkisingh111333** [comment]
when im running your code i m getting runtime exception here:
`java.lang.RuntimeException: Exception occurred while running line magic 'maven': Error resolving 'ai.djl.mxnet:mxnet-native-cu101mkl:1.7.0-backport:linux-x86_64-CUDA-10.1'. [unresolved dependency: ai.djl.mxnet#mxnet-native-cu101mkl;linux-x86_64-CUDA-10.1: not found, unresolved dependency: ai.djl.mxnet#mxnet-native-cu101mkl;linux-x86_64-CUDA-10.1: not found]
	at io.github.spencerpark.ijava.runtime.Magics.lineMagic(Magics.java:19)
       at .(#293:1)`
i have also checked maven ....Its Not found

**Comment by aksrajvanshi** [comment]
Before loading the libraries, try running this command 

`!curl -O https://raw.githubusercontent.com/aws-samples/d2l-java/master/tools/colab_build.sh && bash colab_build.sh`

Once you run this, switch the run time to java and using GPU in Colab. 

It's the same example as this -> https://colab.research.google.com/github/aws-samples/d2l-java/blob/colab/chapter_multilayer-perceptrons/mlp-scratch.ipynb (here the version is 0.8.0, so update it to 0.10.0 like this ->

```
%maven ai.djl:api:0.10.0
%maven ai.djl:model-zoo:0.10.0
%maven ai.djl.mxnet:mxnet-engine:0.10.0
%maven ai.djl.mxnet:mxnet-model-zoo:0.10.0
%maven org.slf4j:slf4j-api:1.7.26
%maven org.slf4j:slf4j-simple:1.7.26
%maven net.java.dev.jna:jna:5.3.0

// See https://github.com/awslabs/djl/blob/master/mxnet/mxnet-engine/README.md
// for more MXNet library selection options
%maven ai.djl.mxnet:mxnet-native-auto:1.7.0-backport
```

Let me know if you face further problems. The maven error should go away.

**Comment by nikkisingh111333** [comment]
maven error has been gone BUT the main issue still here:
`ai.djl.engine.EngineException: MXNet engine call failed: MXNetError: Compile with USE_CUDA=1 to enable GPU usage
Stack trace:
File "src/storage/storage.cc", line 119
`
Now what ????

**Comment by aksrajvanshi** [comment]
Now the Cuda 10.1 or 10.2 should work. Try import these through maven like this:

`%maven ai.djl.mxnet:mxnet-native-cu101mkl:1.7.0-backport` or 

`%maven ai.djl.mxnet:mxnet-native-cu102mkl:1.7.0-backport`

**Comment by nikkisingh111333** [comment]
issue not resolving ..still getting the same error ....i dont know what to
do now ?

**Comment by aksrajvanshi** [comment]
Try `pip install mxnet-cu102` ?

**Comment by nikkisingh111333** [comment]
i have tried it but not working ..  i have checked *!nvidia-smi* cmd and
its showing CUDA version 11.2 running..now how to match cuda with mxnet
version...and one more thing..is this error will also occur in Tensorflow
DJL engine or anyother if i will try my hand on it..if this does'not
resolve..please guide me through ?

**Comment by aksrajvanshi** [comment]
I think you need to update your CUDA version to 10.2 from the CUDA website. https://developer.nvidia.com/cuda-downloads

@frankfliu @zachgk Could you help me in resolving this problem ?

**Comment by nikkisingh111333** [comment]
How do I do that? Does google colab by default 11.2 cuda enabled ....How
can I update it..

**Comment by nikkisingh111333** [comment]
Hey when I see in depth I see when I m executing criteria api for. Model
building I m also getting this ..

No matching cuda flavour for linux found:cu100mkl/sm_75.

Now what does it mean?

**Comment by zachgk** [comment]
Did you figure out how to get the right CUDA? DJL MXNet only supports CUDA 10.1 and 10.2, so you need to install either of those versions on colab. DJL auto engine is using CPU because it could not find a compatible CUDA version on your machine (and 11.2 is not currently compatible).

To install CUDA, I think you can just treat the Colab as a linux machine and install it directly.

**Comment by nikkisingh111333** [comment]
i m a window guy so i dont know how to install....specially on colab which
is a cloud platform...can you please guide me or give any reference where i
can download CUDA 10.2 ?

**Comment by aksrajvanshi** [comment]
https://www.geeksforgeeks.org/how-to-run-cuda-c-c-on-jupyter-notebook-in-google-colaboratory/

Try the steps in the link and get the CUDA version fixed to 10.1/10.2 and try again.

**Comment by nikkisingh111333** [comment]
okk i ll check it out

**Comment by nikkisingh111333** [comment]
problem is not resolving i ve tried all commands :
FOR REMOVING CUDA VERSION
`!apt-get --purge remove cuda nvidia* libnvidia-*
!dpkg -l | grep cuda- | awk '{print $2}' | xargs -n1 dpkg --purge
!apt-get remove cuda-*
!apt autoremove
!apt-get update`

FOR INSTALLING CUDA 10.1:

`!wget  --no-clobber https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.1.105-1_amd64.deb
#install CUDA kit dpkg
!dpkg -i cuda-repo-ubuntu1804_10.1.105-1_amd64.deb
!sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
!apt-get update
!apt-get install cuda-10-1`

after hitting **!nvcc --version** i m getting 10.1 installed succeesfully but when switching to JAVA environement and running my codes i m getting same THIS ERROR:
**`ai.djl.engine.EngineException: MXNet engine call failed: MXNetError: Compile with USE_CUDA=1 to enable GPU usage`** .
what can i do..and When i switch from python to java ...it again by default changes to cuda 11 automatically.. what should i do i have no clues right now for this problem..

**Comment by nikkisingh111333** [comment]
UPDATE:i ve again re run everything from scatch ..
1.install mx-cu101 succesfully
2.remove cuda 11 succesfully
3.install cuda 10.1 succesfully
4.rerun java dependencies mx-101 
now i m getting this error while executing Criteria api;
**`WARN ai.djl.engine.Engine - Failed to load engine from: ai.djl.mxnet.engine.MxEngineProvider
ai.djl.engine.EngineException: Failed to load MXNet native library`**
before i was getting no matching flavour of cuda found warning not error..but now I m getting an error/exception
..what should i do its really screwing up..??please help me ..

**Comment by lanking520** [comment]
@nikkisingh111333 can you provide me the project files (in a zip?) and I can take a look from there. By the way, which OS you are using here?

**Comment by nikkisingh111333** [comment]
i m using ubuntu 18-04 ...but i m window guy ..by default colab is using ubuntu 18-04...can i send you my ipynb file so that you can open it in your colab and check it out ..just after doing some cleaning ....should i ?

**Comment by nikkisingh111333** [comment]
heres my ipynb file in Zip  :

[Cifar10_New(2)(3)(1)(1)(1).zip](https://github.com/awslabs/djl/files/6280659/Cifar10_New.2.3.1.1.1.zip)

**Comment by aksrajvanshi** [comment]
@nikkisingh111333 
Thanks for the code! So, you can do the following things. It's not the best workaround but it works!

Stay in the Python runtime and run this command:

`!curl -O https://raw.githubusercontent.com/aws-samples/d2l-java/master/tools/colab_build.sh && bash colab_build.sh`

Refresh the page and stay at the Python runtime on GPU. Run the following commands then:

```
!sudo rm /usr/local/cuda
!ln -s /usr/local/cuda-10.1 /usr/local/cuda
!ln -s /usr/local/cuda/lib64/libcudart.so /usr/lib64-nvidia
!nvcc --version
```

You should see CUDA 10.1 then

After that, move onto the Java runtime and on GPU and run your code from %maven commands.

**Comment by nikkisingh111333** [comment]
its running smooth as ice....thanks brother....you are great..can you please share me what i was doing wrong so that i can avoid making this mistake..? again thank you so much

**Comment by aksrajvanshi** [comment]
@nikkisingh111333 Great! So this wasn't exactly your problem. This is more of a colab problem. First of all, MXNet needed Cuda 10.1 or 10.2 to work. 

Secondly, DJL needs the libcudart file at the $LD_LIBRARY_PATH environment variable which wasn't there. Initially LD_LIBRARY_PATH was pointing to /usr/lib64-nvidia. We created a symbolic link that allowed DJL to locate the libcudart file.

We can try to do something which would make it easy for users to use DJL on colab along with GPU :) 

Also, if you're starting with Deep Learning, you can start with this book. (https://d2l.djl.ai/)

**Comment by nikkisingh111333** [comment]
Awesome, thanks! Please just let me update if you change or Do anything
special with colab so that I can adapt quickly .....I m gladly looking
forward to see it.

**Comment by lanking520** [comment]
@aksrajvanshi as a further action, can you update the colab instruction in D2L book so we can automate this process next time?
