### ISSUE TITLE
PaddlePaddle ocr example crashed

### ISSUE THREAD

**Issue by hackedbyxx** [awslabs/djl#838]
## Description
(A clear and concise description of what the bug is.)
PaddlePaddle ocr example crashed when i ocr another picture
![20181230_c2222f5782a5420e8b42d89e585a11e8](https://user-images.githubusercontent.com/19482737/114158134-f2856e00-9956-11eb-8ddc-97a46d32ce6c.jpeg)
### Expected Behavior
(what's the expected behavior?)
JVM crashed
### Error Message
(Paste the complete error message, including stack trace.)
ARNING: Logging before InitGoogleLogging() is written to STDERR
W0409 17:07:45.859364 25780 analysis_predictor.cc:1059] Deprecated. Please use CreatePredictor instead.
I0409 17:07:45.859364 25780 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0409 17:07:45.982364 25780 graph_pattern_detector.cc:101] ---  detected 33 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
I0409 17:07:45.994366 25780 graph_pattern_detector.cc:101] ---  detected 1 subgraphs
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0409 17:07:46.062363 25780 analysis_predictor.cc:548] ======= optimize end =======
I0409 17:07:46.062363 25780 naive_executor.cc:107] ---  skip [feed], feed -> x
I0409 17:07:46.064363 25780 naive_executor.cc:107] ---  skip [save_infer_model/scale_0.tmp_1], fetch -> fetch
I0409 17:07:46.067366 25780 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
I0409 17:07:46.067366 25780 naive_executor.cc:107] ---  skip [feed], feed -> x
I0409 17:07:46.070394 25780 naive_executor.cc:107] ---  skip [save_infer_model/scale_0.tmp_1], fetch -> fetch
W0409 17:07:47.504354 25780 analysis_predictor.cc:1059] Deprecated. Please use CreatePredictor instead.
I0409 17:07:47.504354 25780 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [reshape2_matmul_fuse_pass]e[0m
I0409 17:07:47.564352 25780 graph_pattern_detector.cc:101] ---  detected 1 subgraphs
e[32m--- Running IR pass [flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [map_matmul_to_mul_pass]e[0m
I0409 17:07:47.565352 25780 graph_pattern_detector.cc:101] ---  detected 1 subgraphs
e[32m--- Running IR pass [fc_fuse_pass]e[0m
I0409 17:07:47.566351 25780 graph_pattern_detector.cc:101] ---  detected 1 subgraphs
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0409 17:07:47.603384 25780 graph_pattern_detector.cc:101] ---  detected 24 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0409 17:07:47.661382 25780 analysis_predictor.cc:548] ======= optimize end =======
I0409 17:07:47.661382 25780 naive_executor.cc:107] ---  skip [feed], feed -> x
I0409 17:07:47.664384 25780 naive_executor.cc:107] ---  skip [save_infer_model/scale_0.tmp_1], fetch -> fetch
I0409 17:07:47.664384 25780 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
I0409 17:07:47.664384 25780 naive_executor.cc:107] ---  skip [feed], feed -> x
I0409 17:07:47.667392 25780 naive_executor.cc:107] ---  skip [save_infer_model/scale_0.tmp_1], fetch -> fetch
W0409 17:07:47.679383 25780 analysis_predictor.cc:1059] Deprecated. Please use CreatePredictor instead.
I0409 17:07:47.679383 25780 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [map_matmul_to_mul_pass]e[0m
I0409 17:07:47.733382 25780 graph_pattern_detector.cc:101] ---  detected 1 subgraphs
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0409 17:07:47.771381 25780 graph_pattern_detector.cc:101] ---  detected 24 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The input tensor's dimension should be equal to the axis's size. But received input tensor's dimension is 4, axis's size is 3
  [Hint: Expected x_rank == axis_size, but received x_rank:4 != axis_size:3.] (at D:\v2.0.0\paddle\paddle\fluid\operators\transpose_op.cc:47)

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007ffe1b9b3e49, pid=29908, tid=25780
#
# JRE version: Java(TM) SE Runtime Environment 18.9 (11.0.7+8) (build 11.0.7+8-LTS)
# Java VM: Java HotSpot(TM) 64-Bit Server VM 18.9 (11.0.7+8-LTS, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [KERNELBASE.dll+0x23e49]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# \hs_err_pid29908.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
I0409 17:07:47.826381 25780 analysis_predictor.cc:548] ======= optimize end =======
I0409 17:07:47.826381 25780 naive_executor.cc:107] ---  skip [feed], feed -> x
I0409 17:07:47.829383 25780 naive_executor.cc:107] ---  skip [save_infer_model/scale_0.tmp_1], fetch -> fetch
I0409 17:07:47.829383 25780 analysis_predictor.cc:139] Profiler is deactivated, and no profiling report will be generated.
I0409 17:07:47.829383 25780 naive_executor.cc:107] ---  skip [feed], feed -> x
I0409 17:07:47.832397 25780 naive_executor.cc:107] ---  skip [save_infer_model/scale_0.tmp_1], fetch -> fetch

Process finished with exit code 1

here is the picture

**Comment by lanking520** [comment]
Hi @hackedbyxx thanks for reporting the issue. 

It should have fixed in the 0.11.0-SNAPSHOT.

You can try with this jar through adding the https://github.com/awslabs/djl/blob/master/examples/pom.xml#L17-L22 SNAPSHOT repo.


You can use the nightly snapshot to fix that.

Or otherwise, simply patch the code change in here: https://github.com/awslabs/djl/pull/775 to your PaddleOCR translator and it should fix the error.

**Comment by hackedbyxx** [comment]
> Hi @hackedbyxx thanks for reporting the issue.
> 
> It should have fixed in the 0.11.0-SNAPSHOT.
> 
> You can try with this jar through adding the https://github.com/awslabs/djl/blob/master/examples/pom.xml#L17-L22 SNAPSHOT repo.
> 
> You can use the nightly snapshot to fix that.
> 
> Or otherwise, simply patch the code change in here: https://github.com/awslabs/djl/blob/master/paddlepaddle/paddlepaddle-model-zoo/src/main/java/ai/djl/paddlepaddle/zoo/cv/wordrecognition/PpWordRecognitionTranslator.java#L80-L84 to your PaddleOCR translator and it should fix the error.

Ok,thanks

**Comment by hackedbyxx** [comment]
> Hi @hackedbyxx thanks for reporting the issue.
> 
> It should have fixed in the 0.11.0-SNAPSHOT.
> 
> You can try with this jar through adding the https://github.com/awslabs/djl/blob/master/examples/pom.xml#L17-L22 SNAPSHOT repo.
> 
> You can use the nightly snapshot to fix that.
> 
> Or otherwise, simply patch the code change in here: https://github.com/awslabs/djl/blob/master/paddlepaddle/paddlepaddle-model-zoo/src/main/java/ai/djl/paddlepaddle/zoo/cv/wordrecognition/PpWordRecognitionTranslator.java#L80-L84 to your PaddleOCR translator and it should fix the error.

I've tried to change to the 0.11.0-SNAPSHOT,but it cant't  import package in the repository https://oss.sonatype.org/content/repositories/snapshots/

**Comment by lanking520** [comment]
So 
```
    <repositories>
        <repository>
            <id>djl.ai</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
    </repositories>
```
This doesn't work? @frankfliu do we have any spare repos?

**Comment by hackedbyxx** [comment]
![image](https://user-images.githubusercontent.com/19482737/114687514-6dc79500-9d46-11eb-9039-ae3434ff75fe.png)
Yes,it seems doesn't work

**Comment by hackedbyxx** [comment]
> So
> 
> ```
>     <repositories>
>         <repository>
>             <id>djl.ai</id>
>             <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
>         </repository>
>     </repositories>
> ```
> 
> This doesn't work? @frankfliu do we have any spare repos?

Yes,it seems doesn't work

**Comment by lanking520** [comment]
@hackedbyxx can you share your pom.xml here? I can help to take alook

**Comment by hackedbyxx** [comment]
@lanking520 
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.1.RELEASE</version>
        <relativePath/> 
    </parent>

    <properties>
        <java.version>11</java.version>
        <jna.version>5.3.0</jna.version>
        <djl.version>0.11.0-SNAPSHOT</djl.version>
    </properties>

    <repositories>
        <repository>
            <id>djl</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>ai.djl</groupId>
                <artifactId>bom</artifactId>
                <version>${djl.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>api</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>basicdataset</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>model-zoo</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl.mxnet</groupId>
            <artifactId>mxnet-model-zoo</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl.mxnet</groupId>
            <artifactId>mxnet-engine</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl.mxnet</groupId>
            <artifactId>mxnet-native-auto</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>commons-cli</groupId>
            <artifactId>commons-cli</artifactId>
            <version>1.4</version>
        </dependency>
        <dependency>
            <groupId>ai.djl.paddlepaddle</groupId>
            <artifactId>paddlepaddle-model-zoo</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl.paddlepaddle</groupId>
            <artifactId>paddlepaddle-native-auto</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-freemarker</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>

**Comment by hackedbyxx** [comment]
@lanking520 I've solved this problems by remove all the mirrors in maven setting,thanks
