### ISSUE TITLE
Tensorflow Docs not working?

### ISSUE THREAD

**Issue by nikkisingh111333** [awslabs/djl#846]
hey ,i want to train a object detector and want to do it in tensorflow..rather than MxNet...heres what i m doing following the docs provided on djl website :
**MY SETUP**
`!curl -O https://raw.githubusercontent.com/aws-samples/d2l-java/master/tools/colab_build.sh && bash colab_build.sh
!sudo rm /usr/local/cuda
!ln -s /usr/local/cuda-10.1 /usr/local/cuda
!ln -s /usr/local/cuda/lib64/libcudart.so /usr/lib64-nvidia
!nvcc --version
!python3 install.py --sys-prefix
!pip install pyngrok --quiet`

**DEPENDENCY PART**
`%maven org.slf4j:slf4j-api:1.7.26
%maven org.slf4j:slf4j-simple:1.7.26
%maven net.java.dev.jna:jna:5.3.0
%maven ai.djl:basicdataset:0.10.0
%maven ai.djl:api:0.10.0
%maven ai.djl:model-zoo:0.10.0
%maven ai.djl.tensorflow:tensorflow-native-auto:2.3.1
%maven ai.djl.tensorflow:tensorflow-engine:0.10.0
%maven ai.djl.tensorflow:tensorflow-model-zoo:0.10.0
%maven ai.djl.tensorflow:tensorflow-api:0.10.0`
**My imports**:
`import ai.djl.Application;
import ai.djl.Model;
import ai.djl.ModelException;
import ai.djl.engine.Engine;
import ai.djl.inference.Predictor;
import ai.djl.modality.cv.Image;
import ai.djl.modality.cv.ImageFactory;
import ai.djl.modality.cv.output.BoundingBox;
import ai.djl.modality.cv.output.DetectedObjects;
import ai.djl.modality.cv.output.Rectangle;
import ai.djl.modality.cv.util.NDImageUtils;
import ai.djl.ndarray.NDArray;
import ai.djl.ndarray.NDList;
import ai.djl.ndarray.NDManager;
import ai.djl.ndarray.types.DataType;
import ai.djl.repository.zoo.Criteria;
import ai.djl.repository.zoo.ModelZoo;
import ai.djl.repository.zoo.ZooModel;
import ai.djl.training.util.ProgressBar;
import ai.djl.translate.Batchifier;
import ai.djl.translate.TranslateException;
import ai.djl.translate.Translator;
import ai.djl.translate.TranslatorContext;
import ai.djl.util.JsonUtils;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Scanner;
import java.util.concurrent.ConcurrentHashMap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;`

**testing**:
`var engine=Engine.getInstance().getEngineName();
engine`
  **ERROR  I M GETTING**
`ai.djl.engine.EngineException: No deep learning engine found.
Please refer to https://github.com/awslabs/djl/blob/master/docs/development/troubleshooting.md for more details.
	at ai.djl.engine.Engine.getInstance(Engine.java:120)
	at .do_it$Aux(#99:1)
	at .(#99:1)`
WHAT I M DOING WRONG
when hitting this code on python enviornment
`import tensorflow as tf
print(tf.__version__)`
out:2.4.1
..tensorflow 2.4 is there ..how to make it work in djl ...guide me pleaase

**Comment by stu1130** [comment]
@nikkisingh111333 we don't support TensorFlow training. Currently only MXNet engine is fully supported for training capability. PyTorch is still working in progress and has not yet well-tested.

**Comment by nikkisingh111333** [comment]
okk so it means i cannot import tensorflow model which i hve trained on
teachable machine into djl...please i want to ask few things:
1.how can i train ssd model oer any other object detector in djl..i mean
fine tune it..all example i m seeing are just using pre trained model
instead of training them on out own dataset
2.when will be TF for djl
please i want to create some awesome projects which i m unable to do since
i cannot find right AI environment in java ..i m Counting on DJL..

**Comment by zachgk** [comment]
You can find examples of training in https://github.com/awslabs/djl/tree/master/examples/src/main/java/ai/djl/examples/training
