### ISSUE TITLE
PyTorch 1.8.1 - CUDA 11.1 - Windows 10 - unsatisfied link 

### ISSUE THREAD

**Issue by enpasos** [awslabs/djl#847]
I am running into a Problem on a MS Windows 10 OS.

With  djl.version=0.11.0-SNAPSHOT and

```
      <dependency>
          <groupId>ai.djl.pytorch</groupId>
          <artifactId>pytorch-native-auto</artifactId>
          <version>1.8.1-SNAPSHOT</version>
      </dependency>
```
on CUDA 11.1 I get a java.lang.UnsatisfiedLinkError. I see links to the following libraries that are not found
![dll_missing](https://user-images.githubusercontent.com/9622808/114427652-9707ea00-9bbb-11eb-8212-a2ba5ba34549.PNG)

on CUDA 10.2 (on a Turing GPU) everything works fine.

**Comment by lanking520** [comment]
@goswamig Please check the CUDA dependencies missing issue.

**Comment by lanking520** [comment]
Looks like we are missing packages around here. Do you find any other packages that are missing? @enpasos

**Comment by lanking520** [comment]
We tried to fix it with : #850 and #852. Please try again once the nightly build is passed: https://github.com/awslabs/djl/actions/runs/743340536

**Comment by enpasos** [comment]
Thanks. 
Nightly build says past.
I still get the unsatisfied link exception on 
![grafik](https://user-images.githubusercontent.com/9622808/114500952-5646ba00-9c29-11eb-968e-92f8e2e9914e.png)

In dependency analyser I see
![grafik](https://user-images.githubusercontent.com/9622808/114500738-f6e8aa00-9c28-11eb-81aa-28cf9d28050a.png)
and in my filesystem
![grafik](https://user-images.githubusercontent.com/9622808/114500777-0b2ca700-9c29-11eb-8b92-84c64df5fe86.png)

**Comment by lanking520** [comment]
@enpasos you can clean up cache, like delete .djl.ai and try again.

**Comment by enpasos** [comment]
@lanking520 deleted .djl.ai and .m2 ... tried again ... same picture as reported above

**Comment by lanking520** [comment]
@enpasos can you try with auto package? This change is not on Maven snapshot yet

**Comment by enpasos** [comment]
@lanking520 What do I have to do for "auto package"?

**Comment by enpasos** [comment]
Is it more than
![grafik](https://user-images.githubusercontent.com/9622808/114504270-e804f600-9c2e-11eb-9677-2fb593625214.png)

**Comment by lanking520** [comment]
@enpasos Nope, let me clean up the cloud front cache and help you out。 Now please try again

**Comment by enpasos** [comment]
@lanking520 Thank you. Now the two missing dependencies are there. Java still complains but my dependency analyser says ok. I will investigate ... will take some time.

**Comment by lanking520** [comment]
@enpasos try to set a break point here: https://github.com/awslabs/djl/blob/master/pytorch/pytorch-engine/src/main/java/ai/djl/pytorch/jni/LibUtils.java#L120 and debug line by line. Let me know which line you hit the unsatisfied link issue

**Comment by enpasos** [comment]
@lanking520

I debugged LibUtils ... it was not reaching the code you added ... but after adding the libraries to the "load later set" it worked and the "unsatisfied link" problem diappeared

![grafik](https://user-images.githubusercontent.com/9622808/114606682-dd347a80-9c9b-11eb-9f75-559bb020ba27.png)

**Comment by lanking520** [comment]
@enpasos nice catch! I will apply this change accordingly

**Comment by enpasos** [comment]
I checked out the lates code with #854, compiled it, tested -> **problem solved**
