### ISSUE TITLE
maybe the DJL_VERSION in the build.gradle & pom.xml  of examples should be updated

### ISSUE THREAD

**Issue by heartzeus** [awslabs/djl#92]
## Description
(A clear and concise description of what the bug is.)

### Expected Behavior
(what's the expected behavior?)

### Error Message
(Paste the complete error message, including stack trace.)

## How to Reproduce?
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

## Environment Info

Please run the command `./gradlew debugEnv` from the root directory of DJL (if necessary, clone DJL first). It will output information about your system, environment, and installation that can help us debug your issue. Paste the output of the command below:

```
PASTE OUTPUT HERE
```

**Comment by frankfliu** [comment]
DJL_VERSION  is updated to 0.6.0-SNAPSHOT:
https://github.com/awslabs/djl/blob/master/examples/build.gradle#L13
