### ISSUE TITLE
wishing that you can add a image vector extraction using djl model to examples 

### ISSUE THREAD

**Issue by yanchaoguo** [awslabs/djl#93]
## Description
(A clear and concise description of what the feature is.)

## References
- list reference and related literature
- list known implementations

**Comment by frankfliu** [comment]
Now have an example of face feature extraction: https://github.com/awslabs/djl/blob/master/examples/src/main/java/ai/djl/examples/inference/face/FeatureExtraction.java

**Comment by yanchaoguo** [comment]
> Now have an example of face feature extraction: https://github.com/awslabs/djl/blob/master/examples/src/main/java/ai/djl/examples/inference/face/FeatureExtraction.java

这种方式提取的特征长度是固定的吗

**Comment by frankfliu** [comment]
For this model the output length is fixed.

**Comment by yanchaoguo** [comment]
> For this model the output length is fixed.

可惜该模型只能提取人脸特征

**Comment by yanchaoguo** [comment]
> For this model the output length is fixed.

模型文件和一些dll文件 国内无法访问

**Comment by frankfliu** [comment]
There are a lot of feature vector models on TF hub: https://tfhub.dev/s?module-type=image-feature-vector

It should be very straightforward to load with DJL.
