### ISSUE TITLE
error scheme exception when loading img dataset  in window environment

### ISSUE THREAD

**Issue by yanchaoguo** [awslabs/djl#95]
Repository.newInstance(type, “d:/data/cars”)
If I set it like this,  will get this error ,must remove "d:/" 
 
Probably because URI creation is not allowed

**Comment by lanking520** [comment]
If this is Windows, should it be `d:\`?

**Comment by yanchaoguo** [comment]
> If this is Windows, should it be `d:\`?

Repository.newInstance(type, “d:\\data\\cars”)
If I set it like this, will also get this error ,must remove "d:\\"

**Comment by frankfliu** [comment]
@yanchaoguo 2nd parameter is a URI, D:\\ or D:// is not a valid URI, you should pass: "file:///d:/data/cars"

It's not intuitive for Windows user. If we support d:\\data format, should we also support UNC (//shareddrive/data ?

I think we made it clear it's a uri not a file path.

**Comment by frankfliu** [comment]
@yanchaoguo A possible enhancement could be add a overload:
Repoistory.newInstance(String name, Path path)
