### ISSUE TITLE
Demo for using personal dataset

### ISSUE THREAD

**Issue by heartzeus** [awslabs/djl#96]
the demo in this blog [Deep Java Library(DJL) — a Deep Learning Toolkit for Java Developers](https://towardsdatascience.com/deep-java-library-djl-a-deep-learning-toolkit-for-java-developers-55d5a45bca7e) is not up2date. can you provide latest demo?

**Comment by frankfliu** [comment]
@heartzeus Will consider add this into our demo repo

**Comment by frankfliu** [comment]
@heartzeus 
I added the footwear classification project in our demo github repo.
You can find a REAME about how to use ImageFolder to load footwear dataset: https://github.com/aws-samples/djl-demo/tree/master/footwear_classification#preparing-the-footwear-dataset
